### ISSUE TITLE
NoSuchMethodError :  com.mikepenz.materialize.MaterializeBuilder.withTranslucentStatusBar

### ISSUE THREAD

**Issue by anvesh523** [mikepenz/MaterialDrawer#1004]
I want to add "crossfadedrawerlayout" in my app...
I am getting this exception at .build() 

```java
FATAL EXCEPTION: main
                                                 java.lang.NoSuchMethodError: com.mikepenz.materialize.MaterializeBuilder.withTranslucentStatusBar
                                                     at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1258)
                                                     at blpacademy.testapp3.ProductDetails.onCreate(ProductDetails.java:72)
                                                     at android.app.Activity.performCreate(Activity.java:5182)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:153)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                     at dalvik.system.NativeStart.main(Native Method)
```
Please provide some solution

**Comment by mikepenz** [comment]
@anvesh523 the current sample works with the `MaterialDrawer` v5.0.0. You may mix it up with a previous version of `Materialize`. So incompatible lib versions?

**Comment by anvesh523** [comment]
Thanks for the reply, I done something wrong as you mention. I followed all the steps from starting, now it's working fine.

**Comment by mikepenz** [comment]
@anvesh523 great :)
