### ISSUE TITLE
OutOfMemoryError after rotate screen multiple times

### ISSUE THREAD

**Issue by ibrahim132** [mikepenz/MaterialDrawer#1097]
My setupAccountHeader method:
```java
private void setupAccountHeader(Bundle savedInstanceState) {

        mAccountHeader = new AccountHeaderBuilder().withActivity(this)
                .withHeaderBackground(getHeaderBackground())
                .withSavedInstance(savedInstanceState)
                .withSelectionListEnabled(false)
                .withProfileImagesClickable(true)
                .withOnAccountHeaderSelectionViewClickListener(this)
                .withOnAccountHeaderProfileImageListener(this)
                .addProfiles(getProfile())
                .build();

    }
```
My getProfile() method:
```java
@Override
    protected IProfile getProfile() {
        return new ProfileDrawerItem()
                .withIdentifier(-1)
                .withIcon(R.drawable.unknwon_profile_pic)
                .withName(getString(R.string.login_or_create_new_account));
    }
```
Bug logcat:
```
FATAL EXCEPTION: main
Process: com.packagename.baseapp, PID: 29404
java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
at android.content.res.Resources.loadDrawable(Resources.java:3436)
at android.content.res.Resources.getDrawable(Resources.java:1909)
at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:805)
at com.packagename.baseawpframework.ui.activities.BaseDrawerDBActivity.setupAccountHeader(BaseDrawerDBActivity.java:89)
at com.packagename.baseawpframework.ui.activities.BaseDrawerDBActivity.initObjects(BaseDrawerDBActivity.java:73)
at com.packagename.baseawpframework.ui.activities.MainActivity.initObjects(MainActivity.java:123)
at com.packagename.baseawpframework.ui.activities.BaseDBActivity.onCreate(BaseDBActivity.java:91)
at com.packagename.baseawpframework.ui.activities.MainActivity.onCreate(MainActivity.java:70)
at android.app.Activity.performCreate(Activity.java:5451)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
at android.app.ActivityThread.access$1000(ActivityThread.java:175)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mikepenz** [comment]
@ibrahim132 do you recreate the activity on screen rotation?

**Comment by ibrahim132** [comment]
I don't understand what do you mean, but i'm calling setupAccountHeader(Bundle savedInstanceState) method in my Activity onCreate() method.

**Comment by mikepenz** [comment]
@ibrahim132 perhaps your image is just to big, and the system can't probably recycle it upon a screen orientation change. Nothing the **MaterialDrawer** can prevent or handle

**Comment by mikepenz** [comment]
Close as it seems related to the size of the used resource. Can't reproduce it with the sample app. 
We can still have a discussion here and try to fix it for you

**Comment by ibrahim132** [comment]
@mikepenz  Thank you for your support. but i removed the custom profile image and still getting the same error.
 I rotate screen multiple times then this error happened.
Please check the Logcat:
```
Process: com.example, PID: 24827
                                                                java.lang.OutOfMemoryError
                                                                    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
                                                                    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)
                                                                    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:3436)
                                                                    at android.content.res.Resources.getDrawable(Resources.java:1909)
                                                                    at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:55)
                                                                    at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:391)
                                                                    at android.support.v7.widget.TintResources.getDrawable(TintResources.java:48)
                                                                    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                                    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                    at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
                                                                    at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
                                                                    at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
                                                                    at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:171)
                                                                    at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:805)
```
The problem is here in this statements:
`ImageHolder.applyTo(mHeaderBackground, mAccountHeaderBackground, DrawerImageLoader.Tags.ACCOUNT_HEADER.name());`
`imageView.setImageResource(getIconRes());`

**Comment by ibrahim132** [comment]
To reproduce this bug please follow the next steps:
1- Add Drawer layout to Activity with Account Header without any profiles.
2- Open the drawer.
3- Rotate screen.
4- OutOfMemoryError.

**Comment by mikepenz** [comment]
@ibrahim132 can't reproduce this on any of my devices. 

As mentioned the library can't change any logic which happens inside the `setImageResource()` as this is done by the support library. 
The **MaterialDrawer** does not keep the drawable, nor does it leak the context.

You are sure nothing else on your side causes the **OOM**. 

You might also check out the sample application and try to reproduce. 

This might be related to: https://github.com/mikepenz/MaterialDrawer/issues/1142
