### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#1102]
Hi.

im trying to implement the standard drawer in my app (the one that shows up when you open the sample app), however i am getting a ResourceNotFoundException and i have no idea why.

this is my code:
```java
		IProfile profile = new ProfileDrawerItem().withName("Homer Simpson").withEmail("doh!@gmail.com").withIcon("http://www.yourtv.com.au/img/blog/homer-simpson.jpg");

		mHeader = new AccountHeaderBuilder()
				.withActivity(this)
						
				.withTranslucentStatusBar(true)
//				.withHeaderBackground(R.drawable.header)
				.addProfiles(profile)
				.withSavedInstance(savedInstanceState)
				.build();

		mDrawer = new DrawerBuilder()
				.withActivity(this)
				.withHasStableIds(true) 
				.withAccountHeader(mHeader)
				.addDrawerItems(new PrimaryDrawerItem().withName("inbox").withIdentifier(DRAWERITEM_ID_INBOX).withSelectable(false), 
								new PrimaryDrawerItem().withName("therapists").withIdentifier(DRAWERITEM_ID_THERAPISTS).withSelectable(false),
								new PrimaryDrawerItem().withName("my treatments").withIdentifier(DRAWERITEM_ID_MYTREATMENTS).withSelectable(false),
								new PrimaryDrawerItem().withName("evaluation").withIdentifier(DRAWERITEM_ID_EVALUATION).withSelectable(false),
								new PrimaryDrawerItem().withName("diagnosis").withIdentifier(DRAWERITEM_ID_DIAGNOSIS).withSelectable(false),
								new PrimaryDrawerItem().withName("calendar").withIdentifier(DRAWERITEM_ID_CALENDAR).withSelectable(false),
								new PrimaryDrawerItem().withName("logout").withIdentifier(DRAWERITEM_ID_LOGOUT).withSelectable(false))
				.withOnDrawerItemClickListener(this)
				.withSavedInstance(savedInstanceState)
				.withShowDrawerOnFirstLaunch(true)
				.build();
```

and this is the exception im getting when trying to run:
```
03-16 17:33:00.454 5022-5022/com.example.videotherapystudio E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.videotherapystudio, PID: 5022
                                                                              android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                  at android.content.res.Resources.getValue(Resources.java:1269)
                                                                                  at android.content.res.Resources.getDrawable(Resources.java:769)
                                                                                  at android.content.Context.getDrawable(Context.java:402)
                                                                                  at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
                                                                                  at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
                                                                                  at com.mikepenz.materialize.util.UIUtils.getSelectableBackground(UIUtils.java:353)
                                                                                  at com.mikepenz.materialize.util.UIUtils.getSelectableBackground(UIUtils.java:285)
                                                                                  at com.mikepenz.materialdrawer.model.BasePrimaryDrawerItem.bindViewHelper(BasePrimaryDrawerItem.java:78)
                                                                                  at com.mikepenz.materialdrawer.model.PrimaryDrawerItem.bindView(PrimaryDrawerItem.java:69)
                                                                                  at com.mikepenz.materialdrawer.model.PrimaryDrawerItem.bindView(PrimaryDrawerItem.java:18)
                                                                                  at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1287)
                                                                                  at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:413)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5453)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5486)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4723)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
                                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3003)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2881)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3265)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1211)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                                  at android.view.View.layout(View.java:15631)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4966)
                                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2101)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5845)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              	at android.os.Looper.

```

i tried to eliminate this error by removing anything that calls for a resource (e.g. no drawable background for header, and hard-coded strings) but to no use... still getting the above error.

i am using version 5.1.3

please help

**Comment by mikepenz** [comment]
@or-dvir on which device do you test? which android version?

**Comment by mikepenz** [comment]
It can't resolve the following: `R.attr.selectableItemBackground`. This is a valid resource, so it seems there is a misconfiguration somewhere

**Comment by or-dvir** [comment]
device is LG G3 android version 5.0

what does it mean there is a misconfiguration somewhere? how can i fix this?

p.s.
could it have anything to do with the fact that im using a fragment activity?

**Comment by mikepenz** [comment]
@or-dvir you already cleaned and rebuilt the project?

Which support libraries do you use?

**Comment by or-dvir** [comment]
yes. i did clean and rebuild, and still getting this exception.

i am using both v4 and v7 support libraries in my app

**Comment by mikepenz** [comment]
@or-dvir which version of those?

**Comment by or-dvir** [comment]
sorry... miss understood your question.

this is what im using:
compile 'com.android.support:support-v4:23.1.1'
compile 'com.android.support:cardview-v7:23.1.1'

although i do receive a warning saying there is a new version, it says it is an alpha version,
so i don't want to use it (i need stable version).

sample app does not crash.

the layout for my activity is actually a viewpager - could that be the problem?

**Comment by mikepenz** [comment]
@or-dvir the latest version of the `MaterialDrawer` requires the latest (stable) support libraries **v23.2.1**
(you get the alpha warning because there is the Android N alpha version of the support libraries)

**Comment by christianguevara** [comment]
I think you should remember also to compile the app using the 23 lib.

**Comment by mikepenz** [comment]
@christianguevara thanks for adding this detail

**Comment by or-dvir** [comment]
ok... ill see if that works when im back at work next week

**Comment by mikepenz** [comment]
@or-dvir ok great. fine.

**Comment by pokerazor** [comment]
I just had exactly the same problem and in my case it was solvable by adding a `android:theme="@style/MaterialDrawerTheme.*"` attribute to the activity tag in the AndroidManifest.xml.
Maybe the same in your case?
The cause was hard to find though and i was only lucky, because the stack trace is too long. Maybe consider it a bug...?

btw: Awesome library, thank you so much! :-)
Cheers

**Comment by mikepenz** [comment]
@pokerazor oh you might be right. This attribute is only there for the `AppCompat` themes and all themes which extend the `AppCompat` theme. 

It's no bug, but I should note that the theme has to be an `AppCompat` theme, or a child from it, like the `MaterialDrawerTheme.*`

**Comment by or-dvir** [comment]
@christianguevara i am using "compileSdkVersion 23"

@mikepenz changing to support libraries 23.2.1 does not fix the problem

**changing the theme worked!!!**
now i just have to find one that fits my app AND inherits from appcompat.

thank you!

**Comment by mikepenz** [comment]
@or-dvir just for for curiosity, which theme did you use before?

**Comment by or-dvir** [comment]
i was using @android:style/Theme.Holo.Light.NoActionBar

**Comment by mikepenz** [comment]
@or-dvir oh ok. Yeah it is not recommended to use this theme :D. The AppCompat theme will give your app a far better look across different API versions

**Comment by lumyus** [comment]
I am have a very similar problem. However I only face it on certain devices. And it crashes too when using a different than main flavor. Any idea whats going on? Thanks!


`FATAL EXCEPTION: main
                                                                         Process: com.flyingmanta.doubledog, PID: 1847
                                                                         android.content.res.Resources$NotFoundException: String resource ID #0x1
                                                                             at android.content.res.Resources.getText(Resources.java:1468)
                                                                             at android.widget.TextView.setText(TextView.java:5051)
                                                                             at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:59)
                                                                             at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:86)
                                                                             at com.mikepenz.materialdrawer.model.MiniDrawerItem.bindView(MiniDrawerItem.java:153)
                                                                             at com.mikepenz.materialdrawer.model.MiniDrawerItem.bindView(MiniDrawerItem.java:24)
                                                                             at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:2006)
                                                                             at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:655)
                                                                             at com.mikepenz.fastadapter.AbstractAdapter.onBindViewHolder(AbstractAdapter.java:151)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6509)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5452)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5718)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5557)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5553)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                             at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                             at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                             at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1196)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                             at android.view.View.layout(View.java:17939)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5814)`

Furthermore I am using the following code:

```
Drawable drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_person);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem profileItem = new PrimaryDrawerItem()
                .withName("Profile")
                .withIcon(drawable);

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_settings);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem settingsItem = new PrimaryDrawerItem()
                .withName("Settings")
                .withIcon(drawable);

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_notifications);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem notificationItem = new PrimaryDrawerItem()
                .withName("Notifications")
                .withIcon(drawable);

        if(user.getPendingFollowerCount() > 0){
            notificationItem.withBadge(user.getPendingFollowerCount())
                    .withBadgeStyle(new BadgeStyle(ResourcesCompat.getColor(getResources(), R.color.accent, null),
                            ResourcesCompat.getColor(getResources(), R.color.accent, null)));
        }

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_share);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem shareItem = new PrimaryDrawerItem()
                .withName("Share")
                .withIcon(drawable);

        Log.d("Menu", "Icons set up");

    result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withSelectedItem(-1)
                .withHasStableIds(true)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withDrawerWidthDp(72)
                .withGenerateMiniDrawer(true)
                .addDrawerItems(
                        settingsItem.withIdentifier(0),
                        profileItem.withIdentifier(1),
                        notificationItem.withIdentifier(2),
                        shareItem.withIdentifier(3)
                        ) // add the items we want to use with our Drawer
            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                    Intent intent;
                    switch(position) {
                        case 0:
                            intent = new Intent(MainActivity.this, SettingsActivity.class);
                            startActivity(intent);
                            break;
                        case 1:
                            intent = new Intent(MainActivity.this, ProfileActivity.class);
                            intent.putExtra( "user", ((DoubleDogApplication)getApplication()).getLoggedInUser());
                            startActivity(intent);
                            break;
                        case 2:
                            intent = new Intent(MainActivity.this, NotificationActivity.class);
                            startActivity(intent);
                            break;
                        case 3:
                            shareWithFriends();
                            break;
                        default:
                    }

                    return false;
                }
            })
            .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                .build();


        Log.d("Menu", "Menu built");

    //get the CrossfadeDrawerLayout which will be used as alternative DrawerLayout for the Drawer
    //the CrossfadeDrawerLayout library can be found here: https://github.com/mikepenz/CrossfadeDrawerLayout
    crossfadeDrawerLayout = (CrossfadeDrawerLayout) result.getDrawerLayout();

    //define maxDrawerWidth
        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(this));
    //add second view (which is the miniDrawer)
    final MiniDrawer miniResult = result.getMiniDrawer();
    //build the view for the MiniDrawer
    View view = miniResult.build(this);
    //set the background of the MiniDrawer as this would be transparent
        view.setBackgroundColor(ContextCompat.getColor(this, R.color.white));
        //we do not have the MiniDrawer view during CrossfadeDrawerLayout creation so we will add it here
        crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);

    //define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new ICrossfader() {
        @Override
        public void crossfade() {
            boolean isFaded = isCrossfaded();
            crossfadeDrawerLayout.crossfade(400);

            //only close the drawer if we were already faded and want to close it now
            if (isFaded) {
                result.getDrawerLayout().closeDrawer(GravityCompat.START);
            }
        }

        @Override
        public boolean isCrossfaded() {
            return crossfadeDrawerLayout.isCrossfaded();
        }
    });
        Log.d("Menu", "MiniMenu built");
        isMenuCreated = true;

```
