### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by smeegoan** [mikepenz/MaterialDrawer#1112]
Hi,

If I use the following combination of libraries (the problem only began after adding the aboutlibraries):

```
    compile 'com.mikepenz:iconics-core:2.5.10@aar'
    compile 'com.mikepenz:google-material-typeface:2.2.0.1.original@aar'
    compile 'com.mikepenz:community-material-typeface:1.3.41.1@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.5.0.1@aar'
    compile('com.mikepenz:materialdrawer:5.1.3@aar') {
        transitive = true
    }
    compile('com.mikepenz:aboutlibraries:5.6.0@aar') {
        transitive = true
    }

```

I get the following exception:

```
FATAL EXCEPTION: main
Process: com.foo.bar, PID: 29733
java.lang.NoSuchMethodError: No interface method set(Ljava/util/List;)V in class Lcom/mikepenz/fastadapter/IItemAdapter; or its super classes (declaration of 'com.mikepenz.fastadapter.IItemAdapter' appears in /data/app/com.foo.bar-2/base.apk)
	at com.mikepenz.materialdrawer.DrawerBuilder.withDrawerItems(DrawerBuilder.java:929)
	at com.foo.bar.ui.activity.MainActivity.setUpNavigationDrawer(MainActivity.java:313)
	at com.foo.bar.ui.activity.MainActivity.onCreate(MainActivity.java:142)
	at android.app.Activity.performCreate(Activity.java:5933)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Is there a known compatibility issue between these libraries?

**Comment by mikepenz** [comment]
@smeegoan please use the latest version of the `AboutLibraries`, and the `MaterialDrawer`. I updated the `interface` of the `IItemAdapter` in version v1.2.5 of the `FastAdapter`. 

Both the `AboutLibraries` and the `MaterialDrawer` use the `FastAdapter` as of the `interface` update, both need to be the latest version. 

MaterialDrawer at least v5.1.4
AboutLibraries at least v5.5.9
