### ISSUE TITLE
The app closed

### ISSUE THREAD

**Issue by Gheoo** [mikepenz/MaterialDrawer#1135]
the logcat is this:
```
java.lang.NoClassDefFoundError: com.mikepenz.materialdrawer.holder.ImageHolder
	at com.mikepenz.materialdrawer.model.ProfileDrawerItem.withIcon(ProfileDrawerItem.java:52)
```

How can i fix this?

**Comment by mikepenz** [comment]
@Gheoo the logcat does not show enough information. 

Where does it close? The debug application? Do you use proguard?

**Comment by Gheoo** [comment]
The application closed in some devices and i don't use proguard, am i post other logcat?

**Comment by mikepenz** [comment]
@Gheoo I need a full error log what happens.

**Comment by Gheoo** [comment]
```
java.lang.NoClassDefFoundError: com.mikepenz.materialdrawer.holder.ImageHolder
	at com.mikepenz.materialdrawer.model.ProfileDrawerItem.withIcon(ProfileDrawerItem.java:52)
	at com.gheoo.direttagol.activity.MainActivity.setupNavigationDrawer(MainActivity.java:101)
	at com.gheoo.direttagol.activity.MainActivity.onCreate(MainActivity.java:65)
	at android.app.Activity.performCreate(Activity.java:5343)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2340)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2438)
	at android.app.ActivityThread.access$800(ActivityThread.java:160)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5368)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mikepenz** [comment]
@Gheoo the above can only happen when there is a bad proguard setup. You tested it on your device and you can't reproduce? So the class is definitely there.

**Comment by Gheoo** [comment]
I tested it in my device, and i don't have any problem, only some users are advising me

**Comment by Gheoo** [comment]
How can i check if is a bad proguard setup?

**Comment by mikepenz** [comment]
@Gheoo weird. Because if it is a general issue it should always fail. 

Any pattern which devices fail? What do they do? Any click path they do until it crashes? 

I am sure it is no problem of the library, as many people use it without this issue, and if the class would be missing in the source it won't build with gradle and AndroidStudio
