### ISSUE TITLE
java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY

### ISSUE THREAD

**Issue by orcchg** [mikepenz/MaterialDrawer#1167]
Similar to issue #518 

```
java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
                                                                     at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1036)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5364)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
                                                                     at android.view.View.measure(View.java:17478)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2267)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1371)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1595)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6602)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:575)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5476)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

I'm using support library 23.2.1 and Material Drawer 5.1.6
This crash occurs when I try to open an Activity with MD and 'dialog'-theme (such as "@style/Base.Theme.AppCompat.Light.Dialog"). 
Samsung Galaxy Note 10.1 (Tablet large screen).
When I use my own DrawerLayout, I have the same issue, so I've fixed it extending DrawerLayout and overriding onMeasure() this way:

```java
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {

        widthMeasureSpec = MeasureSpec.makeMeasureSpec(
                MeasureSpec.getSize(widthMeasureSpec), MeasureSpec.EXACTLY);

        heightMeasureSpec = MeasureSpec.makeMeasureSpec(
                MeasureSpec.getSize(heightMeasureSpec), MeasureSpec.EXACTLY);

        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

    }
```

How can I fix the issue within MD ? Thank You.

**Comment by mikepenz** [comment]
@orcchg you can also provide your own `DrawerLayout` to the `MaterialDrawer` and do the same. 

You can provide it here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L315

The default layout is the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer.xml

Alter it to use your `DrawerLayout`

**Comment by orcchg** [comment]
@mikepenz Thank You! MD has quite exciting flexibility. It's customization abilities are breath-taking!
This fixed the issue.
