### ISSUE TITLE
OutOfMemoryException when using big pictures inside the AccountHeader

### ISSUE THREAD

**Issue by FabianTerhorst** [mikepenz/MaterialDrawer#1181]
Log from Galaxy Grand Neo (baffinlite) Android 4.2 :
```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:817)
	at android.content.res.Resources.loadDrawable(Resources.java:2854)
	at android.content.res.Resources.getDrawable(Resources.java:1521)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:177)
	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:170)
	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:53)
	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:74)
	at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:704)
	at ..........HomeActivity.onCreate(HomeActivity.java:220)
	at android.app.Activity.performCreate(Activity.java:5326)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
	at android.app.ActivityThread.access$700(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```
Workaround is to set a smaller drawable when the OOM occupied.
```java
try {

mHeader = new AccountHeaderBuilder()
...
.withHeaderBackground(R.drawable.bigPicture)
..
.build()
} catch (OutOfMemoryError outOfMemoryError) {
...
.withHeaderBackground(new ColorDrawable(ContextCompat.getColor(this, R.color.md_indigo_500)))
...
}
```

**Comment by mikepenz** [comment]
I might have a deeper look probably I can catch this inside the drawer so it at least prevents the app from crashing if devs provide to large images
