### ISSUE TITLE
Exception on old Android 2.3 after library updating

### ISSUE THREAD

**Issue by egisxxx** [mikepenz/MaterialDrawer#119]
I update this lib to 2.5.1 and anything change in my code, but on android 2.3 (10)  i get exception:
android.view.View.setBackground
    java.lang.NoSuchMethodError: android.view.View.setBackground
            at com.mikepenz.materialdrawer.accountswitcher.AccountHeader.buildProfiles(AccountHeader.java:900)
            at com.mikepenz.materialdrawer.accountswitcher.AccountHeader.build(AccountHeader.java:606)
I think, it is bug in newest version.

**Comment by mikepenz** [comment]
@egisxxx you are right. missed that i used a method there which is not compatible. will be fixed with v2.5.2

**Comment by egisxxx** [comment]
yes, on 2.5.2 everything fixed. thanks. great library.
