### ISSUE TITLE
Drawer with header drawable id

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#124]
I have and erro with this code

 result = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(R.drawable.header2)
........

android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/header2.jpg from xml type layout resource ID #0x7f020061
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2696)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2651)
       at android.content.res.Resources.getLayout(Resources.java:1082)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
       at com.mikepenz.materialdrawer.Drawer.withHeader(Drawer.java:423)

I need this resources folderdrawable-xxhdpi-v4???

**Comment by mikepenz** [comment]
@Spiderbezno the .withHeader does not take a drawable. It only takes a layout which can contain a drawable. 

As alternative you can create an empty AccountHeader with only an image without any profiles. This will also do the job.
