### ISSUE TITLE
Failed resolution of ...ScrimInsetsRelativeLayout

### ISSUE THREAD

**Issue by DoktorBog** [mikepenz/MaterialDrawer#1267]
Hello I get an error and can not understand why?

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/materialize/view/ScrimInsetsRelativeLayout;
                                                                    at com.mikepenz.crossfadedrawerlayout.view.CrossfadeDrawerLayout.wrapSliderContent(CrossfadeDrawerLayout.java:128)
                                                                    at com.mikepenz.crossfadedrawerlayout.view.CrossfadeDrawerLayout.addView(CrossfadeDrawerLayout.java:107)
                                                                    at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1276)
                                                                    at com.tripod.app.ui.MainActivity.createDrawer(MainActivity.java:383)
                                                                    at com.tripod.app.ui.MainActivity.onCreate(MainActivity.java:168)
                                                                    at android.app.Activity.performCreate(Activity.java:6251)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by mikepenz** [comment]
Please follow the instructions ins the README:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency
