### ISSUE TITLE
NPE in BezelImageView with VectorDrawable when Xposed is installed

### ISSUE THREAD

**Issue by grote** [mikepenz/MaterialDrawer#1283]
I know this is probably a crazy issue, but it was already reported two times by users of my app. I don't know who is to blame, but I report it here, so you know and maybe you know better where to report this.

Apparently, this stack trace comes right after the user tries to open the navigation drawer.

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at android.util.PathParser$PathDataNode.addCommand(PathParser.java:335)
    at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
    at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
    at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
    at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
    at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:927)
    at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
    at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
    at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
    at android.widget.ImageView.onDraw(ImageView.java:1227)
    at com.mikepenz.materialdrawer.view.BezelImageView.onDraw(BezelImageView.java:215)
    at android.view.View.draw(View.java:15199)
    at android.view.View.updateDisplayListIfDirty(View.java:14133)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.updateDisplayListIfDirty(View.java:14128)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.updateDisplayListIfDirty(View.java:14128)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.draw(View.java:15202)
    at android.widget.FrameLayout.draw(FrameLayout.java:592)
    at android.view.View.updateDisplayListIfDirty(View.java:14133)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.updateDisplayListIfDirty(View.java:14128)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.draw(View.java:15202)
    at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
    at android.view.View.updateDisplayListIfDirty(View.java:14133)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.draw(View.java:15202)
    at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
    at android.view.View.updateDisplayListIfDirty(View.java:14133)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.View.draw(View.java:14923)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3410)
    at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
    at android.view.View.draw(View.java:15202)
    at android.view.View.updateDisplayListIfDirty(View.java:14133)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3394)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3373)
    at android.view.View.updateDisplayListIfDirty(View.java:14093)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3394)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3373)
    at android.view.View.updateDisplayListIfDirty(View.java:14093)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3394)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3373)
    at android.view.View.updateDisplayListIfDirty(View.java:14093)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3394)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3373)
    at android.view.View.updateDisplayListIfDirty(View.java:14093)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3394)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3373)
    at android.view.View.updateDisplayListIfDirty(View.java:14093)
    at android.view.View.getDisplayList(View.java:14156)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:278)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:284)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2641)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2464)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2062)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1106)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6018)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
    at android.view.Choreographer.doCallbacks(Choreographer.java:596)
    at android.view.Choreographer.doFrame(Choreographer.java:557)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:155)
    at android.app.ActivityThread.main(ActivityThread.java:5696)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

Note that I am using a VectorDrawable in the account header. This has only been reported by users that had Xposed installed. This applies to the latest 5.2.6 version.

**Comment by mikepenz** [comment]
@grote the exception is thrown from the underlying architecture and the **mikepenz** package name just shows up because it passes the issue through. I'm afraid I can't do anything against this. It might need to be opened on the Xposed thread or so. Seems they break the `VectorDrawable` in a really weird way.

Sorry that I can't help here
