### ISSUE TITLE
java.lang.RuntimeException: Binary XML file line #74: You must supply a layout_width attribute.

### ISSUE THREAD

**Issue by mwshubham** [mikepenz/MaterialDrawer#1326]
`W/System.err: java.lang.RuntimeException: Binary XML file line #74: You must supply a layout_width attribute.
W/System.err:     at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:619)
W/System.err:     at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6845)
W/System.err:     at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7014)
W/System.err:     at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1863)
W/System.err:     at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1775)
W/System.err:     at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:61)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:820)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
W/System.err:     at com.mikepenz.materialdrawer.model.AbstractDrawerItem.getViewHolder(AbstractDrawerItem.java:290)
W/System.err:     at com.mikepenz.fastadapter.utils.RecyclerViewCacheUtil.apply(RecyclerViewCacheUtil.java:45)
W/System.err:     at com.webkul.mobikul.ui.activity.MainActivity.addingCustomChangesToRemoveEmailListFromDrawer(MainActivity.java:432)`

I am getting this error. I suppose this is related to library.  Please let me know what is the cause of this.
or I think i have messed something.

i am using fpllowing depedency
` compile('com.mikepenz:materialdrawer:5.2.7@aar') {
        transitive = true
    }`

**Comment by mwshubham** [comment]
sorry i have done this mistake 


 <dimen name="activity_horizontal_margin">@dimen/activity_horizontal_margin</dimen>
    <dimen name="activity_vertical_margin">@dimen/activity_horizontal_margin</dimen>

seems like android studio don't fix transitive errors
