### ISSUE TITLE
How can i add an AccountHeader at runtime ?

### ISSUE THREAD

**Issue by createS0ftware** [mikepenz/MaterialDrawer#135]
Hi 

I create the Drawer , then the user authenticates and i need to either add the AccountHeader then or change an existing AccountHeader.

I have tried rebuilding but i get the error saying that i can't reuse a builder.

What is the correct method ?

Thanks

**Comment by createS0ftware** [comment]
Ok i figured it out .

Very good improvements on v2.5.5 . Keep up the good work

**Comment by mikepenz** [comment]
@createS0ftware thanks ;)

What was your issue?

**Comment by AngleV** [comment]
same thing here @mikepenz 

I create the drawer with AccountHeader like this
```
   drawer = new DrawerBuilder()
                .withActivity(this)
                .withSavedInstance(savedInstanceState)
                .withAccountHeader(headerResult)
```

```
 headerResult = new AccountHeaderBuilder()
                .withTextColor(Color.BLACK)
                .withActivity(this)
                .withCompactStyle(false)
                .withCurrentProfileHiddenInList(false)
                .withProfileImagesClickable(false)
                .withResetDrawerOnProfileListClick(false)
                .withAlternativeProfileHeaderSwitching(true)
                .withSelectionListEnabledForSingleProfile(false)
                .withHeaderBackground(R.drawable.header_2)
                .withSelectionListEnabledForSingleProfile(false)
                .build();


        return headerResult;
```

But when i am trying to add a profile to headerResult i get a NullPointerException

```
 profile = new ProfileDrawerItem()
                    .withName(name)
                    .withEmail(email)
                    .withIcon(R.drawable.default_avatar);

 headerResult.addProfile(profile, 0);    <----- NullPointerException to headerResult
```

Basicaly what i am trying to do is create an empty AccounHeader. As soon as user signs in from another activity i want to add the profile to the AccountHeader to my main Activity where drawer lives.
i would appreciate if you could drop me a snippet Mike !

**Comment by mikepenz** [comment]
@AngleV can you please also provide the exception

**Comment by AngleV** [comment]
@mikepenz 

Yes sure. Here you are


```
04-20 23:14:54.431 E/ViewRootImpl: sendUserActionEvent() mView == null
04-20 23:14:56.661 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.bs.beachsnapp, PID: 29351
                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.AccountHeader.addProfile(com.mikepenz.materialdrawer.model.interfaces.IProfile, int)' on a null object reference
                                         at com.bs.beachsnapp.ui.activities.MainActivity.setUserProfile(MainActivity.java:105)
                                         at com.bs.beachsnapp.ui.activities.SignInActivity.setupHeader(SignInActivity.java:369)
                                         at com.bs.beachsnapp.ui.activities.SignInActivity$4.success(SignInActivity.java:246)
                                         at com.bs.beachsnapp.ui.activities.SignInActivity$4.success(SignInActivity.java:242)
                                         at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:158)
                                         at android.app.ActivityThread.main(ActivityThread.java:7224)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by mikepenz** [comment]
@AngleV is your `headerResult` null?

**Comment by AngleV** [comment]
@mikepenz 
According to Android studio Debugger Yes its null !!!

**Comment by mikepenz** [comment]
:D @AngleV I think you just miss to set it to your headerResult variable or so :D

**Comment by AngleV** [comment]
Got any advise how to access AccountHeader from another activity and add a new profile ?
