### ISSUE TITLE
Espresso Tests fail on including MaterialDrawer 2.5.5 (works on 2.0.0)

### ISSUE THREAD

**Issue by kaushald** [mikepenz/MaterialDrawer#142]
Added a blank espresso test in com.mikepenz.unsplash
App was initialized and test passed successfully. (with Material Drawer 2.0.0)

Changed the drawer to 2.5.5 in the gradle file.
The same espresso test fails with the following error -
(Please let me know if you need additional details)

```
Test running started
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.support.v4.widget.DrawerLayout.isDrawerView(DrawerLayout.java:1100)
at android.support.v4.widget.DrawerLayout.isDrawerOpen(DrawerLayout.java:1350)
at android.support.v7.app.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:251)
at com.mikepenz.materialdrawer.Drawer.build(Drawer.java:896)
at com.mikepenz.unsplash.activities.MainActivity.onCreate(MainActivity.java:62)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:346)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikepenz.unsplash.debug/com.mikepenz.unsplash.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.support.v4.widget.DrawerLayout.isDrawerView(DrawerLayout.java:1100)
at android.support.v4.widget.DrawerLayout.isDrawerOpen(DrawerLayout.java:1350)
at android.support.v7.app.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:251)
at com.mikepenz.materialdrawer.Drawer.build(Drawer.java:896)
at com.mikepenz.unsplash.activities.MainActivity.onCreate(MainActivity.java:62)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:346)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
... 10 more

Test running failed: Instrumentation run failed due to 'java.lang.NullPointerException'
```

#### Add the following dependencies
```gradle
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.0'
    androidTestCompile 'com.android.support.test:testing-support-lib:0.1'
    // http://stackoverflow.com/questions/28999124/resolved-versions-for-app-22-0-0-and-test-app-21-0-3-differ
    androidTestCompile ('com.android.support.test.espresso:espresso-contrib:2.0') {
        exclude module: 'support-annotations'
    }
```
#### Add packagingOptions to android
```gradle
    packagingOptions {
        exclude 'LICENSE.txt'
    }
```
#### Add the following test to the project (androidTest needs to be created)
```java
package com.mikepenz.unsplash;

/**
 * Created by kaushaldalvi on 3/22/15.
 */

import android.test.ActivityInstrumentationTestCase2;
import com.mikepenz.unsplash.activities.MainActivity;


/**
 * https://code.google.com/p/android-test-kit/wiki/EspressoStartGuide
 * http://developer.android.com/reference/android/test/ActivityInstrumentationTestCase2.html
 * <a href="http://d.android.com/tools/testing/testing_android.html">Testing Fundamentals</a>
 * <p/>
 */
public class EspressoTest extends ActivityInstrumentationTestCase2<MainActivity> {
    public EspressoTest() {
        super(MainActivity.class);
    }

    @Override
    public void setUp() throws Exception {
        super.setUp();
        getActivity(); 
    }

    public void testEspressoFirstTest() {
        //Blank Test
    }
}
```
#### Add an android test configuration and run the test

**Comment by mikepenz** [comment]
@kaushald it seems that there's still a misconfiguration with the new library. Can't tell what should be wrong. updated wall:splash internally and it's working. 

Have you tried running it without the test? Got it working already?

**Comment by kaushald** [comment]
@mikepenz - yes, wall:splash works if MD is updated to 2.5.5
What doesnt work is an Espresso test that just launches the application.

The Espresso test works with wall:splash using 2.0.0

**Comment by mikepenz** [comment]
@kaushald i assume that it has some issues with the styles or something like this. if you can debug into it and let me know where it fails it will help :)

**Comment by kaushald** [comment]
I tried it out on v2.0.7 and v2.5.0, it works on 2.0.7 and fails on 2.5.0 so I am guessing it has to do something with the ScrimInsetsFrameLayout. Dont really have much more debugging infoat the moment. Will keep adding more as I find some. This is a great library, I want to be able to use it while being able to automate the testing using Espresso.

**Comment by mikepenz** [comment]
Yeah. As i said perhaps we can hunt it down with a more detailed error description

**Comment by kaushald** [comment]
Hi Mike, not sure what you mean by additional debug info.
I have created a fork of the project and added tests to it so that you can quickly run and see for yourself.

You can find it here - https://github.com/kaushald/MaterialDrawer

Just add a run config like this and run it - 
![Image of run config](http://i.imgur.com/vp6JHkE.png)

This is the error that you get - 
```
Testing started at 4:14 PM ...
Installing com.mikepenz.materialdrawer.app
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.mikepenz.materialdrawer.app"
pkg: /data/local/tmp/com.mikepenz.materialdrawer.app
Success


Uploading file
	local path: /Users/kaushald/Documents/projects/git/android/MaterialDrawer/app/build/outputs/apk/app-debug-androidTest-unaligned.apk
	remote path: /data/local/tmp/com.mikepenz.materialdrawer.app.test
Installing com.mikepenz.materialdrawer.app.test
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.mikepenz.materialdrawer.app.test"
pkg: /data/local/tmp/com.mikepenz.materialdrawer.app.test
Success


Running tests
Test running started
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.support.v4.widget.DrawerLayout.isDrawerView(DrawerLayout.java:1100)
at android.support.v4.widget.DrawerLayout.isDrawerOpen(DrawerLayout.java:1350)
at android.support.v7.app.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:251)
at com.mikepenz.materialdrawer.Drawer.build(Drawer.java:1003)
at com.mikepenz.materialdrawer.app.SimpleHeaderDrawerActivity.onCreate(SimpleHeaderDrawerActivity.java:94)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:346)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikepenz.materialdrawer.app/com.mikepenz.materialdrawer.app.SimpleHeaderDrawerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at android.support.v4.widget.DrawerLayout.isDrawerView(DrawerLayout.java:1100)
at android.support.v4.widget.DrawerLayout.isDrawerOpen(DrawerLayout.java:1350)
at android.support.v7.app.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:251)
at com.mikepenz.materialdrawer.Drawer.build(Drawer.java:1003)
at com.mikepenz.materialdrawer.app.SimpleHeaderDrawerActivity.onCreate(SimpleHeaderDrawerActivity.java:94)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:346)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
... 10 more

Test running failed: Instrumentation run failed due to 'java.lang.NullPointerException'
```

**Comment by mikepenz** [comment]
@kaushald doesn't seem that i'm not able to get the same exception as you. But reading the log output. Can you please try to remove the .withToolbar() of your drawer for the test. The above exception fails with the .syncState method of the ActionBarDrawertoggle

**Comment by kaushald** [comment]
Hi @mikepenz , removed the .withToolbar() of the drawer to test.
Tests pass successfully now. However, as expected there is no toolbar :)

![without toolbar](http://i.imgur.com/8X8YSXZ.png)

Also pushed the  change to https://github.com/kaushald/MaterialDrawer (and a fix, it was waiting 5000 seconds to launch the test instead of 5 seconds, changed it to 2 seconds now)

```
Testing started at 8:21 PM ...
No apk changes detected. Skipping file upload, force stopping package instead.
DEVICE SHELL COMMAND: am force-stop com.mikepenz.materialdrawer.app
Uploading file
	local path: /Users/kaushaldalvi/Documents/projects/android/git/MaterialDrawer/app/build/outputs/apk/app-debug-androidTest-unaligned.apk
	remote path: /data/local/tmp/com.mikepenz.materialdrawer.app.test
Installing com.mikepenz.materialdrawer.app.test
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.mikepenz.materialdrawer.app.test"
pkg: /data/local/tmp/com.mikepenz.materialdrawer.app.test
Success


Running tests
Test running startedFinish
```

**Comment by wKovacs64** [comment]
FWIW, I'm running into the same issue (and confirming the removal of `.withToolbar()` resolves it).

**Comment by mikepenz** [comment]
@kaushald @wKovacs64 i really assume that it has to be a combination of the new support library and the not yet really supporting espresso for it. Or something like that. 

@wKovacs64 you found the problem? Sounds bad :/

**Comment by kaushald** [comment]
@wKovacs64 suggested - Downgrade library SDK to 21 and support libs to 21.0.3. That did it, test works with toolbar as well on making these changes.

**Comment by wKovacs64** [comment]
I think I've found a better fix, though. Testing now.

**Comment by kaushald** [comment]
@wKovacs64's solution here works - https://github.com/kaushald/MaterialDrawer/pull/2

**Comment by wKovacs64** [comment]
This seems to be an issue with the Android support library v4. espresso-contrib:2.0 depends on support-v4 version 21.0.3. MaterialDrawer 2.0.7 (the last released version @kaushald reported as working with Espresso) also depends on support-v4 21.0.3, while subsequent releases (2.5.0+) were upgraded to version 22.0.0 (targeting SDK 22). Having both versions in the dependency tree seems to cause the problem. Reverting the target SDK and support-v4 version in the MaterialDrawer library resolves the issue, but the better solution is probably to exclude the support-v4 module from the espresso-contrib:2.0 dependency in the app as such:
```
androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.0') {
    exclude module: 'support-annotations'
    exclude module: 'support-v4'
}
```
No changes to MaterialDrawer required. Thoughts, @mikepenz ?

**Comment by kaushald** [comment]
@wKovacs64 wow, great job figuring that out !

**Comment by wKovacs64** [comment]
@kaushald Thanks, glad I could help. Here's some bonus information:

I started writing some more elaborate tests and ran into more errors. You may need to exclude recyclerview-v7 as well, if you use any other libraries that depend on recyclerview-v7:22.0.0 (such as @mikepenz 's nifty [AboutLibraries](https://github.com/mikepenz/AboutLibraries)). I think that should be the last one we need to worry about, looking at the dependency tree.
```
androidTestCompile ('com.android.support.test.espresso:espresso-contrib:2.0') {
    exclude module: 'support-annotations'
    exclude module: 'support-v4'
    exclude module: 'recyclerview-v7'
}
```

**Comment by kaushald** [comment]
@wKovacs64 - appreciate it, thanks
@mikepenz - again great work and thank you for this library

**Comment by mikepenz** [comment]
@wKovacs64 thank you so much for figuring this out.

@kaushald thanks

**Comment by mikepenz** [comment]
I'Ve added this to the FAQ. thanks again
