### ISSUE TITLE
UnsupportedOperationException at BezelImageView 

### ISSUE THREAD

**Issue by davidemanfroni** [mikepenz/MaterialDrawer#1437]
Thanks for your work , really helpful and easy to use .
I found an error on my project that I can not fix from this morning.

this is my logcat

```
08-02 17:09:51.783 11976-11976/it.justselfie.app E/AndroidRuntime: FATAL EXCEPTION: main
   Process: it.justselfie.app, PID: 11976
   java.lang.RuntimeException: Unable to start activity ComponentInfo{it.justselfie.app/it.justselfie.app.Activity.CouponListActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
    Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:595)
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:755)
       at it.justselfie.app.Activity.CouponListActivity.setupNavigationDrawer2(CouponListActivity.java:115)
       at it.justselfie.app.Activity.CouponListActivity.onCreate(CouponListActivity.java:79)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
       at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:158) 
       at android.app.ActivityThread.main(ActivityThread.java:7224) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
       at android.view.LayoutInflater.createView(LayoutInflater.java:657)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:595) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:755) 
       at it.justselfie.app.Activity.CouponListActivity.setupNavigationDrawer2(CouponListActivity.java:115) 
       at it.justselfie.app.Activity.CouponListActivity.onCreate(CouponListActivity.java:79) 
       at android.app.Activity.performCreate(Activity.java:6876) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
       at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:158) 
       at android.app.ActivityThread.main(ActivityThread.java:7224) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Native Method)
       at android.view.LayoutInflater.createView(LayoutInflater.java:631)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:595) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:755) 
       at it.justselfie.app.Activity.CouponListActivity.setupNavigationDrawer2(CouponListActivity.java:115) 
       at it.justselfie.app.Activity.CouponListActivity.onCreate(CouponListActivity.java:79) 
       at android.app.Activity.performCreate(Activity.java:6876) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
       at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:158) 
       at android.app.ActivityThread.main(ActivityThread.java:7224) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 12: TypedValue{t=0x3/d=0x77 "res/drawable/material_drawer_circle_mask.xml" a=3 r=0x7f0200b0}
       at android.content.res.TypedArray.getColor(TypedArray.java:449)
       at com.mikepenz.materialdrawer.view.BezelImageView.<init>(BezelImageView.java:104)
       at com.mikepenz.materialdrawer.view.BezelImageView.<init>(BezelImageView.java:88)
       at java.lang.reflect.Constructor.newInstance(Native Method) 
       at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:595) 
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:755) 
       at it.justselfie.app.Activity.CouponListActivity.setupNavigationDrawer2(CouponListActivity.java:115) 
       at it.justselfie.app.Activity.CouponListActivity.onCreate(CouponListActivity.java:79) 
       at android.app.Activity.performCreate(Activity.java:6876) 
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
       at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:158) 
       at android.app.ActivityThread.main(ActivityThread.java:7224) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)   
```

The strange thing is that if I try to import it into a new blank project , works .

Maybe it conflicts with other libraries ?

these are my dipendecies:

```gradle
 compile 'com.google.code.gson:gson:2.4'
 compile 'com.facebook.android:facebook-android-sdk:4.11.0'
compile 'com.jakewharton:butterknife:6.1.0'
  compile 'com.aurelhubert:ahbottomnavigation:1.2.3'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.commit451:PhotoView:1.2.4'
    compile 'jp.wasabeef:blurry:2.0.2'
    compile files('libs/universal-image-loader-1.9.4.jar')
    compile 'com.github.nisrulz:qreader:1.0.5'
```

and local projects by:
https://github.com/navasmdc/MaterialDesignLibrary
https://github.com/ongakuer/CircleIndicator

Thanks!

**Comment by mikepenz** [comment]
Perhaps it really conflicts with one of the dependency. 

The root cause is the following:
```
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 12: TypedValue{t=0x3/d=0x77 "res/drawable/material_drawer_circle_mask.xml" a=3 r=0x7f0200b0}
```

**Comment by mikepenz** [comment]
have you cleaned everything? this error happend before too? which build tools are you using? which target version?

**Comment by davidemanfroni** [comment]
I 've cleaned and rebuilt the project .

This error occurred immediately when I tried to use the library for the first time

buildToolsVersion 24.0.0
targetSdkVersion 24

I tried also the support library  24.1.1 and 24.0.0

**Comment by mikepenz** [comment]
@davidemanfroni could you please provide a small sample app showcasing this issue? I can't really reproduce this. And I am quite sure it has to be related to your project setup

**Comment by mikepenz** [comment]
Close until further details are provided.
