### ISSUE TITLE
Update Account Header - null object reference

### ISSUE THREAD

**Issue by FasdAR** [mikepenz/MaterialDrawer#1604]
When I turn on the main activity the update is successful, but when I click on one of the points to the example of the menu that gives this error

Error

```
10-31 22:29:39.387 5443-5443/ru.landmarkstd.influence.influence E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: ru.landmarkstd.influence.influence, PID: 5443
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.landmarkstd.influence.influence/ru.landmarkstd.influence.influence.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.AccountHeader.updateProfile(com.mikepenz.materialdrawer.model.interfaces.IProfile)' on a null object reference
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.AccountHeader.updateProfile(com.mikepenz.materialdrawer.model.interfaces.IProfile)' on a null object reference
                                                                                      at ru.landmarkstd.influence.influence.FunctionalClass.NavigationDrawer$1.onBitmapLoaded(NavigationDrawer.java:86)
                                                                                      at com.squareup.picasso.RequestCreator.into(RequestCreator.java:518)
                                                                                      at ru.landmarkstd.influence.influence.FunctionalClass.NavigationDrawer.<init>(NavigationDrawer.java:73)
                                                                                      at ru.landmarkstd.influence.influence.MainActivity.onCreate(MainActivity.java:58)
                                                                                      at android.app.Activity.performCreate(Activity.java:6876)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:158) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

Code MainActivity

```
public class MainActivity extends AppCompatActivity
{
    Toolbar toolbar;
    Activity activity;
    Resources resources;
    Context context;

    FirebaseDatabase database;
    FirebaseRecyclerAdapter<VideoClass, MainActivity.VideoViewHolder> mFirebaseAdapter;

    RecyclerView recyclerViewVideo;
    LinearLayoutManager layoutManagerChat;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
         *****/
        new NavigationDrawer(getApplicationContext(), activity, resources,toolbar);
        ***/
    }
}
```

Code NavigationDrawer

```
`public class NavigationDrawer
{
    Context context;
    Activity activity;
    Resources resources;
    Toolbar toolbar;
    Bitmap bitmap = null;
    AccountHeader headerResult = null;

    FirebaseUser userFU;
    FirebaseDatabase database;

    SharedPreferences Settings;

    static
    {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }

    public NavigationDrawer(Context context, final Activity activity, Resources resources, Toolbar toolbar)
    {
        this.context = context;
        this.activity = activity;
        this.resources = resources;
        this.toolbar = toolbar;

        userFU = FirebaseAuth.getInstance().getCurrentUser();
        database = FirebaseDatabase.getInstance();

        Settings = context.getSharedPreferences(resources.getString(R.string.SettingsName), Context.MODE_PRIVATE);

        final boolean isPlayer = Settings.getBoolean(resources.getString(R.string.SettingsIsPlayer), false);

        Picasso.with(context).load(userFU.getPhotoUrl()).into(new Target()
        {
            IProfile profile = new ProfileDrawerItem().withName(userFU.getDisplayName()).withEmail(userFU.getEmail())
                    .withIcon(R.drawable.ava_load_sync).withIdentifier(1);

            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from)
            {
                Log.d("myLog", "LoadBitmap");

                if (profile != null)
                {
                    profile.withIcon(bitmap);
                    headerResult.updateProfile(profile);
                }
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable)
            {
                Log.d("myLog", "FailedLoadBitmap");

                profile.withIcon(R.drawable.ava_load_failed);

                if (profile != null)
                {
                    profile.withIcon(bitmap);
                    headerResult.updateProfile(profile);
                }
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable)
            {
                Log.d("myLog", "PrepareLoadBitmap");
                if (isPlayer)
                {
                    headerResult = new AccountHeaderBuilder()
                            .withActivity(activity)
                            .withHeaderBackground(R.drawable.header_image_player)
                            .addProfiles(
                                    profile
                            )
                            .build();
                }
                else
                {
                    headerResult = new AccountHeaderBuilder()
                            .withActivity(activity)
                            .withHeaderBackground(R.drawable.header_image_watcher)
                            .addProfiles(
                                   profile
                            )
                            .build();
                }
            }
        });

        PrimaryDrawerItem menuItem = new PrimaryDrawerItem().withIdentifier(2).withName(resources.getString(R.string.TextMenu))
                .withIcon(R.drawable.icon_menu)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener()
                {
            @Override
            public boolean onItemClick(View view, int position, IDrawerItem drawerItem)
            {
                activity.getApplicationContext().startActivity(new Intent(activity.getApplicationContext(), MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
                activity.finish();

                return true;
            }
        });

        PrimaryDrawerItem runStreamItem = new PrimaryDrawerItem().withIdentifier(3).withName(resources.getString(R.string.TextRunStream))
                .withIcon(R.drawable.icon_videocam);

        PrimaryDrawerItem settingsItem = new PrimaryDrawerItem().withIdentifier(4).withName(resources.getString(R.string.TextSettings)).withIcon(R.drawable.icon_settings);

        final Drawer result = new DrawerBuilder()
                .withSelectedItem(-1)
                .withActivity(activity)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        menuItem,
                        settingsItem

                )
                .build();
    }
}`
```

**Comment by mikepenz** [comment]
the `headerResult` is null in your code

**Comment by FasdAR** [comment]
I removed and left ` AccountHeader headerResult;` but it does not help. He criticizes this line ` headerResult.updateProfile(profile);`

**Comment by mikepenz** [comment]
@FasdAR I do not understand why removing would fix this. the log shows that `headerResult` is null. So you might never set it or so. This is clearly not related to the library itself
