### ISSUE TITLE
ExpandableDrawer NPE when used in StickyDrawerItems.

### ISSUE THREAD

**Issue by caman9119** [mikepenz/MaterialDrawer#1612]
Here is my code:

```java
result = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .withHasStableIds(true)
                .withAccountHeader(headerResult)
                .addStickyDrawerItems(
                        new ExpandableDrawerItem().withName("Become a Supporter")
                                .withDescription("Get Pro Features.")
                                .withIcon(GoogleMaterial.Icon.gmd_mood)
                                .withIdentifier(19).withSelectable(false)
                                .withSubItems(
                                        new SecondaryDrawerItem().withName("Beer ($1.99)")
                                                .withLevel(2)
                                                .withIcon(GoogleMaterial.Icon.gmd_local_drink)
                                                .withIdentifier(2000),
                                        new SecondaryDrawerItem()
                                                .withName("Lunch ($5.99)")
                                                .withLevel(2)
                                                .withIcon(GoogleMaterial.Icon.gmd_local_cafe)
                                                .withIdentifier(2001),
                                        new SecondaryDrawerItem()
                                                .withName("Dinner ($11.99)")
                                                .withLevel(2)
                                                .withIcon(GoogleMaterial.Icon.gmd_local_dining)
                                                .withIdentifier(2001)
                                )
                )
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Next")
                                .withIcon(GoogleMaterial.Icon.gmd_home)
                                .withIdentifier(R.id.menu_next_launch)
                                .withSelectable(true),
                        new PrimaryDrawerItem().withName("Launches")
                                .withIcon(GoogleMaterial.Icon.gmd_assignment)
                                .withIdentifier(R.id.menu_launches)
                                .withSelectable(true),
                        new PrimaryDrawerItem().withName("Missions")
                                .withIcon(R.drawable.ic_satellite)
                                .withIdentifier(R.id.menu_missions)
                                .withSelectable(true),
                        new PrimaryDrawerItem().withName("Vehicles")
                                .withIcon(R.drawable.ic_rocket)
                                .withIdentifier(R.id.menu_vehicle)
                                .withSelectable(true),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem()
                                .withIcon(GoogleMaterial.Icon.gmd_info_outline)
                                .withName("What's New?")
                                .withIdentifier(R.id.menu_new)
                                .withSelectable(false),
                        new SecondaryDrawerItem()
                                .withIcon(GoogleMaterial.Icon.gmd_feedback)
                                .withName("Feedback")
                                .withIdentifier(R.id.menu_feedback)
                                .withSelectable(false),
                        new SecondaryDrawerItem().withName("Launch Library")
                                .withDescription("Launch Data Source")
                                .withIcon(GoogleMaterial.Icon.gmd_open_in_browser)
                                .withIdentifier(R.id.menu_launch)
                                .withSelectable(true)
                ).withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem != null) {
                            navigate((int) drawerItem.getIdentifier());
                        }
                        return false;
                    }
                })
                .build();
```

And here is the NPE crash:

```
11-03 21:16:10.987 9694-9694/me.calebjones.spacelaunchnow.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: me.calebjones.spacelaunchnow.debug, PID: 9694
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                                                                                      at com.mikepenz.materialdrawer.model.ExpandableDrawerItem$1.onItemClick(ExpandableDrawerItem.java:89)
                                                                                      at com.mikepenz.materialdrawer.DrawerUtils.onFooterDrawerItemClick(DrawerUtils.java:62)
                                                                                      at com.mikepenz.materialdrawer.DrawerBuilder$4.onClick(DrawerBuilder.java:1661)
                                                                                      at android.view.View.performClick(View.java:5637)
                                                                                      at android.view.View$PerformClick.run(View.java:22429)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mikepenz** [comment]
Will be fixed in the next version.
