### ISSUE TITLE
DrawerItem Background Color

### ISSUE THREAD

**Issue by mikescamell** [mikepenz/MaterialDrawer#163]
Is it possible to change the background color of each DrawerItem when adding them? I know it's meant to be material standard by i'm doing a project where it needs to be different for each DrawerItem. Thanks and thanks for the library.

**Comment by mikepenz** [comment]
@mikescamell the default drawer items do not allow this. You can easily create your custom drawer item implementations. just look at the source of any of the implemented drawerItems. i think you should get the point :D

**Comment by mikepenz** [comment]
@mikescamell the default drawer items do not allow this. You can easily create your custom drawer item implementations. just look at the source of any of the implemented drawerItems.

**Comment by mikescamell** [comment]
Thanks @mikepenz, i already started looking to this while awaiting your answer.

**Comment by mikepenz** [comment]
@mikescamell is the best option i think ;). keeping default stuff as simple as possible. I tried to make the api really easy so everyone can add new DrawerItems as they are required. :)

**Comment by mikescamell** [comment]
I completely understand and you've done a good job :) I've pretty much got it to where i want now mostly through custom layouts. Thanks again!

**Comment by mikepenz** [comment]
@mikescamell so none of the provided items fit for your case?

**Comment by mikescamell** [comment]
It's a complete custom job. I'm taking iOS designs and adapting them. Personally i wouldn't do it but that's not what i get paid for ;)

**Comment by IlyaMyasoedov** [comment]
@mikescamell, Did you create your custom drawer item? Could you tell me what methods you overrode to change item background? Thanks in advance

**Comment by mikescamell** [comment]
Here you go:

    public class CustomPrimaryDrawerItem extends PrimaryDrawerItem {

        @Override
        public int getLayoutRes() {
            return R.layout.custom_material_drawer_item_primary;
        }
    }

**Comment by mikepenz** [comment]
@mikescamell thanks for helping. i will add a CustomDrawerItem sample to the sample application soon, so hopefully people will understand this feature easier ;)

**Comment by mikescamell** [comment]
No worries :)

**Comment by IlyaMyasoedov** [comment]
@mikescamell My code for navigation drawer give an error with CustomPrimaryDrawerItem, you wrote above:
<pre> drawerResult = new Drawer()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withActionBarDrawerToggle(true)
                .withHeader(R.layout.drawer_header)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.booklet_dukan).withIcon(R.drawable.pamyatka_icon),
                        new CustomPrimaryDrawerItem().withName(R.string.shop).withIcon(R.drawable.shop_icon).withTintSelectedIcon(true),
                        new PrimaryDrawerItem().withName(R.string.rate_app),
                        new PrimaryDrawerItem().withName(R.string.tell_to_friends),
                        new PrimaryDrawerItem().withName(R.string.write_to_developers)
                ).build();
<code>
Error:
<pre>java.lang.NullPointerException at com.mikepenz.materialdrawer.model.PrimaryDrawerItem.convertView(PrimaryDrawerItem.java:99)
            at com.mikepenz.materialdrawer.adapter.DrawerAdapter.getView(DrawerAdapter.java:96)
            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
            at android.widget.AbsListView.obtainView(AbsListView.java:2159)
            at android.widget.ListView.makeAndAddView(ListView.java:1831)
            at android.widget.ListView.fillDown(ListView.java:674)
            at android.widget.ListView.fillFromTop(ListView.java:735)
            at android.widget.ListView.layoutChildren(ListView.java:1638)
            at android.widget.AbsListView.onLayout(AbsListView.java:1994)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:931)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1896)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1715)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:993)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4397)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:152)
            at android.app.ActivityThread.main(ActivityThread.java:5132)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
<code>

**Comment by mikepenz** [comment]
@IlyaMyasoedov if you create the drawer like mentioned by @mikescamell the layout must include the same id's as the original layout. if you want a complete custom layout you should also overwrite `convertView`

look at this drawerItem how it's implemented
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java

**Comment by IlyaMyasoedov** [comment]
Mike, you mentioned that there are two ways to solve the problem, Could you explain how i can change the background color without need to override "convertView" method? (proposed @mikescamell). Sorry to trouble you again. 
To change the background color we need to get RelativeLayout from R.layout.material_drawer_item_primary, but i can't know the way to do this without LayoutInflater.

**Comment by mikepenz** [comment]
@IlyaMyasoedov you have not posted the layout of your custom drawerItem or the CustomDrawerItem itself

**Comment by IlyaMyasoedov** [comment]
@mikepenz I understood what you mean. Thanks for your help. Now all works perfectly. I didn't add a new custom layout. 
![screenshot_2015-04-22-08-23-17](https://cloud.githubusercontent.com/assets/10130086/7267796/56eaf256-e8c9-11e4-93cd-037e87051389.png)
Here is my code for CustomPrimaryDrawerItem:
<pre>
public class CustomPrimaryDrawerItem extends PrimaryDrawerItem {
    private int icon = 0;
    private int background = 0;
    private int name = 0;


    @Override
    public CustomPrimaryDrawerItem withIcon(int icon){
        this.icon = icon;
        return this;
    }

    public CustomPrimaryDrawerItem withBackground(int background){
        this.background = background;
        return this;
    }

    @Override
    public CustomPrimaryDrawerItem withName(int name){
        this.name = name;
        return this;
    }


    @Override
    public int getLayoutRes() {
        return R.layout.material_drawer_item_primary;
    }

    @Override
    public View convertView(LayoutInflater inflater, View convertView, ViewGroup parent) {

        Context ctx = parent.getContext();

        ViewHolder viewHolder;
        if (convertView == null) {
            convertView = inflater.inflate(getLayoutRes(), parent, false);
            viewHolder = new ViewHolder(convertView);
            convertView.setTag(viewHolder);
        } else {
            viewHolder = (ViewHolder) convertView.getTag();
        }
        viewHolder.view.setBackgroundResource(background);

        //setting name
        viewHolder.name.setText(name);
        viewHolder.name.setTextColor(Color.WHITE);

        viewHolder.description.setVisibility(View.GONE);

        //setting icon
        viewHolder.icon.setImageResource(icon);



        return convertView;
    }

    private static class ViewHolder {
        private View view;
        private ImageView icon;
        private TextView name;
        private TextView description;

        private ViewHolder(View view) {
            this.view = view;
            this.icon = (ImageView)view.findViewById(R.id.icon);
            this.name = (TextView)view.findViewById(R.id.name);
            this.description = (TextView)view.findViewById(R.id.description);
        }
    }
}
<code>

**Comment by mikepenz** [comment]
@IlyaMyasoedov great :) and looks nice

**Comment by tomlobato** [comment]
great, tks!
I`ve ended up with another approach, with anonymous classes:

        for (WedMenuItem wedMenuItem: WedMenuItem.itemsToShow(wedding)) {
            PrimaryDrawerItem item = new PrimaryDrawerItem() {
                @Override
                public void onPostBindView(IDrawerItem drawerItem, View view) {
                    super.onPostBindView(drawerItem, view);
                    view.setBackgroundColor(getResources().getColor(R.color.green_200));
                }
            };
            item.withName(wedMenuItem.title())
            .withIdentifier(wedMenuItem.ordinal());
            drawer.addItem(item);
        }

**Comment by kiotoze** [comment]
@tomlobato Nice solution, thanks!
