### ISSUE TITLE
Unable to start activity ComponentInfo, caused by NullPointerException

### ISSUE THREAD

**Issue by HEATH3N** [mikepenz/MaterialDrawer#1649]
I'm having trouble getting this to work in a blank app. 

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        new DrawerBuilder().withActivity(this).build();
        setContentView(R.layout.activity_main);
    }
}
```

```
minSdkVersion 19
compileSdkVersion 23
```

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile('com.mikepenz:materialdrawer:5.8.0@aar') {
        transitive = true
    }
}
```

```
12-04 16:37:25.742 24844-24844/? E/dalvikvm: >>>>> Normal User
12-04 16:37:25.742 24844-24844/? E/dalvikvm: >>>>> com.concordiapps.boulder [ userId:0 | appId:10591 ]
12-04 16:37:25.752 24844-24844/? D/dalvikvm: Late-enabling CheckJNI
12-04 16:37:26.182 24844-24844/com.concordiapps.boulder I/Xposed: HIDE EM
12-04 16:37:26.192 24844-24844/com.concordiapps.boulder I/InstantRun: Instant Run Runtime started. Android package is com.concordiapps.boulder, real application class is null.
12-04 16:37:26.212 24844-24844/com.concordiapps.boulder W/InstantRun: No instant run dex files added to classpath
12-04 16:37:26.232 24844-24844/com.concordiapps.boulder I/PersonaManager: getPersonaService() name persona_policy
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve interface method 20880: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve interface method 20882: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve interface method 20886: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 723: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 745: Landroid/content/res/TypedArray;.getType (I)I
12-04 16:37:26.262 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
12-04 16:37:26.272 24844-24844/com.concordiapps.boulder I/PersonaManager: getPersonaService() name persona_policy
12-04 16:37:26.322 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.widget.FrameLayout.startActionModeForChild, referenced from method android.support.v7.widget.ActionBarContainer.startActionModeForChild
12-04 16:37:26.322 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 21366: Landroid/widget/FrameLayout;.startActionModeForChild (Landroid/view/View;Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
12-04 16:37:26.322 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6f at 0x0002
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 455: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 686: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 688: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
12-04 16:37:26.332 24844-24844/com.concordiapps.boulder D/skia: GFXPNG PNG bitmap created width:42 height:126 bitmap id is 270 
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder D/skia: GFXPNG PNG bitmap created width:18 height:18 bitmap id is 271 
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder D/skia: GFXPNG PNG bitmap created width:18 height:18 bitmap id is 272 
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder D/skia: GFXPNG PNG bitmap created width:18 height:18 bitmap id is 273 
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve instanceof 161 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
12-04 16:37:26.342 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x20 at 0x000c
12-04 16:37:26.352 24844-24844/com.concordiapps.boulder D/skia: GFXPNG PNG bitmap created width:72 height:72 bitmap id is 274 
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.mikepenz.materialize.MaterializeBuilder.build
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 20902: Landroid/view/Window;.setStatusBarColor (I)V
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x012e
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder I/dalvikvm: Could not find method android.view.Window.setNavigationBarColor, referenced from method com.mikepenz.materialize.MaterializeBuilder.build
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder W/dalvikvm: VFY: unable to resolve virtual method 20901: Landroid/view/Window;.setNavigationBarColor (I)V
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder D/dalvikvm: VFY: replacing opcode 0x6e at 0x0144
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder D/AndroidRuntime: Shutting down VM
12-04 16:37:26.362 24844-24844/com.concordiapps.boulder W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417f0da0)
12-04 16:37:26.372 24844-24844/com.concordiapps.boulder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.concordiapps.boulder, PID: 24844
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.concordiapps.boulder/com.concordiapps.boulder.MainActivity}: java.lang.NullPointerException
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:169)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5476)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: java.lang.NullPointerException
                                                                              at android.view.ViewGroup.addViewInner(ViewGroup.java:3770)
                                                                              at android.view.ViewGroup.addView(ViewGroup.java:3624)
                                                                              at android.support.v4.widget.DrawerLayout.addView(DrawerLayout.java:1972)
                                                                              at android.view.ViewGroup.addView(ViewGroup.java:3600)
                                                                              at com.mikepenz.materialize.MaterializeBuilder.build(MaterializeBuilder.java:411)
                                                                              at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1275)
                                                                              at com.concordiapps.boulder.MainActivity.onCreate(MainActivity.java:16)
                                                                              at android.app.Activity.performCreate(Activity.java:5451)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:169) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5476) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by mikepenz** [comment]
@HEATH3N the first thing I see is that you use an old appcompat version with the lastest MaterialDrawer. the latest version of the `MaterialDrawer` needs the latest appcompat version too. otherwise you have to exclude the included appcompat version. 


The crash occurs because it seems that you have not added your layout to the activity yet?

Please call `setContentView` first
