### ISSUE TITLE
IllegalStateException while committing fragment transaction

### ISSUE THREAD

**Issue by ankitbatra11** [mikepenz/MaterialDrawer#1661]
Non-fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
       at com.tools.screenshot.home.ui.activities.HomeActivity.onDrawerItemClick(SourceFile:309)
       at com.tools.screenshot.home.ui.activities.HomeActivity.onClick(SourceFile:181)
       at com.tools.screenshot.home.ui.activities.HomeDrawer$1.onItemClick(SourceFile:55)
       at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(SourceFile:1716)
       at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(SourceFile:1690)
       at com.mikepenz.fastadapter.FastAdapter$1.onClick(SourceFile:492)
       at android.view.View.performClick(View.java:4508)
       at android.view.View$PerformClick.run(View.java:18675)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

Just searched in the issues, is this the same as https://github.com/mikepenz/MaterialDrawer/issues/862?

**Comment by mikepenz** [comment]
@ankitbatra11 sorry this is not MaterialDrawer related. 

But it seems like you are also doing this after the activity was destroyed

**Comment by ankitbatra11** [comment]
Thanks for the prompt reply. Will put a guard check before committing.
