### ISSUE TITLE
NPE with ExpandableDrawerItem as StickyItem

### ISSUE THREAD

**Issue by dexion** [mikepenz/MaterialDrawer#1662]
Hello, Mike!

```JAVA
.addDrawerItems(
    new PrimaryDrawerItem()
            .withName(R.string.drawer_item_calculator)
            .withSelectable(false)
            .withIcon(CommunityMaterial.Icon.cmd_calculator)
            .withIdentifier(1000),
    new PrimaryDrawerItem()
            .withName(R.string.drawer_item_statistic)
            .withSelectable(false)
            .withIcon(CommunityMaterial.Icon.cmd_chart_line)
            .withIdentifier(2000),
    new DividerDrawerItem()
)
.addStickyDrawerItems(
    new ExpandableDrawerItem()
        .withName(R.string.drawer_item_help)
        .withSelectable(false)
        .withIcon(CommunityMaterial.Icon.cmd_help)
        .withIdentifier(19)
        .withSubItems(
            new SecondaryDrawerItem()
                .withSelectable(false)
                .withLevel(2)
                .withName(R.string.drawer_item_first)
                .withIcon(CommunityMaterial.Icon.cmd_cake_variant)
                .withIdentifier(10),
            new DividerDrawerItem(),
            new SecondaryDrawerItem()
                .withSelectable(false)
                .withLevel(2)
                .withName(R.string.drawer_item_second)
                .withIcon(CommunityMaterial.Icon.cmd_help)
                .withIdentifier(20)
        )
)
```

crash when try expand item with
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.**********, PID: 5820
                  Theme: themes:{}
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                      at com.mikepenz.materialdrawer.model.ExpandableDrawerItem$1.onItemClick(ExpandableDrawerItem.java:89)
                      at com.mikepenz.materialdrawer.DrawerUtils.onFooterDrawerItemClick(DrawerUtils.java:62)
                      at com.mikepenz.materialdrawer.DrawerBuilder$4.onClick(DrawerBuilder.java:1661)
                      at android.view.View.performClick(View.java:5204)
                      at android.view.View$PerformClick.run(View.java:21158)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5471)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

If `ExpandableDrawerItem` move into `addDrawerItems` method all works fine.

**Comment by mikepenz** [comment]
@dexion the `StickyFooter` can't have `SubItems`

**Comment by dexion** [comment]
Why not? It's very useful.

**Comment by mikepenz** [comment]
Because the sticky footer is basically a `LinearLayout` with the flat items in. It is no `RecyclerView` which may handle all their child views too.

**Comment by dexion** [comment]
Ok. Then it will be feature request )

**Comment by mikepenz** [comment]
After some time thinking about this. It's currently not on my list of features I will add. 

I would be happy about a PR though
