### ISSUE TITLE
Verifier rejected class

### ISSUE THREAD

**Issue by Kolobok163rus** [mikepenz/MaterialDrawer#1665]
```
E/AndroidRuntime:
 FATAL EXCEPTION: main
                  Process: home.myapp, PID: 4492
                  java.lang.VerifyError: Verifier rejected class com.mikepenz.materialdrawer.DrawerBuilder: void com.mikepenz.materialdrawer.DrawerBuilder.addMenuItems(android.view.Menu, boolean) failed to verify: void com.mikepenz.materialdrawer.DrawerBuilder.addMenuItems(android.view.Menu, boolean): [0xBB] register v0 has type Precise Reference: com.mikepenz.materialdrawer.model.interfaces.IDrawerItem[] but expected Reference: com.mikepenz.fastadapter.IItem[]Verifier rejected class com.mikepenz.materialdrawer.DrawerBuilder: com.mikepenz.materialdrawer.DrawerBuilder com.mikepenz.materialdrawer.DrawerBuilder.addDrawerItems(com.mikepenz.materialdrawer.model.interfaces.IDrawerItem[]) failed to verify: com.mikepenz.materialdrawer.DrawerBuilder com.mikepenz.materialdrawer.DrawerBuilder.addDrawerItems(com.mikepenz.materialdrawer.model.interfaces.IDrawerItem[]): [0x9] register v5 has type Reference: com.mikepenz.materialdrawer.model.interfaces.IDrawerItem[] but expected Reference: com.mikepenz.fastadapter.IItem[] (declaration of 'com.mikepenz.materialdrawer.DrawerBuilder' appears in /data/app/home.myapp/base.apk)
                      at home.myapp.MainActivity.onCreate(MainActivity.java:60)
                      at android.app.Activity.performCreate(Activity.java:6664)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Application terminated.

```

**Comment by mikepenz** [comment]
@Kolobok163rus have you cleaned your project? Do you have a bad proguard config? Do you have older versions of one of my other libs in the project?

**Comment by Kolobok163rus** [comment]
First project was your MaterialDrawer from this article https://habrahabr.ru/post/250765/ after I just changed build.gradle replacing it ```
compile('com.mikepenz.materialdrawer:library:0.9.5@aar') {
    transitive = true
}

```
on this
```
compile('com.mikepenz:materialdrawer:5.8.1@aar') {
    transitive = true
}
``` 
After that stopped working.

**Comment by mikepenz** [comment]
@Kolobok163rus so you don't have any of my other libraries as dependency?
What's your support lib version?

**Comment by Kolobok163rus** [comment]
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile('com.mikepenz:materialdrawer:5.8.1@aar') {
        transitive = true
    }
    compile 'com.mikepenz:fontawesome-typeface:4.7.0.0@aar'
    testCompile 'junit:junit:4.12'
}
```

**Comment by Kolobok163rus** [comment]
woohoo, I solved the problem. i just update sdk-tools. Sorry for the useless concern

**Comment by npomfret** [comment]
@Kolobok163rus 

> woohoo, I solved the problem. i just update idk-tools

I have a similar error, what tools version did you refer to?

**Comment by mikepenz** [comment]
@npomfret make sure the support libs do not conflict. you can exclude the (in the lib) defined version if you have a different one
