### ISSUE TITLE
setToolbar fails with persistent drawer activity

### ISSUE THREAD

**Issue by Mygod** [mikepenz/MaterialDrawer#1682]
I was trying to make a minidrawer based on the sample in [`PersistentDrawerActivity.java`](https://github.com/mikepenz/MaterialDrawer/blob/bfeca71/app/src/main/java/com/mikepenz/materialdrawer/app/PersistentDrawerActivity.java). However I got this instead:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.github.shadowsocks, PID: 23369
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.widget.DrawerLayout.isDrawerOpen(int)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6126)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.widget.DrawerLayout.isDrawerOpen(int)' on a null object reference
                      at android.support.v7.app.ActionBarDrawerToggle.syncState(ActionBarDrawerToggle.java:242)
                      at com.mikepenz.materialdrawer.DrawerBuilder.handleDrawerNavigation(DrawerBuilder.java:1418)
                      at com.mikepenz.materialdrawer.Drawer.setToolbar(Drawer.java:108)
                      at com.github.shadowsocks.ToolbarFragment.onViewCreated(ToolbarFragment.scala:35)
                      at com.github.shadowsocks.ProfilesFragment.onViewCreated(ProfilesFragment.scala:256)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1010)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                      at android.app.BackStackRecord.run(BackStackRecord.java:816)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                      at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                      at android.app.Activity.performStart(Activity.java:6695)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6126) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

Here's the [related commit](https://github.com/Mygod/shadowsocks-android/commit/0732dd598172a00a295b6904b70fb683bb96c280). It works fine on my portrait but breaks on landscape (where I enabled persistent drawer). Any help would be appreciated.

**Comment by mikepenz** [comment]
@Mygod makes sense as in the persistent drawer scenario there is no `DrawerLayout` so you can't (and don't ahve to provide the `Toolbar`) . as a `ActionBarDrawerToggle` wouldn't be used anyway.

Please just don't pass the toolbar in the landscape mode

**Comment by Mygod** [comment]
Hmm yeah that makes sense. Thanks.
