### ISSUE TITLE
Issues upgrading from 3.1.2 to 5.8.1

### ISSUE THREAD

**Issue by snijsure** [mikepenz/MaterialDrawer#1695]
I am upgrading my project from 3.1.2 to 5.8.1 and I think I have followed instructions on upgrading correctly however I am getting following crash: Note I am using latest support library 2.5.1 and compileSDKVersion is set to 25

My changes to upgrade from 3.1.2 to 5.8.1 are as follows:

change app/build.gradle 
Removed:
    compile 'com.mikepenz:materialdrawer:3.1.2'

Added:
```
 compile('com.mikepenz:fastadapter:2.1.5@aar') {
    transitive = true
  }
  compile('com.mikepenz:materialdrawer:5.8.1@aar') {
   transitive = true
}
```

Change signature of onItemClick from:
```
public boolean onItemClick(AdapterView<?> adapterView, View view, int position, long id,              IDrawerItem iDrawerItem) 
```
To new signature          
```
public boolean onItemClick(View view, int position, IDrawerItem drawerItem) 
```
Actual code where I use MatrialDrawer library is actually very simple couple of PrimaryDrawerItem.

Why would I be getting this crash, note I am not using FastAdapter anywhere else. Do I need to update by proguard files, but I am also getting same crash when proguard is disabled.
```
 FATAL EXCEPTION: main
                                                                       PID: 5139
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(android.content.res.ColorStateList)' on a null object reference
                                                                           at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:85)
                                                                           at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:73)
                                                                           at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:20)
                                                                           at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1835)
                                                                           at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:573)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                           at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                           at android.view.View.layout(View.java:17637)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
 E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mikepenz** [comment]
which `DrawerItem` are you using?

**Comment by snijsure** [comment]
I am using PrimaryDrawerItem.

`    PrimaryDrawerItem exploreItem =
        getCustomDrawerItem(R.string.title_discover, R.drawable.icon_drawer_explore,
            R.drawable.icon_drawer_explore_na);
    PrimaryDrawerItem ntkItem = getCustomDrawerItem(R.string.title_ntk, R.drawable.icon_drawer_ntk,
        R.drawable.icon_drawer_ntk_na);
    PrimaryDrawerItem favoritesItem =
        getCustomDrawerItem(R.string.title_favorites, R.drawable.icon_drawer_favorites,
            R.drawable.icon_drawer_favorites_na);`

And using them here:

`
    navDrawer = new DrawerBuilder().withActivity(this)
        .withToolbar(toolbar)
        .withTranslucentStatusBar(true)
        .withSelectedItem(presenter.getTab())
        .addDrawerItems(exploreItem, ntkItem, favoritesItem)
        .withHeader(header)
        .withStickyFooter(R.layout.footer_drawer)
        .withFooterClickable(true).build();`

**Comment by mikepenz** [comment]
CustomDrawerItem? you have overwritten an existing `DrawerItem` or modified it's layout?

**Comment by snijsure** [comment]
That private method getCustomDrawerItem ☝️ is mis-named, there is nothing custom about its just a convenience function that creates PrimaryDrawerItem.  I have not over-ridden DrawerItem or modified layout.

**Comment by mikepenz** [comment]
@snijsure can you please clean and rebuild the project? 
the crash occurs on a position where it shouldn't if nothing is modified or overwritten
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.java#L85

**Comment by snijsure** [comment]
@mikepenz I did rm -rf in my app/build, build directory as well as my ~/.gradle/cache thinking this might be cache issue. Same result.

I put break point in my code BaseViewHolder  ( https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseViewHolder.java ) and icon/name/description are all null at end of that constructor.

Now in case of sample app I see you do this

`new RecyclerViewCacheUtil<IDrawerItem>().withCacheSize(2).apply(result.getRecyclerView(), result.getDrawerItems());`

And in sample app case above call to RecyclerViewCacheUtil seem to be initializing BaseViewHolders. I have attached my code that sets up navigation drawer

[menu.txt](https://github.com/mikepenz/MaterialDrawer/files/700381/menu.txt)

**Comment by snijsure** [comment]
@mikepenz Is there like a branch/tag for 3.8.1 , I looked around and didn't find one. I was thinking I could take sample app from that branch and see if I can reproduce the issue? Is there anything I can do to sort this issue out?

**Comment by mikepenz** [comment]
@snijsure there was never  aversion 3.8.1 
https://github.com/mikepenz/MaterialDrawer/releases?after=v4.0.1

**Comment by mikepenz** [comment]
Close as inactive for too long. Please report back if this is still an issue.
