### ISSUE TITLE
Can not be used with Android-Iconics

### ISSUE THREAD

**Issue by TshineZheng** [mikepenz/MaterialDrawer#1701]
```java
public class MyActivity extends AppCompatActivity
{
protected void onCreate(Bundle savedInstanceState) {
        LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Drawer mDrawer = new DrawerBuilder()
                .withActivity(this)
                .build();

        PrimaryDrawerItem primaryDrawerItem = new PrimaryDrawerItem()
                .withName("item")
                .withDescription("item");

        PrimaryDrawerItem crashedPrimaryDrawerItem = new PrimaryDrawerItem()
                        .withName("crashitem")
                        .withDescription("{some_icons}balabla");

        mDrawer.addItem(primaryDrawerItem);
        mDrawer.addItem(crashedPrimaryDrawerItem);
}
}
```

After running, switch the two DrawerItem, it will crash

```
01-18 10:22:34.155 4238-4238/me.tshine.easymark E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: me.tshine.easymark, PID: 4238
                                                                  java.lang.IndexOutOfBoundsException
                                                                      at android.graphics.Paint.getRunAdvance(Paint.java:2557)
                                                                      at android.text.TextLine.handleText(TextLine.java:719)
                                                                      at android.text.TextLine.handleRun(TextLine.java:932)
                                                                      at android.text.TextLine.measureRun(TextLine.java:387)
                                                                      at android.text.TextLine.measure(TextLine.java:277)
                                                                      at android.text.TextLine.metrics(TextLine.java:251)
                                                                      at android.text.Layout.getLineExtent(Layout.java:1067)
                                                                      at android.text.Layout.getLineMax(Layout.java:1023)
                                                                      at android.text.Layout.getLineRight(Layout.java:1000)
                                                                      at android.widget.Editor.drawHardwareAccelerated(Editor.java:1721)
                                                                      at android.widget.Editor.onDraw(Editor.java:1657)
                                                                      at android.widget.TextView.onDraw(TextView.java:5856)
                                                                      at android.view.View.draw(View.java:17067)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                                      at android.view.View.draw(View.java:16833)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                                      at android.view.View.draw(View.java:16833)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                      at android.view.View.draw(View.java:17070)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                                      at android.view.View.draw(View.java:16833)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                      at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4400)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                      at android.view.View.draw(View.java:17070)
                                                                      at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3792)
                                                                      at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                                      at android.view.View.draw(View.java:16833)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                      at android.view.View.draw(View.java:17070)
                                                                      at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                                      at android.view.View.draw(View.java:16833)
                                                                      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                      at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
.
.
.
.
```

**Comment by mikepenz** [comment]
Which version of the drawer / iconics do you use?

**Comment by TshineZheng** [comment]
com.mikepenz:iconics-core:2.8.2@aar
com.mikepenz:materialdrawer:5.8.1@aar

**Comment by mikepenz** [comment]
@TshineZheng seems like this is not properly supported in the android framework. The exception is not thrown in any of the libs. 

please remove:
```
LayoutInflaterCompat.setFactory(getLayoutInflater(), new IconicsLayoutInflater(getDelegate()));
```

and handle the icons for the `TextView`s specifically
