### ISSUE TITLE
Having issues with this line .build();

### ISSUE THREAD

**Issue by Technologx** [mikepenz/MaterialDrawer#1732]
Every time I go to debug the app I'm working on on my phone I run into a error and it deals with this line 

> .build();

 every time &amp; I'm not sure why.

Here's my code:
````
package com.technologx.bluerain.sample;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.CompoundButton;
import android.widget.Toast;

import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.interfaces.OnCheckedChangeListener;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.Nameable;

public class MainActivity extends AppCompatActivity {

    private Drawer result = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(R.layout.nav_header_main)
                .withHeaderDivider(false)
                .withActionBarDrawerToggle(true)
                .withHeaderDivider(false)
                .withSliderBackgroundColorRes(R.color.material_drawer_background)
                .addDrawerItems(

                        new PrimaryDrawerItem().withName(R.string.nav_home).withIdentifier(1).withIcon(R.drawable.ic_home),
                        new PrimaryDrawerItem().withName(R.string.nav_icons).withIdentifier(2).withIcon(R.drawable.ic_icons),
                        new PrimaryDrawerItem().withName(R.string.nav_wallpapers).withIdentifier(3).withIcon(R.drawable.ic_wallpapers),
                        new PrimaryDrawerItem().withName(R.string.nav_apply).withIdentifier(4).withIcon(R.drawable.ic_apply),
                        new PrimaryDrawerItem().withName(R.string.nav_request).withIdentifier(5).withIcon(R.drawable.ic_request),
                        new PrimaryDrawerItem().withName(R.string.nav_kustom).withIdentifier(6).withIcon(R.drawable.ic_widgets),
                        new PrimaryDrawerItem().withName(R.string.nav_zooper).withIdentifier(7).withIcon(R.drawable.ic_widgets),
                        new PrimaryDrawerItem().withName(R.string.nav_settings).withIdentifier(8).withIcon(R.drawable.ic_settings)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        long id = drawerItem.getIdentifier();
                        if (id == 1) {
                            Toast.makeText(MainActivity.this, "Home", Toast.LENGTH_SHORT).show();
                        } else if (id == 2) {
                            Toast.makeText(MainActivity.this, "Icons", Toast.LENGTH_SHORT).show();
                        } else if (id == 3) {
                            Toast.makeText(MainActivity.this, "Wallpapers", Toast.LENGTH_SHORT).show();
                        } else if (id == 4) {
                            Toast.makeText(MainActivity.this, "Apply", Toast.LENGTH_SHORT).show();
                        } else if (id == 5) {
                            Toast.makeText(MainActivity.this, "Request", Toast.LENGTH_SHORT).show();
                        } else if (id == 6) {
                            Toast.makeText(MainActivity.this, "Kustom", Toast.LENGTH_SHORT).show();
                        } else if (id == 7) {
                            Toast.makeText(MainActivity.this, "Zooper", Toast.LENGTH_SHORT).show();
                        } else if (id == 8) {
                            Toast.makeText(MainActivity.this, "Settings", Toast.LENGTH_SHORT).show();
                        }

                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
//                .withShowDrawerUntilDraggedOpened(true)
                .build();
    }

    private OnCheckedChangeListener onCheckedChangeListener = new OnCheckedChangeListener() {
        @Override
        public void onCheckedChanged(IDrawerItem drawerItem, CompoundButton buttonView, boolean isChecked) {
            if (drawerItem instanceof Nameable) {
                Log.i("material-drawer", "DrawerItem: " + ((Nameable) drawerItem).getName() + " - toggleChecked: " + isChecked);
            } else {
                Log.i("material-drawer", "toggleChecked: " + isChecked);
            }
        }
    };

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        //add the values which need to be saved from the drawer to the bundle
        outState = result.saveInstanceState(outState);
        //add the values which need to be saved from the accountHeader to the bundle
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onBackPressed() {
        //handle the back press :D close the drawer first and if the drawer is closed close the activity
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }
}
````

Any help would be greatly appreciated.

Also here's what comes up when the app crashes:
````
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.technologx.bluerain.sample, PID: 32233
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.technologx.bluerain.sample/com.technologx.bluerain.sample.MainActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                      at android.app.ActivityThread.access$800(ActivityThread.java:162)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5431)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                   Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                      at android.view.ViewGroup.addView(ViewGroup.java:3781)
                      at android.support.v4.widget.DrawerLayout.addView(DrawerLayout.java:1972)
                      at android.view.ViewGroup.addView(ViewGroup.java:3761)
                      at com.mikepenz.materialize.MaterializeBuilder.build(MaterializeBuilder.java:411)
                      at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1275)
                      at com.technologx.bluerain.sample.MainActivity.onCreate(MainActivity.java:76)
                      at android.app.Activity.performCreate(Activity.java:6056)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:162) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5431) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
````

**Comment by mikepenz** [comment]
@Technologx which version of the drawer are you using?

**Comment by IvanMazzoli** [comment]
I usually inflate the header and don't pass the R.layout, try that

**Comment by Technologx** [comment]
@mikepenz I"m using the latest version &amp; @IvanMazzoli I have no idea what your trying to have me do I'm new to android coding.

**Comment by mikepenz** [comment]
@Technologx if you remove `.withHeader(R.layout.nav_header_main)` will it work?

**Comment by DreadTank27** [comment]
Try this:
`View header = getLayoutInflater().inflate(R.layout.drawer_header, null);`
`.withHeader(header)`

**Comment by Technologx** [comment]
Either way I do it I still get issues with the 

> .build();

 line

**Comment by Technologx** [comment]
I got my issue figured out I wasn't calling a activity for the drawer to mount to.

````
package com.technologx.bluerain.sample;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.widget.CompoundButton;
import android.widget.Toast;

import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.interfaces.OnCheckedChangeListener;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.Nameable;

public class MainActivity extends AppCompatActivity {

    private Drawer result = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.content_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        View header = getLayoutInflater().inflate(R.layout.nav_header_main, null);

        result = new DrawerBuilder(this)
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(header)
                .withHeaderDivider(false)
                .withActionBarDrawerToggle(true)
                .withHeaderDivider(false)
                .withSliderBackgroundColorRes(R.color.material_drawer_background)
                .addDrawerItems(

                        new PrimaryDrawerItem().withName(R.string.nav_home).withIdentifier(1).withIcon(R.drawable.ic_home),
                        new PrimaryDrawerItem().withName(R.string.nav_icons).withIdentifier(2).withIcon(R.drawable.ic_icons),
                        new PrimaryDrawerItem().withName(R.string.nav_wallpapers).withIdentifier(3).withIcon(R.drawable.ic_wallpapers),
                        new PrimaryDrawerItem().withName(R.string.nav_apply).withIdentifier(4).withIcon(R.drawable.ic_apply),
                        new PrimaryDrawerItem().withName(R.string.nav_request).withIdentifier(5).withIcon(R.drawable.ic_request),
                        new PrimaryDrawerItem().withName(R.string.nav_kustom).withIdentifier(6).withIcon(R.drawable.ic_widgets),
                        new PrimaryDrawerItem().withName(R.string.nav_zooper).withIdentifier(7).withIcon(R.drawable.ic_widgets),
                        new PrimaryDrawerItem().withName(R.string.nav_settings).withIdentifier(8).withIcon(R.drawable.ic_settings)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        long id = drawerItem.getIdentifier();
                        if (id == 1) {
                            Toast.makeText(MainActivity.this, "Home", Toast.LENGTH_SHORT).show();
                        } else if (id == 2) {
                            Toast.makeText(MainActivity.this, "Icons", Toast.LENGTH_SHORT).show();
                        } else if (id == 3) {
                            Toast.makeText(MainActivity.this, "Wallpapers", Toast.LENGTH_SHORT).show();
                        } else if (id == 4) {
                            Toast.makeText(MainActivity.this, "Apply", Toast.LENGTH_SHORT).show();
                        } else if (id == 5) {
                            Toast.makeText(MainActivity.this, "Request", Toast.LENGTH_SHORT).show();
                        } else if (id == 6) {
                            Toast.makeText(MainActivity.this, "Kustom", Toast.LENGTH_SHORT).show();
                        } else if (id == 7) {
                            Toast.makeText(MainActivity.this, "Zooper", Toast.LENGTH_SHORT).show();
                        } else if (id == 8) {
                            Toast.makeText(MainActivity.this, "Settings", Toast.LENGTH_SHORT).show();
                        }

                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                .build();
    }

    private OnCheckedChangeListener onCheckedChangeListener = new OnCheckedChangeListener() {
        @Override
        public void onCheckedChanged(IDrawerItem drawerItem, CompoundButton buttonView, boolean isChecked) {
            if (drawerItem instanceof Nameable) {
                Log.i("material-drawer", "DrawerItem: " + ((Nameable) drawerItem).getName() + " - toggleChecked: " + isChecked);
            } else {
                Log.i("material-drawer", "toggleChecked: " + isChecked);
            }
        }
    };

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        //add the values which need to be saved from the drawer to the bundle
        outState = result.saveInstanceState(outState);
        //add the values which need to be saved from the accountHeader to the bundle
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onBackPressed() {
        //handle the back press :D close the drawer first and if the drawer is closed close the activity
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }
}
````
