### ISSUE TITLE
Custom DrawerItems' viewholders get mixed some how

### ISSUE THREAD

**Issue by roostaamir** [mikepenz/MaterialDrawer#1768]
Hi
I want to create more than one custome `DrawerItems` and somehow their viewholders will get mixed in the framework

here's the code for my custome `DrawerItems` :

```
public class HeaderDrawerItem extends BaseDrawerItem<HeaderDrawerItem, HeaderDrawerItem.ViewHolder> {

    private StringHolder name;
    private StringHolder number;

    @Override
    public int getType() {
        return R.id.material_drawer_item_primary;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return R.layout.header_drawer_item;
    }

    @Override
    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    @Override
    public void bindView(ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);
        name.applyTo(holder.name);
        number.applyTo(holder.number);

        onPostBindView(this, holder.itemView);
    }

    @Override
    public HeaderDrawerItem withName(String name) {
        this.name = new StringHolder(name);
        return this;
    }

    public HeaderDrawerItem withNumber(String number) {
        this.number = new StringHolder(number);
        return this;
    }

    @Override
    public StringHolder getName() {
        return this.name;
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {

        private TextView name;
        private TextView number;

        public ViewHolder(View view) {
            super(view);

            this.name = (TextView) view.findViewById(R.id.material_drawer_header_name);
            this.number = (TextView) view.findViewById(R.id.material_drawer_header_number);
        }
    }
}
```

and :

```
public class RightToLeftDrawerItem extends BaseDrawerItem<RightToLeftDrawerItem, RightToLeftDrawerItem.ViewHolder> {

    private ImageHolder icon;
    private StringHolder name;

    @Override
    public int getType() {
        return R.id.material_drawer_item_primary;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return R.layout.right_to_left_drawer_item;
    }

    @Override
    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    @Override
    public void bindView(ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);
        icon.applyTo(holder.icon);
        name.applyTo(holder.name);

        onPostBindView(this, holder.itemView);
    }

    @Override
    public RightToLeftDrawerItem withIcon(@DrawableRes int iconRes) {
        icon = new ImageHolder(iconRes);
        return this;
    }

    @Override
    public ImageHolder getIcon() {
        return this.icon;
    }

    @Override
    public RightToLeftDrawerItem withName(String name) {
        this.name = new StringHolder(name);
        return this;
    }

    @Override
    public StringHolder getName() {
        return this.name;
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

    public static class ViewHolder extends RecyclerView.ViewHolder{

        private ImageView icon;
        private TextView name;

        public ViewHolder(View view) {
            super(view);

            this.icon = (ImageView) view.findViewById(R.id.material_drawer_icon);
            this.name = (TextView) view.findViewById(R.id.material_drawer_name);
        }
    }
}

```

and I am creating the drawer like this:

```
private void initNavigationPanel() {
        Drawer drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        new HeaderDrawerItem().withName("some name").withNumber("some number"),
                        new DividerDrawerItem(),
                        new RightToLeftDrawerItem().withName("something").withIcon(R.drawable.truck)
                )
                .withTranslucentStatusBar(false)
                .build();
        drawer.setGravity(Gravity.RIGHT);
    }
```

I get this error :

```
java.lang.ClassCastException: com.pnpcgart.helpers.HeaderDrawerItem$ViewHolder cannot be cast to com.pnpcgart.helpers.RightToLeftDrawerItem$ViewHolder
                                                                            at com.pnpcgart.helpers.RightToLeftDrawerItem.bindView(RightToLeftDrawerItem.java:19)
                                                                            at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:1835)
                                                                            at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:573)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                            at android.view.View.layout(View.java:16922)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5405)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2413)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2122)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6944)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        	at andro
```

If I for example omit the `HeaderDrawerItem` from the `initNavigationPanel()` method, it works fine. But with the two custome `DrawerItems`, it seems that `HeaderDrawer.ViewHolder` is incorrectly passed to `RightToLeftDrawerItem`'s `BindView()` method.

what should I do?

**Comment by mikepenz** [comment]
@roostaamir the `getType()` method has to return a unique result per item. So you are not allowed define the same for multiple items

**Comment by roostaamir** [comment]
You are a life saver. Thank you
