### ISSUE TITLE
cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by MarStarck** [mikepenz/MaterialDrawer#1780]
i just wanna try to use it, but after adding 
```
new DrawerBuilder().withActivity(this).build();
```
in my OnCreate function,

my app crashed:
```
Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:4137)
	at android.support.v4.widget.DrawerLayout.addView(DrawerLayout.java:1972)
	at android.view.ViewGroup.addView(ViewGroup.java:4117)
	at com.mikepenz.materialize.MaterializeBuilder.build(MaterializeBuilder.java:411)
	at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1318)
```

**Comment by mikepenz** [comment]
@MarStarck please make sure you already defined your layout for that activity before calling this code
