### ISSUE TITLE
how to make header name and image margin right 0

### ISSUE THREAD

**Issue by ahmedsaber00** [mikepenz/MaterialDrawer#1785]
i want to make the name under the image without space between them
as this
![1](https://cloud.githubusercontent.com/assets/19168468/23944816/e08bf4d0-097c-11e7-8861-153febf8ffef.png)

but i have this
![img_20170315_124444](https://cloud.githubusercontent.com/assets/19168468/23944878/1f816a12-097d-11e7-89be-2ba80694754e.jpg)
i want to remove the red space

**Comment by mikepenz** [comment]
This is the layout for the header: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml you can copy and paste this xml to your project and adjust it to your needs. The build will automatically overwrite the variant included in the lib

**Comment by ahmedsaber00** [comment]
i made new layout 
material_drawer_header.xml
and added all th xml into it and didn't change anything else yes
but i got this error

03-15 12:58:31.558 719-719/com.aa.aa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.aa.aa, PID: 719
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aa.aa/com.aa.aa.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding(int, int, int, int)' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666)
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding(int, int, int, int)' on a null object reference
                                                                        at com.mikepenz.materialdrawer.accountswitcher.AccountHeaderBuilder.build(AccountHeaderBuilder.java:658)
                                                                        at com.aa.aa.MainActivity.onCreate(MainActivity.java:76)
                                                                        at android.app.Activity.performCreate(Activity.java:6583)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                        at android.os.Looper.loop(Looper.java:207) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by mikepenz** [comment]
@ahmedsaber00 something must be different.

**Comment by ahmedsaber00** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="@dimen/material_drawer_account_header_height"
  android:clickable="true">

  <ImageView
    android:id="@+id/material_drawer_account_header_background"
    android:layout_width="match_parent"
    android:layout_height="@dimen/material_drawer_account_header_height"
    android:scaleType="fitXY" />

  <RelativeLayout
    android:id="@+id/material_drawer_account_header"
    android:layout_width="match_parent"
    android:layout_height="@dimen/material_drawer_account_header_height">

    <com.mikepenz.materialdrawer.view.BezelImageView
      android:id="@+id/material_drawer_account_header_current"
      android:layout_width="@dimen/material_drawer_account_header_selected"
      android:layout_height="@dimen/material_drawer_account_header_selected"
      android:layout_alignParentLeft="true"
      android:layout_alignParentTop="true"
      android:layout_marginBottom="@dimen/material_drawer_account_header_horizontal_bottom"
      android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
      android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
      android:clickable="true"
      android:elevation="2dp" />

    <LinearLayout
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_alignParentRight="true"
      android:layout_alignTop="@+id/material_drawer_account_header_current"
      android:gravity="right">

      <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_first"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="2dp"
        android:visibility="gone" />

      <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_second"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="2dp"
        android:visibility="gone" />

      <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_third"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="2dp"
        android:visibility="gone" />
    </LinearLayout>

    <LinearLayout
      android:id="@+id/material_drawer_account_header_text_section"
      android:layout_width="match_parent"
      android:layout_height="56dp"
      android:layout_alignParentBottom="true"
      android:layout_alignParentLeft="true"
      android:layout_alignParentRight="true"
      android:layout_marginBottom="@dimen/material_drawer_padding"
      android:layout_toLeftOf="@+id/material_drawer_account_header_text_switcher"
      android:gravity="center_vertical"
      android:orientation="vertical"
      android:paddingEnd="56dp"
      android:paddingLeft="0dp"
      android:paddingRight="56dp"
      android:paddingStart="0dp">

      <TextView
        android:id="@+id/material_drawer_account_header_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
        android:fontFamily="sans-serif-medium"
        android:lines="1"
        android:maxLines="1"
        android:textSize="@dimen/material_drawer_account_header_text" />

      <TextView
        android:id="@+id/material_drawer_account_header_email"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
        android:fontFamily="sans-serif"
        android:lines="1"
        android:maxLines="1"
        android:textSize="@dimen/material_drawer_account_header_text" />

    </LinearLayout>

    <ImageView
      android:id="@+id/material_drawer_account_header_text_switcher"
      android:layout_width="@dimen/material_drawer_account_header_dropdown"
      android:layout_height="@dimen/material_drawer_account_header_dropdown"
      android:layout_alignParentBottom="true"
      android:layout_alignParentRight="true"
      android:layout_marginBottom="@dimen/material_drawer_account_header_dropdown_margin_bottom"
      android:layout_marginRight="@dimen/material_drawer_vertical_padding" />

  </RelativeLayout>
</FrameLayout>

**Comment by ahmedsaber00** [comment]
and file name is 
res/layout/material_drawer_header.xml

**Comment by mikepenz** [comment]
@ahmedsaber00 which version of the drawer are you using? and which version did you copy the xml from?

**Comment by mikepenz** [comment]
@ahmedsaber00 it really looks like the xml is different from the one included in the materialDrawer version you use. which one do you have in the app?

**Comment by ahmedsaber00** [comment]
compile('com.mikepenz:materialdrawer:3.0.9@aar') {
    transitive = true
  }

**Comment by mikepenz** [comment]
That's a few years old :O.

**Comment by mikepenz** [comment]
But yeah. You have to use the xml matching your version: https://github.com/mikepenz/MaterialDrawer/blob/v3.0.9/library/src/main/res/layout/material_drawer_header.xml 

I think it changed quite a bit since v4. It never changed since v5 though

**Comment by amixpal** [comment]
@mikepenz I tried to add `material_drawer_header` after some adjustment but it's not reflecting the changes in header. 

` headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.black_overlay)
                .withSavedInstance(savedInstanceState)
                .withSelectionListEnabledForSingleProfile(false)
                .withSelectionListEnabled(false)
                .withTextColor(Color.WHITE)
                .build();`
