### ISSUE TITLE
No static method getScreenWidth(Landroid/content/Context;)

### ISSUE THREAD

**Issue by Pareshoct7** [mikepenz/MaterialDrawer#1815]
My code for drawer is as following 

```java
SessionManager sessionManager = new SessionManager(this);

        String fname = sessionManager.getUserDetail().getDriver_first_name();
        String lname = sessionManager.getUserDetail().getDriver_last_name();
        String email = sessionManager.getUserDetail().getDriver_email();

AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        new ProfileDrawerItem()
                                .withName(sessionManager.getUserDetail().getDriver_first_name()+" "+sessionManager.getUserDetail().getDriver_last_name())
                                .withEmail(sessionManager.getUserDetail().getDriver_email())
                                .withIcon(R.mipmap.ic_launcher)
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();

        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1).withName("Map").withIcon(R.drawable.map)
                .withIconTintingEnabled(true);
        PrimaryDrawerItem item2 = new PrimaryDrawerItem().withIdentifier(2).withName("List").withIcon(R.drawable.list)
                .withIconTintingEnabled(true);
        PrimaryDrawerItem item3 = new PrimaryDrawerItem().withIdentifier(2).withName("My Route").withIcon(R.drawable.route)
                .withIconTintingEnabled(true);

        result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        item1,
                        item2, item3
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.e("Drawer", "Drawer Position : " + position);

                        Fragment fragment = null;

                        switch (position) {

                            case 1:
                                fragment = new HomeContainerFragment();
                                break;
                            case 2:
                                fragment = new HomeListFragment();
                                break;
                            case 3:
                                fragment = new MyRouteFragment();
                                break;
                        }

                        if (fragment != null) {
                            openFragment(R.id.fragmentContainer,fragment);
                        }

                        return false;
                        // do something with the clicked item :D
                    }
                })
                .build();
```

and i get the following error 

```java
java.lang.NoSuchMethodError: No static method getScreenWidth(Landroid/content/Context;)I in class Lcom/mikepenz/materialize/util/UIUtils; or its super classes (declaration of 'com.mikepenz.materialize.util.UIUtils' appears in /data/app/paresh.boon-1/base.apk)
                                                                 at com.mikepenz.materialdrawer.util.DrawerUIUtils.getOptimalDrawerWidth(DrawerUIUtils.java:81)
                                                                 at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:775)
                                                                 at paresh.boon.DashboardActivity.onViewReady(DashboardActivity.java:86)
                                                                 at paresh.boon.General.base.BaseActivity.onCreate(BaseActivity.java:67)
                                                                 at paresh.boon.DashboardActivity.onCreate(DashboardActivity.java:53)
                                                                 at android.app.Activity.performCreate(Activity.java:6575)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:211)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by mikepenz** [comment]
The method is in place: https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/util/UIUtils.java#L335 

Which version of `Materialize` are you using?
Which version of `MaterialDrawer` are you using?

**Comment by Pareshoct7** [comment]
i am using this version

`
compile('com.mikepenz:materialdrawer:5.8.3@aar') {
	transitive = true
}
`
and i didnt get you how to solve the error

**Comment by mikepenz** [comment]
do you have other libraries from me in your project?

**Comment by Pareshoct7** [comment]
no i only have one

**Comment by Pareshoct7** [comment]
`
//NETWORK
    compile 'com.squareup.okhttp3:logging-interceptor:3.6.0'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.2.0'
    compile 'io.reactivex:rxjava:1.2.7'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'jp.wasabeef:picasso-transformations:2.1.2'
    compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'
    compile 'com.jakewharton.timber:timber:4.5.1'
    provided 'org.glassfish:javax.annotation:10.0-b28'
    compile 'com.google.dagger:dagger:2.9'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.9'
    compile 'com.google.code.gson:gson:2.6.2'

    //Data
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.fatboyindustrial.gson-jodatime-serialisers:gson-jodatime-serialisers:1.2.0'

    //EVENT BUS
    compile 'org.greenrobot:eventbus:3.0.0'

    //Utils
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.mobsandgeeks:android-saripaar:2.0.3'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.google.android.gms:play-services-places:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.google.maps.android:android-maps-utils:0.5'

    compile 'com.github.jrvansuita:PickImage:2.1.1'
    compile 'com.wdullaer:materialdatetimepicker:3.1.3'
    compile('com.mikepenz:materialdrawer:5.8.2@aar') {
        transitive = true
    }
`

this are my gradle lines

**Comment by mikepenz** [comment]
if `5.8.2` of the MaterialDrawer works for you. Please stay with this for now. I'll check what might cause the problem with that method

**Comment by Pareshoct7** [comment]
Yes it is `5.8.2`  still not working

**Comment by mikepenz** [comment]
@Pareshoct7 ah you didn't mention that. v5.8.2 is definitely working for people. So something has to be strange about your setup. Do you have proguard enabled? 

And can you please make a `dependency`tree via gradle and send the output: 
```gradle
gradle app:dependencies
```

**Comment by Pareshoct7** [comment]
ok I will check and let you know. but my proguard is not enabled. and all the stuff is good in gradle.

**Comment by mikepenz** [comment]
Yes. There is just something causing a conflict. 

Have you cleaned your project after setting the different version number?

**Comment by Pareshoct7** [comment]
Yes i did this And can you check this for me can you take my teamviewer and check what is the issue ?

**Comment by mikepenz** [comment]
Can you please first send the output of the dependency tree?

**Comment by Pareshoct7** [comment]
Can you please check this and i dont know where is the dependency tree.

**Comment by mikepenz** [comment]
```
gradle app:dependencies
```

**Comment by mikepenz** [comment]
Could you please report back? Close this for now, as it is definitely not a library issue
