### ISSUE TITLE
Can't get Google Plus Profile Image as Profile Drawer Item

### ISSUE THREAD

**Issue by rgocal** [mikepenz/MaterialDrawer#1850]
I have the username listed and the email listed as a profile once signed in but for the life of me, I cannot get or probably don't fully understand how to pull the data for the profile image. Does anyone have a sample I can look at or walk me through what I should be looking at. Application is considered a private project so I cannot provide code openly but in a private session, i could.

**Comment by mikepenz** [comment]
@rgocal if you have an url you need to init the `DrawerImageLoader` as shown in the sample. If you have a drawable pass it to the `ProfileDrawerItem` if passed during drawer creation it's fine. If at a later time make sure to notify about the item being updated

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L65

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L28

**Comment by rgocal** [comment]
Alright, im gonna play around with this. If i cant manage, il make some snibbets to share. This looks promising.

**Comment by rgocal** [comment]
Okey so my login code is very similar to to Google IO 2016 app. 
https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/util/AccountUtils.java

I use AccountUtils. GetProfileID on account email on material drawer and results are flawless. But it crashes when i implement everything for profile image

**Comment by mikepenz** [comment]
What crashes? Do you have a log?

**Comment by rgocal** [comment]
Il recreate the error next time i get on.

**Comment by rgocal** [comment]
After looking over the provided links, the problem was solved. Thankyou for your time!

**Comment by rgocal** [comment]
https://www.dropbox.com/s/x8sajalkur4krtk/Screenshot_1494460487.png?dl=0

preview

**Comment by rgocal** [comment]
Wait, haven a problem after resetting the app

Build version: 1.0 
Build date: 1979-11-30 00:00:00 
Current date: 2017-05-10 21:39:46 
Device: Xiaomi MI 5 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gsd.launcher.sapphyx/com.gsd.launcher.launcher3.settings.MainSettings}: java.lang.NullPointerException: uriString
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5458)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:475)
	at android.net.Uri$StringUri.<init>(Uri.java:465)
	at android.net.Uri.parse(Uri.java:437)
	at com.mikepenz.materialize.holder.ImageHolder.<init>(ImageHolder.java:29)
	at com.mikepenz.materialdrawer.holder.ImageHolder.<init>(ImageHolder.java:28)
	at com.mikepenz.materialdrawer.model.ProfileDrawerItem.withIcon(ProfileDrawerItem.java:78)
	at com.gsd.launcher.launcher3.settings.MainSettings.onCreate(MainSettings.java:115)
	at android.app.Activity.performCreate(Activity.java:6323)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
	... 9 more

**Comment by mikepenz** [comment]
@rgocal you probably try to set an empty string or null or a non valid url as image. Don't do this and you are good
