### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by inteist** [mikepenz/MaterialDrawer#1886]
I have just integrated the library into my app and although I have not had any issues while developing and testing, I get this on about half the devices in the pre launch report

```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:587)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:422)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
	at android.content.res.Resources.loadDrawable(Resources.java:2150)
	at android.content.res.Resources.getDrawable(Resources.java:715)
	at android.support.v7.widget.VectorEnabledTintResources.a(VectorEnabledTintResources.java:74)
	at android.support.v7.widget.AppCompatDrawableManager.a(AppCompatDrawableManager.java:437)
	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
	at android.support.v4.content.b.getDrawable(ContextCompat.java:374)
	at android.support.v7.widget.AppCompatDrawableManager.a(AppCompatDrawableManager.java:202)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
	at com.mikepenz.materialdrawer.a.d.a(ImageHolder.java:79)
	at com.mikepenz.materialize.b.c.a(ImageHolder.java:172)
	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:809)
```

I use android drawables (vector drawables which are simple and small icons) for the menu icons and a 120K jpeg for the drawer header background
with CENTER_CROP 
 .withHeaderBackgroundScaleType(ImageView.ScaleType.CENTER_CROP)

no other changes were made to the app and the problem is obviously coming from the drawer based on the stacktrace.

**P.S.** something I noticed also is that all the crashes are from devices running Android 4.4 (may not be related to OS though because HTC One running Android 4.4 does not crash. It can be more related to the fact that these devices have lower specs and hence crash earlier/more often.

I have confirmed that re-creation of the drawer is the culprit (if I statically setup it in one activity then no crashes occur)

I still do not understand how specific my case is but I am not doing anything too particular and I would think that the lib should readily support the usage of vector drawables for the menu (list) icons.

**Comment by mikepenz** [comment]
what's the resolution of that image?

**Comment by inteist** [comment]
Same as the image in the sample app ~500x280

**Comment by mikepenz** [comment]
as of your comment. How do you "re-create" the drawer? The drawer should only created ONCE

**Comment by mikepenz** [comment]
@inteist if you do not set the vectordrawables will it work? Just trying to figure out what seems to be the real problem

**Comment by mikepenz** [comment]
@inteist well that'S not a leak in that case. If you create an activity with a drawer the drawer exists in this activity. if you create a new activity and the drawer again, a different drawer exists in that activity (the previous activity still exists, so it is quite correct that it's still using memory) If you now have bigger drawables for every single activity it will build up RAM.
If you want to re-use these you should consider getting a bitmap of the image you want to set and re-use it across all activities you have.
There is nothing wrong about this behaviour as it is basically the expected behaviour of Android and the activities 

Yes I used leak canary already there are no leaks.

**Comment by inteist** [comment]
Hi, Mike

at the moment we only create the drawer in **1 activity** (home activity) in it's `onCreate` method.

When we did that, the pre-release checked out (no crashes there) but now the app is in production (since yesterday) and there are 3 crashes for 3 different users

The crash seems to happen in the setup header so it is not the material drawables. The image that we use is a JPEG and has the exact same resolution as the image from the sample app.

Everything points to some memory leak IMO. What can we do to help you find the issue so you/we can fix it?


```
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:835)
       at android.content.res.Resources.loadDrawable(Resources.java:2988)
       at android.content.res.Resources.getDrawable(Resources.java:1558)
       at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
       at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:437)
       at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
       at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
       at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
       at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
       at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:172)
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:809)
       REDACTED.setupAppDrawer(BaseActivity.java:325)
       REDACTED.onCreate(REDACTED:94)
       at android.app.Activity.performCreate(Activity.java:5372)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3877)
       at android.app.ActivityThread.access$800(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mikepenz** [comment]
@inteist well there a few possibilities here:
- image to big
- image to big for specific phones with no ram available
- your application has the memory leak
- you recreate the drawer more often (instead of just once)

the library itself was checked with leakCanary and it had no leaks. I can't control how devs include the library in the end though.

**Comment by inteist** [comment]
- image toO big
- image toO big for specific phones with no ram available
- your application has the memory leak
**addressing all the above**
no OOM crashes before we added the library and we use various image resources in the app, including on the fly transcoding of SVGs into bitmaps - never had OOM crash till now.

- you recreate the drawer more often (instead of just once)
no, just once in one activity's onCreate method but even if we did – and there probably are use cases when you'd want to do that (what about orientation change for example?), it should not crash with OOM. You have suggested caching the bitmap in one of the OOM threads, I think. I think it would be much more logical to cache it inside the library and reuse? The point of any library is to make dev's life easier and get rid of repetitive/boilerplate code and this IMO falls right into that category.

Thanks.

**Comment by mikepenz** [comment]
For orientation change it will anyways recreate the activity, so onCreate is called again. that's fine. It's still only created once for that instance of this activity. 

Which icon do you set? A vector? And that directly using the res int? 
Because that would describe the crash on 4.4 only. At least there is nothing special I do here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/holder/ImageHolder.java#L79

I just set your res of that image as imgeResource. 

Have you checked already if the ram is growing? Do you see after how long the crash is happening? because if it happens instantly on appStart than it is definitely no leak

**Comment by inteist** [comment]
> that's fine. It's still only created once for that instance of this activity.
as long as the previous activity is properly cleaned up

> Which icon do you set? 
Ok, sorry I double checked and we use a x2 of the sample image resolution – namely 1024x576. We tried the 512x288 but it was a bit blurry on the HD+ and UHD devices. Would that be enough to warrant this problem?

> A vector? 
NO

> And that directly using the res int?
YES

> Do you see after how long the crash is happening? 
No, we can't really reproduce this ourselves

>  if it happens instantly on appStart than it is definitely no leak
No, it *seems** to  happen with usage (we can't really reproduce this ourselves)

**Comment by mikepenz** [comment]
@inteist 1024x576 definitely can cause a crash on some phones. that's too big.  

You might consider a image loading library like `Glide` which can also set the image from the resources on a view, in a proper resolution.

**Comment by inteist** [comment]
`Glide` AFAIU is for **loading images from network**. It is an overkill and perhaps even not the right tool for that. 

If there are such issues with relatively not too big of resolutions, IMO it would make sense for the library to handle bitmap caching. I hope you'd consider implementing it. In the meantime, we will try caching the bitmap ourselves and see if that resolves this issue.

**Comment by mikepenz** [comment]
@inteist well `Glide` also handles local images which are too big, and automatically downscales this. 

I am 99% sure caching the full res image will not solve the problem. only downscaling the image will solve it. And that is clearly nothing the MaterialDrawer should do. 

The image is only decoded once during the creation, that's done by the system, because the header background is only set once too. So caching has affect. 

You really have to downsample and downscale that image. The resolution is what makes it so big in the memory and that will cause the problems sometimes on some phones...

**Comment by inteist** [comment]
@mikepenz, I see thanks. 

What is the best way to get the header bg image view size so we can calculate how the image should be downsampled? Since it is not visible, I assume it has not been laid out yet and all its measurements would be "0". 

Can you please advise how to properly downsample the BG image to be used in the header view. Thanks!

**Comment by mikepenz** [comment]
https://stackoverflow.com/a/17773344/325479
