### ISSUE TITLE
App crash while clicking the mini drawer

### ISSUE THREAD

**Issue by RITCHIEHuang** [mikepenz/MaterialDrawer#1928]
```java
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@ce8f496
                                                       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
                                                       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
                                                       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:537)
                                                       at android.widget.ImageView.onDraw(ImageView.java:1148)
                                                       at android.view.View.draw(View.java:15122)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:592)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14051)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4477)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                                       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                              at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                                       at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14056)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14051)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14051)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:14051)
                                                       at android.view.View.getDisplayList(View.java:14079)
                                                       at android.view.View.draw(View.java:14846)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                       at android.view.View.draw(View.java:15125)
                                                   	at android.view.View.updateDisplayListIfD
```

When I click on the mini Drawer, the app crash with this error Message.
The error message containes 

`at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)`

 I just feel confused about this problem.
Please help me, thanks.

**Comment by mikepenz** [comment]
@RITCHIEHuang the crash is not related to that layout or to this library. This line just shows up, because the stack trace contains the whole view hierarchy. (including that layout inbetween). 
As the top line of your StackTrace tells you, the crash happens because you are using a bitmap which is already recycled.
