### ISSUE TITLE
6.0.0.4-SNAPSHOT - Multiple ContainerDrawerItem dex files define

### ISSUE THREAD

**Issue by sosite** [mikepenz/MaterialDrawer#1949]
I want to use the new FastAdapter 3.0.0.4 version so I also need to bump this lib version. Unfortunately I can't build any 6.0.0.+ version of this lib:
```gradle
compile('com.mikepenz:materialdrawer:6.0.0.4-SNAPSHOT@aar') {
    transitive = true
}
```

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/model/ContainerDrawerItem;
Error:com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/model/ContainerDrawerItem;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:60)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':employer:transformDexArchiveWithDexMergerForDevDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/model/ContainerDrawerItem;
```

**Comment by mikepenz** [comment]
well looks like ithere are 2 different versions of the materialdrawer somewhere. have you cleaned your project?

**Comment by sosite** [comment]
I remember to make `Invalidate Caches / Restart...` but forgot to run simple `Clean Project`. Sorry for the problem :wink:

**Comment by mikepenz** [comment]
Awesome. So it works now?

**Comment by sosite** [comment]
Yea, it works 😄
