### ISSUE TITLE
Error while unselecting PrimaryItem

### ISSUE THREAD

**Issue by pranjal-joshi** [mikepenz/MaterialDrawer#1967]
Selecting first PrimaryItem works well, but then this happens while selecting the second PrimaryItem.
Error is ocuuring during unselect event of PrimaryItem.
P.S. Selection works fine if i use addStickyFooterItem.

Here is my logs:
```java
07-24 15:15:29.662 28265-28265/com.cyberfox.meetapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.cyberfox.meetapp, PID: 28265
                                                                      java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                          at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
                                                                          at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:322)
                                                                          at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
                                                                          at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3759)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3566)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3265)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1216)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2680)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                          at android.os.Handler.handleCallback(Handler.java:742)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/com.cyberfox.meetapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.cyberfox.meetapp-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515) 
                                                                          at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:322) 
                                                                          at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149) 
                                                                          at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3759) 
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3566) 
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3265) 
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1216) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336) 
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743) 
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586) 
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336) 
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273) 
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2680) 
                                                                          at android.view.View.layout(View.java:16653) 
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438) 
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198) 
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958) 
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134) 
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050) 
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860) 
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:672) 
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:608) 
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846) 
                                                                          at android.os.Handler.handleCallback(Handler.java:742) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5529) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: android.support.v4.animation.AnimatorCompatHelper
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 45 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-24 15:15:29.665 28265-28265/com.cyberfox.meetapp E/MQSEventManagerDelegate: failed to get MQSService.
```

**Comment by mikepenz** [comment]
Well you have a conflict of v25.4.0 of the support libraries and the latest 26.x ones I guess. 

```
Landroid/support/v4/animation/AnimatorCompatHelper
```

Which dependencies do you use in your project?

**Comment by pranjal-joshi** [comment]
First of all, Thanks for super prompt response! :+1: 
Please have a look at my dependencies & suggest fix.

`dependencies {
    // added by Pranjal

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile('com.mikepenz:materialdrawer:5.6.0@aar') {
        transitive = true
    }

    compile 'com.github.halysongoncalves:pugnotification:1.8.1'
    compile 'com.github.MAXDeliveryNG:slideview:1.0.1'
    compile 'com.futuremind.recyclerfastscroll:fastscroll:0.2.5'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.google.android.gms:play-services-places:11.0.2'
    compile 'com.google.android.gms:play-services-location:11.0.2'
    compile 'com.google.android.gms:play-services-maps:11.0.2'
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.android.support:design:25.0.0'
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha7'
    compile 'com.android.support:support-v4:26.+'
    testCompile 'junit:junit:4.12'
}
`

**Comment by pranjal-joshi** [comment]
Its working as you said after updating support library to 26.+
Thanks for this awesome library. I hope you will release many more! :)
`
compile 'com.android.support:cardview-v7:26.+'
compile 'com.android.support:design:26.+'
`
