### ISSUE TITLE
Resources$NotFoundException: String resource ID #0x1

### ISSUE THREAD

**Issue by lumyus** [mikepenz/MaterialDrawer#2014]
I face the following issue only on certain devices and certain flavors, but not all. 
The issue is somewhere related with this line `crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT); `
Meaning that whenever I comment this line out, the app doesnt crash anymore. However the menu is not being showed of course. I am using the CrossfadeDrawerLayoutActvitiy and adapted it to my needs. Any idea whats going on? Thanks!

`FATAL EXCEPTION: main Process: com.flyingmanta.doubledog, PID: 1847 android.content.res.Resources$NotFoundException: String resource ID #0x1 at android.content.res.Resources.getText(Resources.java:1468) at android.widget.TextView.setText(TextView.java:5051) at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:59) at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:86) at com.mikepenz.materialdrawer.model.MiniDrawerItem.bindView(MiniDrawerItem.java:153) at com.mikepenz.materialdrawer.model.MiniDrawerItem.bindView(MiniDrawerItem.java:24) at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onBindViewHolder(FastAdapter.java:2006) at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:655) at com.mikepenz.fastadapter.AbstractAdapter.onBindViewHolder(AbstractAdapter.java:151) at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6509) at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5452) at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5718) at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5557) at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5553) at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229) at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556) at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516) at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608) at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693) at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410) at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742) at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731) at android.widget.LinearLayout.onLayout(LinearLayout.java:1496) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742) at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731) at android.widget.LinearLayout.onLayout(LinearLayout.java:1496) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814) at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814) at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1196) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344) at android.widget.FrameLayout.onLayout(FrameLayout.java:281) at android.view.View.layout(View.java:17939) at android.view.ViewGroup.layout(ViewGroup.java:5814)`

Furthermore I am using the following code:

```
Drawable drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_person);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem profileItem = new PrimaryDrawerItem()
                .withName("Profile")
                .withIcon(drawable);

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_settings);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem settingsItem = new PrimaryDrawerItem()
                .withName("Settings")
                .withIcon(drawable);

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_notifications);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem notificationItem = new PrimaryDrawerItem()
                .withName("Notifications")
                .withIcon(drawable);

        if(user.getPendingFollowerCount() > 0){
            notificationItem.withBadge(user.getPendingFollowerCount())
                    .withBadgeStyle(new BadgeStyle(ResourcesCompat.getColor(getResources(), R.color.accent, null),
                            ResourcesCompat.getColor(getResources(), R.color.accent, null)));
        }

        drawable = ContextCompat.getDrawable(this,R.drawable.ic_action_share);
// Wrap the drawable so that future tinting calls work
// on pre-v21 devices. Always use the returned drawable.
        drawable = DrawableCompat.wrap(drawable);
// We can now set a tint
        DrawableCompat.setTint(drawable, ContextCompat.getColor(this, R.color.black));

        PrimaryDrawerItem shareItem = new PrimaryDrawerItem()
                .withName("Share")
                .withIcon(drawable);

        Log.d("Menu", "Icons set up");

    result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withSelectedItem(-1)
                .withHasStableIds(true)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withDrawerWidthDp(72)
                .withGenerateMiniDrawer(true)
                .addDrawerItems(
                        settingsItem.withIdentifier(0),
                        profileItem.withIdentifier(1),
                        notificationItem.withIdentifier(2),
                        shareItem.withIdentifier(3)
                        ) // add the items we want to use with our Drawer
            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                    Intent intent;
                    switch(position) {
                        case 0:
                            intent = new Intent(MainActivity.this, SettingsActivity.class);
                            startActivity(intent);
                            break;
                        case 1:
                            intent = new Intent(MainActivity.this, ProfileActivity.class);
                            intent.putExtra( "user", ((DoubleDogApplication)getApplication()).getLoggedInUser());
                            startActivity(intent);
                            break;
                        case 2:
                            intent = new Intent(MainActivity.this, NotificationActivity.class);
                            startActivity(intent);
                            break;
                        case 3:
                            shareWithFriends();
                            break;
                        default:
                    }

                    return false;
                }
            })
            .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                .build();


        Log.d("Menu", "Menu built");

    //get the CrossfadeDrawerLayout which will be used as alternative DrawerLayout for the Drawer
    //the CrossfadeDrawerLayout library can be found here: https://github.com/mikepenz/CrossfadeDrawerLayout
    crossfadeDrawerLayout = (CrossfadeDrawerLayout) result.getDrawerLayout();

    //define maxDrawerWidth
        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(this));
    //add second view (which is the miniDrawer)
    final MiniDrawer miniResult = result.getMiniDrawer();
    //build the view for the MiniDrawer
    View view = miniResult.build(this);
    //set the background of the MiniDrawer as this would be transparent
        view.setBackgroundColor(ContextCompat.getColor(this, R.color.white));
        //we do not have the MiniDrawer view during CrossfadeDrawerLayout creation so we will add it here
        crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);

    //define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new ICrossfader() {
        @Override
        public void crossfade() {
            boolean isFaded = isCrossfaded();
            crossfadeDrawerLayout.crossfade(400);

            //only close the drawer if we were already faded and want to close it now
            if (isFaded) {
                result.getDrawerLayout().closeDrawer(GravityCompat.START);
            }
        }

        @Override
        public boolean isCrossfaded() {
            return crossfadeDrawerLayout.isCrossfaded();
        }
    });
        Log.d("Menu", "MiniMenu built");
        isMenuCreated = true;

```

**Comment by lumyus** [comment]
I was creating the menu inside the onReceive method of a broadcaster. This was causing the crash. Cheers and thanks for the great library.
