### ISSUE TITLE
Crash when clicking the down arrow on header on Samsung S7 Edge

### ISSUE THREAD

**Issue by AkshayPathak** [mikepenz/MaterialDrawer#2042]
Hi Mike,

I seem to be getting a crash when I click the mini down arrow on the header to view all the profiles. I tested this on two Samsung S7 Edge devices and both crashed. The crash did not occur on Nexus 4, and Nexus 7. Below is the stacktrace of the crash.

```
FATAL EXCEPTION: 
java.lang.AbstractMethodError: abstract method "boolean com.mikepenz.fastadapter.IItem.failedToRecycle(android.support.v7.widget.RecyclerView$ViewHolder)"
 at com.mikepenz.fastadapter.FastAdapter$OnBindViewHolderListenerImpl.onFailedToRecycleView(FastAdapter.java:2041)
 at com.mikepenz.fastadapter.FastAdapter.onFailedToRecycleView(FastAdapter.java:673)
 at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5753)
 at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8462)
 at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8447)
 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:818)
 at android.view.View.layout(View.java:18793)
 at android.view.ViewGroup.layout(ViewGroup.java:5952)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2625)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2341)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1493)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7040)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
 at android.view.Choreographer.doCallbacks(Choreographer.java:702)
 at android.view.Choreographer.doFrame(Choreographer.java:638)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6688)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by mikepenz** [comment]
@AkshayPathak does this happen in the sample app too?

**Comment by AkshayPathak** [comment]
No, this does not seem to happen on the sample app. I really don't have any ideas as to what might be causing this. My implementation is pretty standard to your samples as well.

**Comment by mikepenz** [comment]
can you please show some code? 
Which libs versions do you use? 
Which support libs version? 
which build tools and so on?

**Comment by mikepenz** [comment]
Please report back

**Comment by AkshayPathak** [comment]
@mikepenz, this issue got resolved after updating the fastadapter to your latest release (V3.0.5). Thank you for your support. Great library! Keep up the good work.
