### ISSUE TITLE
Drawer crashes on rotation after call switchDrawerContent

### ISSUE THREAD

**Issue by Andoctorey** [mikepenz/MaterialDrawer#2073]
We don't use AccountHeader in project.
1. Create drawer
2. Rotate screen 
All good

1. Create drawer
2. Switch drawer content
3. Rotate screen 
Crash:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.AccountHeader.toggleSelectionList(android.content.Context)' on a null object reference
                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754)
                                         at android.app.ActivityThread.-wrap18(Unknown Source:0)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                         at android.os.Looper.loop(Looper.java:164)
                                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.AccountHeader.toggleSelectionList(android.content.Context)' on a null object reference
                                         at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1556)
                                         at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1343)
                                         at ***.setupDrawer(MainActivity.java:565)
                                         at ***.MainActivity.onCreate(MainActivity.java:409)
                                         at android.app.Activity.performCreate(Activity.java:6975)
                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754) 
                                         at android.app.ActivityThread.-wrap18(Unknown Source:0) 
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                         at android.os.Looper.loop(Looper.java:164) 
                                         at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by mikepenz** [comment]
@Andoctorey is this happening in the sample application? if not there must be an issue of the way how you create the drawer.
are you not re-creating the drawer in `onCreate`?

**Comment by Andoctorey** [comment]
I'm recreating activity withSavedInstance method. Just checked - without it app is not crashing. 
But I found quick fix - adding  drawer.resetDrawerContent() to onSaveInstanceState: 
```    
   @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        if (drawer != null) {
            if (drawer.switchedDrawerContent()) {
                drawer.resetDrawerContent();
            }
            drawer.saveInstanceState(outState);
        }
        if (crossFader != null) crossFader.saveInstanceState(outState);
    }
```
