### ISSUE TITLE
Can't use MaterialDrawer with FastAdapter 3.0.0

### ISSUE THREAD

**Issue by Tarik02** [mikepenz/MaterialDrawer#2086]
I want to use MaterialDrawer and FastAdapter 3 together but i get this error:
```
10-30 20:55:11.929 20474-20474/com.agropostavka.agropostavka E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.agropostavka.agropostavka, PID: 20474
                                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/fastadapter/adapters/HeaderAdapter;
                                                                                   at com.mikepenz.materialdrawer.DrawerBuilder.<init>(DrawerBuilder.java:869)
                                                                                   at co.zsmb.materialdrawerkt.builders.DrawerBuilderKt.<init>(DrawerBuilderKt.kt:49)
                                                                                   at co.zsmb.materialdrawerkt.builders.DrawerBuilderKtKt.drawer(DrawerBuilderKt.kt:28)
                                                                                   at com.agropostavka.agropostavka.activity.MainActivity.onCreate(MainActivity.kt:45)
                                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.fastadapter.adapters.HeaderAdapter" on path: DexPathList[[zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/base.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_dependencies_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_0_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_1_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_2_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_3_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_4_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_5_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_6_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_7_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_8_apk.apk", zip file "/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.agropostavka.agropostavka-GbodBhhBCkkrUFHoTI4-Ag==/lib/x86, /system/lib, /system/vendor/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                   at com.mikepenz.materialdrawer.DrawerBuilder.<init>(DrawerBuilder.java:869) 
                                                                                   at co.zsmb.materialdrawerkt.builders.DrawerBuilderKt.<init>(DrawerBuilderKt.kt:49) 
                                                                                   at co.zsmb.materialdrawerkt.builders.DrawerBuilderKtKt.drawer(DrawerBuilderKt.kt:28) 
                                                                                   at com.agropostavka.agropostavka.activity.MainActivity.onCreate(MainActivity.kt:45) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

Dependencies:
```
compile('com.mikepenz:materialdrawer:5.9.5@aar') {
	transitive = true
	exclude group: 'com.android.support'
}
implementation 'com.mikepenz:fastadapter:3.0.0@aar'
```

**Comment by mikepenz** [comment]
@Tarik02 there will be a v6 of the MaterialDrawer within this week. 

(currently there is just a SNAPSHOT release of the MaterialDrawer you could use)

**Comment by Tarik02** [comment]
Thanks!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/releases/tag/v6.0.0
