### ISSUE TITLE
Issue in adding the hamburger icon

### ISSUE THREAD

**Issue by AliRezaBeitari** [mikepenz/MaterialDrawer#2096]
**MainActivity.java**

```
package com.beitari.test;

import android.graphics.Color;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.Toolbar;
import android.view.View;
import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);

        setContentView(R.layout.activity_main);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        toolbar.setTitle(R.string.app_name);
        toolbar.setTitleTextColor(Color.WHITE);

        setSupportActionBar(toolbar);

        Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withSavedInstance(savedInstanceState)
                .build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
    }
}
```

**activity_main.xml**

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.beitari.shergoo.MainActivity">

    <android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <android.support.design.widget.AppBarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layoutDirection="rtl"
                    android:textDirection="rtl"
                    android:background="@color/primary"
                    android:theme="@style/AppTheme">

                </android.support.v7.widget.Toolbar>

            </android.support.design.widget.AppBarLayout>

        </LinearLayout>
    </android.support.design.widget.CoordinatorLayout>

</android.support.constraint.ConstraintLayout>
```

But I get this error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beitari.test/com.beitari.test.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
	at com.beitari.test.MainActivity.onCreate(MainActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:6662)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
	at android.app.ActivityThread.-wrap12(ActivityThread.java) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loop(Looper.java:154) 
	at android.app.ActivityThread.main(ActivityThread.java:6077) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by mikepenz** [comment]
Pass the toolbar to the drawer

**Comment by AliRezaBeitari** [comment]
@mikepenz even with `.withToolbar(toolbar)` it still has error!

**Comment by mikepenz** [comment]
@AliRezaBeitari make sure `Toolbar` is not null

Check out the `DrawerActivity` in the sample. It works properly:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L102

**Comment by Kvaibhav01** [comment]
@mikepenz, I face the same error. The logcat error of @AliRezaBeitari and me is same. Here is my code:

```
Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new SecondaryDrawerItem().withName(R.string.drawer_item_settings)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        switch (position)
                        {
                            case 1:  Uri uri = Uri.parse( "https://github.com/Kvaibhav01/Quake-Report" );
                                startActivity( new Intent( Intent.ACTION_VIEW, uri ) );

                            case 2: Uri uri2 = Uri.parse( "https://play.google.com/store/apps/developer?id=Vaibhav+Khulbe" );
                                startActivity( new Intent( Intent.ACTION_VIEW, uri2 ) );
                        }
                        return true;
                    }
                })
                .build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
Android Studio displays a warning in `setDisplayHomeAsUpEnabled()` method of null pointer exception. Due to which the app doesn't starts. How to resolve this? I'm not sure what you mean by:

> make sure Toolbar is not null

**Comment by mikepenz** [comment]
@AliRezaBeitari don't forget you set the `supportActionBar`

```java
Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
toolbar.setTitle(R.string.app_name);
toolbar.setTitleTextColor(Color.WHITE);

setSupportActionBar(toolbar);
```

**Comment by Kvaibhav01** [comment]
That works! 😄

**Comment by Kvaibhav01** [comment]
The app runs but the hamburger icon appears for a moment (when the app launches) but then it disappears. I can only see the menu options icon that I created earlier on the action bar. I have a list which displays like this in the screenshot:

![screenshot_1511032082](https://user-images.githubusercontent.com/11731837/32983940-bcc16c60-ccc2-11e7-87e9-4864443c67d9.png)


I've already added the required [code for hamburger icon](https://github.com/mikepenz/MaterialDrawer#code---show-the-hamburger-icon). It looks as if the hamburger icon is shifted behind my list. Here's my code for Material Drawer library:

```
/*Implement navigation drawer*/
        toolbar = (Toolbar) findViewById(R.id.toolbarMain);
        toolbar.setTitle("Quake List");
        setSupportActionBar(toolbar);
        new DrawerBuilder().withActivity(this).build();

        // Create the AccountHeader
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        new ProfileDrawerItem().withName("Vaibhav Khulbe").withEmail("khulbevaibhavdev@gmail.com").withIcon(getResources().getDrawable(R.drawable.profile))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();

        //if you want to update the items at a later time it is recommended to keep it in a variable
        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1).withName(R.string.drawer_item_home);
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withIdentifier(2).withName(R.string.drawer_item_settings);

        //create the drawer and remember the `Drawer` result object

        Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withActionBarDrawerToggle(true)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new SecondaryDrawerItem().withName(R.string.drawer_item_settings)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        switch (position)
                        {
                            case 1:  Uri uri = Uri.parse( "https://github.com/Kvaibhav01/Quake-Report" );
                                startActivity( new Intent( Intent.ACTION_VIEW, uri ) );

                            case 2: Uri uri2 = Uri.parse( "https://play.google.com/store/apps/developer?id=Vaibhav+Khulbe" );
                                startActivity( new Intent( Intent.ACTION_VIEW, uri2 ) );
                        }
                        return true;
                    }
                })
                .build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
