### ISSUE TITLE
App crashes building the AccountHeaderBuilder

### ISSUE THREAD

**Issue by oscargrgm** [mikepenz/MaterialDrawer#2144]
## About this issue

I want to add an `AccountHeader` to my `Drawer` but when I try to build my `AccountHeaderBuilder` the app always crash. The stack trace is:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.example/com.android.example.activities.MainActivity}: 
    android.content.res.Resources$NotFoundException: Resource ID #0xffe3001b
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5443)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0xffe3001b
    at android.content.res.Resources.getValue(Resources.java:1351)
    at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:330)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
    at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
    at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
    at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
    at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:79)
    at com.mikepenz.materialize.holder.ImageHolder.applyTo(ImageHolder.java:172)
    at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:813)
    at com.android.example.activities.MainActivity.initDrawer(MainActivity.java:424)
    at android.app.Activity.performCreate(Activity.java:6245)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5443) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```
Debugging I've found that in the library class `ImageHolder`, method `applyTo(ImageView imageView, String tag)` is setting an `IconRes` to the `ImageView`, but the method `getIconRes() `(line 79) is returning an id that is not founded by the system.

The resource is looking for is **#0xffe3001b**.

I've tried to set the theme to one of your MaterialDrawer's list, but it is not working.

The activity extends `AppCompatActivity` and my code is the next:
```
DrawerBuilder drawerBuilder = new DrawerBuilder(this);
AccountHeaderBuilder headerBuilder = new AccountHeaderBuilder()
    .withActivity(this)
    .withCompactStyle(true)
    .withProfileImageVisible(false)
    .withHeaderBackground(R.color.primaryDark)
    .withTextColor(R.color.white);

IProfile emptyProfile = new ProfileDrawerItem()
    .withName("Óscar")
    .withEmail("oscar@example.com");

headerBuilder.addProfiles(emptyProfile);
drawerBuilder.withAccountHeader(headerBuilder.build());

Drawer drawer = drawerBuilder.build();
```
Any clue?
## Details
- [x] Used library version: 
    - iconics-core:3.0.0
    - materialdrawer:6.0.2
- [x] Used support library version: 26.0.0
- [x] Used gradle build tools version: 3.0.1

**Comment by mikepenz** [comment]
@oscargrgm the `MaterialDrawer` depends on the `support libraries` 27. you might have a support lib conflict.


Try to make sure you don't have conflicts with a resolution strategy:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L83

**Comment by oscargrgm** [comment]
I've tried upgrading the `compileSdkVersion` to 27 and the `support libraries` to 27.0.2, including the `resolutionStrategy` as you said and it's still not working. Maybe I have to add another library to my Gradle? Because it seems like some resource is not being reached or found.

In the next class:
materialdrawer-6.0.2-sources.jar **>** com **>** mikepenz **>** materialdrawer **>** holder **>** ImageHolder
```
/**
* sets an existing image to the imageView
*
* @param imageView
* @param tag       used to identify imageViews and define different placeholders
* @return true if an image was set
*/
@Override
public boolean applyTo(ImageView imageView, String tag) {
    if (getUri() != null) {
        boolean consumed = DrawerImageLoader.getInstance().setImage(imageView, getUri(), tag);
        if (!consumed) {
            imageView.setImageURI(getUri());
        }
    } else if (getIcon() != null) {
        imageView.setImageDrawable(getIcon());
    } else if (getBitmap() != null) {
        imageView.setImageBitmap(getBitmap());
    } else if (getIconRes() != -1) {
        imageView.setImageResource(getIconRes());
    } else if (mIIcon != null) {
        imageView.setImageDrawable(new IconicsDrawable(imageView.getContext(), mIIcon).actionBar());
    } else {
        imageView.setImageBitmap(null);
        return false;
    }
    return true;
}
```
The method `imageView.setImageResourcfe(getIconRes());` is calling:

materialize-1.1.2-sources.jar **>** com **>** mikepenz **>** materialize **>** holder **>** ImageHolder
```
/**
* sets an existing image to the imageView
*
* @param imageView
* @param tag       used to identify imageViews and define different placeholders
* @return true if an image was set
*/
public boolean applyTo(ImageView imageView, String tag) {
    if (mUri != null) {
        imageView.setImageURI(mUri);
        /*
        if ("http".equals(mUri.getScheme()) || "https".equals(mUri.getScheme())) {
            DrawerImageLoader.getInstance().setImage(imageView, mUri, tag);
        } else {
        }
        */
    } else if (mIcon != null) {
        imageView.setImageDrawable(mIcon);
    } else if (mBitmap != null) {
        imageView.setImageBitmap(mBitmap);
    } else if (mIconRes != -1) {
        imageView.setImageResource(mIconRes);
    } else {
        imageView.setImageBitmap(null);
        return false;
    }
    return true;
}
```
Here, the variable `int mIconRes` is -1 by default and no one is setting it to another different value, and I think this is causing the `Resources$NotFoundException: Resource ID #0xffe3001b`. It also didn't work before, when I did use the version `'com.mikepenz:materialdrawer:5.8.0@aar'`

**Comment by mikepenz** [comment]
@oscargrgm but `imageView.setImageResource(getIconRes());` will only be called if `iconRes` != `-1` 

did you do a clean? can you reproduce this in the sample?

**Comment by oscargrgm** [comment]
Ok, digging in the code I've seen I wrote this line:

`accountHeaderBuilder.withHeaderBackground(R.color.primaryColor);`

and this method only works with a `Drawable` identifier, a `Drawable` or an `ImageHolder`, so it is crashing trying to find the `Resource` with the `Color` id.

My fault. I've changed it and now it works perfectly. Sorry and thank you very much for your help :)
