### ISSUE TITLE
NullPointerException on calculateProfiles, updateHeaderAndList, addProfiles 

### ISSUE THREAD

**Issue by rishirD** [mikepenz/MaterialDrawer#2193]
## About this issue

- NullPointerException on calculateProfiles, updateHeaderAndList, addProfiles on android version 4.4.4 and below.

## Details

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.rishideep.wallon/xyz.rishideep.wallon.ACTIVITIES.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2285)
       at android.app.ActivityThread.access$800(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5077)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```
Caused by java.lang.NullPointerException
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.calculateProfiles(AccountHeaderBuilder.java:900)
       at com.mikepenz.materialdrawer.AccountHeaderBuilder.updateHeaderAndList(AccountHeaderBuilder.java:1484)
       at com.mikepenz.materialdrawer.AccountHeader.addProfiles(AccountHeader.java:275)
       at xyz.rishideep.wallon.ACTIVITIES.MainActivity.updateDrawerItems(MainActivity.java:587)
       at xyz.rishideep.wallon.ACTIVITIES.MainActivity.onCreate(MainActivity.java:176)
       at android.app.Activity.performCreate(Activity.java:5395)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2285)
       at android.app.ActivityThread.access$800(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5077)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```java
private void updateDrawerItems() {
        drawerHeader.clear();

        if (!AuthManager.getInstance().isAuthorized()) {
            drawerHeader.addProfiles(drawerItemAddAccount, profileDefault);
        } else {
            IProfile profile;
            if (AuthManager.getInstance().getAvatarPath() != null) {
                profile = new ProfileDrawerItem().withName(AuthManager.getInstance().getUsername()).withEmail(AuthManager.getInstance().getEmail()).withIcon(AuthManager.getInstance().getAvatarPath());
            } else {
                profile = profileDefault;
            }
            drawerHeader.addProfiles(drawerItemViewProfile, drawerItemLogout, profile);
        }
    }
```

**Comment by mikepenz** [comment]
@rishirD which version of the library? is it reproducible in the sample? 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L900

A nullpointer here is only possible if you async modify the accounts while it is created.

**Comment by rishirD** [comment]
@mikepenz 
version - 6.0.0@aar
reproducible in the sample? - didn't check that.
This works fine for all the versions of android except v4.4.4 and below.
The app crashes with the above stack trace.

**Comment by mikepenz** [comment]
@rishirD please check with the sample app. If it does not crash the error is somewhere in your code. 

Tested on a v4.4.4 device and the sample works without any issues.

Most likely it is some race condition in which you modify the profiles even though it is currently setting up the header.
Make also sure you do not alter the list of the profiles (which is provided the `AccountHeaderBuilder.withProfiles`) or clear that list at the same time. 

Also make sure all operations on the header or UI happen on the UI thread. (which is very important for views)
