### ISSUE TITLE
Unfortunately, Quizy has stopped + Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x1

### ISSUE THREAD

**Issue by Malscythe** [mikepenz/MaterialDrawer#2198]
Every time i open the app and start the quiz the error comes up
my MainActivity.java
```
package com.example.administrator.quizy;

import android.content.DialogInterface;
import android.content.Intent;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import org.w3c.dom.Text;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Random;

public class MainActivity extends AppCompatActivity {

    private TextView countLabel;
    private TextView questionLabel;
    private Button answerBtn1;
    private Button answerBtn2;
    private Button answerBtn3;
    private Button answerBtn4;

    private String rightAnswer;
    private int rightAnswerCount = 0;
    private int quizCount = 1;
    static final private int QUIZ_COUNT = 22;

    ArrayList<ArrayList<String>> quizArray = new ArrayList<>();

    String quizData[][] = {
            // {"Question", "RightAnswer", "Choice1", "Choice2", "Choice3"}
            {"if Logx(1/B) = -3/2, then x is equal to","4", "-4", "4", "1/4", "10"},
            {"20% of 2 is equal to", "0.4", "20", "4", "0.4", "0.04"},
            {"if Log 4(x) = 12, then log 2(x/4)is equal to", "22", "11", "48", "-12", "22"},
            {"The population of a country increased by an avrage of 2% per year from 2000 to 2003. If the population of this country was 2,000,000 on december 31,2003, then the population of this country on January 1,2000, to the nearest thousand would have been", "1,846,000", "1,846,000", "1,852,000", "1,000,000", "1,500,000"},
            {"f is a quadtratic function whose graph is a parabola opening upward and has avertex on the x-axis. The graph of the new function g defined bt g(x) =2 - f(x-5) has a range of defined by interval", "(-infinity,2]", "[-5,+infinity)", "[2,+infinity)", "(-infinity,2]", "(-infinity,0]"},
            {"f is a function such that f(x) < 0. The graph of the new function g defined by g(x)= | f(x)| is a reflection of the group of f", "on the x axis", "on the y-axis", "on the x-axis", "on the line y = x", "on the line y = -x"},
            {"if the graph of y = f(x) is transformed into the graph of 2y - 6 = -4 f(x - 3), point (a , b) on the graph of y = f(x) becomes point(A,B) on the graph of 2y - 6 = -4 f(x - 3) where A and B are given by", "A = a + 3,B = -2b + 3", "A = a - 3,B = b", "A = a -3,B = b", "A = a + 3,B = -2b","A = a + 3,B = -2b + 3"},
            {"When a parabola represented by the equation y - 2x 2 = 8x + 5 is translated 3 units to the left and 2 units up, the new parabola has its vertex at", "(-5,-1)", "(-5,-1)", "(-5,-5)", "(-1,-3)", "(-2,-3)"},
            {"the graphs of the two linear equations ax + by = c and bx - ay = c, where a,b and c are all not equal to zero", "Answer: D. Perpendicular", " are parallel", "B.intersect at one point", "C.intersect at two points", "D.parallel"},
            {"The graphs of the two equations y = a x 2 + bx + c and y = A x 2 + Bx +C, such that a and A have different signs and that the quantities b 2 - 4a c and B 2- 4A C are both negative,", "Answer: C.none of the above", " intersect at two points", "B.intersect at one point", "C.do not intersect", "D.none of the above"},
            {"For x greater than or equal to zero and kess than or equal to 2 pi,sin x and cos x are both decreasing on the intervals","Answer: B. (pi/2 , pi)", "  (0 , pi/2)", "B. (pi/2 , pi)", "C. (pi , 3 pi / 2)", "D. (3 pi / 2 , 2 pi)"},
            {"The three solutions of the equation f(x) = 0 are -2, 0, and 3. Therefore, the three solutions of the equation f(x - 2) = 0 are", "Answer: D. 0, 2 and 5", "  - 4, -2, and 1", "B. -2, 0 and 3", "C. 4, 2, and 5", "D. 0, 2 and 5"},
            {"The three solutions of the equation f(x) = 0 are - 4, 8, and 11. Therefore, the three solutions of the equation f(2 x) = 0 are", "Answer:   - 2, 4, and 11/2", "  - 2, 4, and 11/2", "B. - 8, 16 and 22", "C. - 4, 8, and 11", "D. 2, 19 / 2 and 7 / 2"},
            {"A school committee consists of 2 teachers and 4 students. The number of different committees that can be formed from 5 teachers and 10 students is", "Answer: C. 2100", "  10", "B. 15", "C. 2100", "D. 8"},
            {"Five different books (A, B, C, D and E) are to be arranged on a shelf. Books C and D are to be arranged first and second starting from the right of the shelf. The number of different orders in which books A, B and E may be arranged is", "Answer: B. 3!", "  5!", "B. 3!", "C. 2!", "D. 3! * 2!"},
            {"The mean of a data set is equal to 10 and its standard deviation is equal to 1. If we add 5 to each data value, then the mean and standard deviation become", "Answer: C. mean = 15 , standard deviation = 1", "  mean = 15 , standard deviation = 6", "B. mean = 10 , standard deviation = 6", "C. mean = 15 , standard deviation = 1", "D. mean = 10 , standard deviation = 1"},
            {"The exam scores of all 500 students were recorded and it was determined that these scores were normally distributed. If Jane's score is 0.8 standard deviation above the mean, then how many, to the nearest unit, students scored above Jane?", "Answer: D. 106", "  394", "B. 250", "C. 400", "D. 106"},
            {"If f(x) is an odd function, then | f(x) | is", "Answer: B. an even function", "  an odd function", "B. an even function", "C. neither odd nor even", "D. even and odd"},
            {"The period of | sin (3x) | is", "Answer: C. pi / 3", "  2 pi", "B. 2 pi / 3", "C. pi / 3", "D. 3 pi"},
            {"When a metallic ball bearing is placed inside a cylindrical container, of radius 2 cm, the height of the water, inside the container, increases by 0.6 cm. The radius, to the nearest tenth of a centimeter, of the ball bearing is", "Answer: B. 1.2 cm", "  1 cm", "B. 1.2 cm", "C. 2 cm", "D. 0.6 cm"},
            {"The period of 2 sin x cos x is", "Answer: D. pi", "  4 pi 2", "B. 2 pi", "C. 4 pi", "D. pi"},
            {"The probability that an electronic device produced by a company does not function properly is equal to 0.1. If 10 devices are bought, then the probability, to the nearest thousandth, that 7 devices function properly is", "Answer:   0.057", "  0.057", "B. 0.478", "C. 0.001", "D. 0"}

    };
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        countLabel = (TextView) findViewById(R.id.countLabel);
        questionLabel = (TextView) findViewById(R.id.questionLabel);
        answerBtn1 = (Button) findViewById(R.id.answerBtn1);
        answerBtn1 = (Button) findViewById(R.id.answerBtn2);
        answerBtn1 = (Button) findViewById(R.id.answerBtn3);
        answerBtn1 = (Button) findViewById(R.id.answerBtn4);

        int quizCategory = getIntent().getIntExtra("QUIZ_CATEGORY", 0);

        Log.v("CATEGORY_TAG", quizCategory + "");

        //Create quizArray from quizData

        for (int i = 0; i < quizData.length; i++) {

            ArrayList<String> tmpArray = new ArrayList<>();
            tmpArray.add(quizData[i][0]); //Question
            tmpArray.add(quizData[i][1]); //Right Answer
            tmpArray.add(quizData[i][2]); //Choice1
            tmpArray.add(quizData[i][3]); //Choice2
            tmpArray.add(quizData[i][4]); //Choice3

            quizArray.add(tmpArray);
        }
        {
            showNextQuiz();
        }
    }

    public void showNextQuiz() {

        Random random = new Random();
        int randomNum = random.nextInt(quizArray.size());

        countLabel.setText(quizCount);

        ArrayList<String> quiz = quizArray.get(randomNum);

        questionLabel.setText(quiz.get(0));
        rightAnswer = quiz.get(1);

        quiz.remove(0);
        Collections.shuffle(quiz);

        answerBtn1.setText(quiz.get(0));
        answerBtn2.setText(quiz.get(1));
        answerBtn3.setText(quiz.get(2));
        answerBtn4.setText(quiz.get(3));

        quizArray.remove(randomNum);

    }

    public void checkAnswer(View view) {

        Button answerBtn = (Button) findViewById(view.getId());
        String btnText = answerBtn.getText().toString();

        String alertTitle;

        if (btnText.equals(rightAnswer)) {

            alertTitle = "Correct!";
            rightAnswerCount++;
        } else {

            alertTitle = "Wrong...";
        }

        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setTitle(alertTitle);
        builder.setMessage("Answer : " + rightAnswer);
        builder.setPositiveButton("OK", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                if(quizCount == QUIZ_COUNT) {
                    Intent intent = new Intent(getApplicationContext(), result.class);
                    intent.putExtra("RIGHT_ANSWER_COUNT", rightAnswerCount);
                    startActivity(intent);
            } else {
                    quizCount++;
                    showNextQuiz();
                }
        }
    });

    }
        }
```
result.java
```
package com.example.administrator.quizy;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

public class result extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_result);

        TextView resultLabel = (TextView)findViewById(R.id.resultLabel);
        TextView totalScoreLabel = (TextView)findViewById(R.id.totalResultLabel);

        int score = getIntent().getIntExtra("RIGHT_ANSWER_COUNT", 0);

        SharedPreferences settings = getSharedPreferences("quizApp", Context.MODE_PRIVATE);
        int totalScore = settings.getInt("totalScore", 0);
        totalScore += score;


        resultLabel.setText(score + " / 22");
        totalScoreLabel.setText("Total Score : " + totalScore);

        SharedPreferences.Editor editor = settings.edit();
        editor.putInt("totalScore", totalScore);
        editor.commit();

    }

    public void returnTop(View view) {
        Intent intent = new Intent(getApplicationContext(), StartActivity.class);
        startActivity(intent);
        }

    }
```
StartActivity.java
```
package com.example.administrator.quizy;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

public class StartActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_start);
    }

    public void startQuiz(View view) {

        int quizCategory = 0;

        Intent intent = new Intent(getApplicationContext(), MainActivity.class);
        intent.putExtra("QUIZ_CATEGORY", quizCategory);
        startActivity(intent);
        }
    }
```
Logcat
```
02-05 02:42:51.532 5294-5294/? E/Zygote: MountEmulatedStorage()
02-05 02:42:51.532 5294-5294/? E/Zygote: v2
02-05 02:42:51.532 5294-5294/? I/libpersona: KNOX_SDCARD checking this for 10271
02-05 02:42:51.532 5294-5294/? I/libpersona: KNOX_SDCARD not a persona
02-05 02:42:51.537 5294-5294/? I/SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-N910C_5.1.1_0032
02-05 02:42:51.537 5294-5294/? E/Zygote: accessInfo : 0
02-05 02:42:51.537 5294-5294/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
02-05 02:42:51.537 5294-5294/? I/art: Late-enabling -Xcheck:jni
02-05 02:42:51.707 5294-5294/com.example.administrator.quizy I/InstantRun: starting instant run server: is main process
02-05 02:42:51.777 5294-5294/com.example.administrator.quizy D/SecWifiDisplayUtil: Metadata value : none
02-05 02:42:51.797 5294-5294/com.example.administrator.quizy W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-05 02:42:51.842 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* installDecor mIsFloating : false
02-05 02:42:51.842 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* installDecor flags : -2139029248
02-05 02:42:51.967 5294-5315/com.example.administrator.quizy D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-05 02:42:51.972 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
02-05 02:42:51.972 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* isFloatingMenuEnabled return false
02-05 02:42:51.992 5294-5294/com.example.administrator.quizy D/SRIB_DCS: log_dcs ThreadedRenderer::initialize entered! 
02-05 02:42:51.997 5294-5315/com.example.administrator.quizy I/OpenGLRenderer: Initialized EGL, version 1.4
02-05 02:42:52.007 5294-5315/com.example.administrator.quizy I/OpenGLRenderer: HWUI protection enabled for context ,  &this =0xae82f640 ,&mEglDisplay = 1 , &mEglConfig = -1366834928 
02-05 02:42:52.007 5294-5315/com.example.administrator.quizy D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 8192
02-05 02:42:52.007 5294-5315/com.example.administrator.quizy D/OpenGLRenderer: Enabling debug mode 0
02-05 02:42:52.007 5294-5315/com.example.administrator.quizy D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
02-05 02:42:52.042 5294-5294/com.example.administrator.quizy W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
02-05 02:42:52.152 5294-5294/com.example.administrator.quizy I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3e4a8ebb time:256653532
02-05 02:42:52.702 5294-5294/com.example.administrator.quizy D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-05 02:42:52.742 5294-5294/com.example.administrator.quizy I/Timeline: Timeline: Activity_launch_request id:com.example.administrator.quizy time:256654121
02-05 02:42:52.777 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* installDecor mIsFloating : false
02-05 02:42:52.777 5294-5294/com.example.administrator.quizy D/PhoneWindow: *FMB* installDecor flags : -2139029248
02-05 02:42:52.792 5294-5294/com.example.administrator.quizy V/CATEGORY_TAG: 0
02-05 02:42:52.792 5294-5294/com.example.administrator.quizy W/ResourceType: No package identifier when getting value for resource number 0x00000001
02-05 02:42:52.792 5294-5294/com.example.administrator.quizy D/AndroidRuntime: Shutting down VM
02-05 02:42:52.802 5294-5294/com.example.administrator.quizy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.administrator.quizy, PID: 5294
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.administrator.quizy/com.example.administrator.quizy.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x1
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:197)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6872)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                                Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x1
                                                                                   at android.content.res.Resources.getText(Resources.java:1409)
                                                                                   at android.widget.TextView.setText(TextView.java:4943)
                                                                                   at com.example.administrator.quizy.MainActivity.showNextQuiz(MainActivity.java:103)
                                                                                   at com.example.administrator.quizy.MainActivity.onCreate(MainActivity.java:94)
                                                                                   at android.app.Activity.performCreate(Activity.java:6550)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248) 
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6872) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

**Comment by mikepenz** [comment]
Not a library issue. 

That issue is in your app

```
at android.content.res.Resources.getText(Resources.java:1409)
```
