### ISSUE TITLE
Error when use AccountHeader

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2199]
I used this code exactly:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

when I include AccountHeader I get the following error. while if ignore this AccountHeader, code works correcyly.why?

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{act.ActMain2}: android.view.InflateException: Binary XML file line #17: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                     at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                     at android.os.Looper.loop(Looper.java:136)
                                     at android.app.ActivityThread.main(ActivityThread.java:5105)
                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                     at dalvik.system.NativeStart.main(Native Method)
                                  Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:597)
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:760)
                                     at act.ActMain2.setDrawer(ActMain2.java:1768)
                                     at act.ActMain2.onCreate(ActMain2.java:261)
                                     at android.app.Activity.performCreate(Activity.java:5275)
                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                     at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                     at android.os.Looper.loop(Looper.java:136) 
                                     at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                     at dalvik.system.NativeStart.main(Native Method) 
                                  Caused by: java.lang.reflect.InvocationTargetException
                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:597) 
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:760) 
                                     at act.ActMain2.setDrawer(ActMain2.java:1768) 
                                     at act.ActMain2.onCreate(ActMain2.java:261) 
                                     at android.app.Activity.performCreate(Activity.java:5275) 
                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                     at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                     at android.os.Looper.loop(Looper.java:136) 
                                     at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                     at dalvik.system.NativeStart.main(Native Method) 
                                  Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                     at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                     at com.mikepenz.materialdrawer.view.BezelImageView.<init>(BezelImageView.java:104)
                                     at com.mikepenz.materialdrawer.view.BezelImageView.<init>(BezelImageView.java:88)
                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                     at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:597) 
                                     at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:760) 
                                     at act.ActMain2.setDrawer(ActMain2.java:1768) 
                                     at act.ActMain2.onCreate(ActMain2.java:261) 
                                     at android.app.Activity.performCreate(Activity.java:5275) 
                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                     at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                     at android.os.Looper.loop(Looper.java:136) 
                                     at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by mikepenz** [comment]
@BigGitWorld it seems like you have a misconfigured Proguard setup and remove that view

**Comment by mikepenz** [comment]
It is correctly in the library (v6.0.5) 

<img width="368" alt="screen shot 2018-02-04 at 21 16 49" src="https://user-images.githubusercontent.com/1476232/35781937-be330584-09f0-11e8-8fc2-bc93d826c240.png">

make sure you have proper proguard configuration which keeps views

**Comment by BigGitWorld** [comment]
my progaurd is not enabled at all. this is my build.gradle file:

```

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "my.project.sample"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        preDexLibraries = false
    }
}



dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
  
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:26.0.0-alpha1'
    compile 'com.android.support:cardview-v7:26.0.0-alpha1'
    compile 'com.android.support:design:26.0.0-alpha1'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.novoda:merlin:1.1.5'
    compile 'com.afollestad:material-cab:0.1.12'
    compile("com.mikepenz:materialdrawer:6.0.5@aar") {
        transitive = true
    }
    //required support lib modules
    compile "com.android.support:recyclerview-v7:26.0.0-alpha1"
    compile "com.android.support:support-annotations:26.0.0-alpha1"
}

apply plugin: 'com.google.gms.google-services'

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}

```

**Comment by mikepenz** [comment]
it might also be incompatiblity of support libraries 25.3.1, and your compile 26 or so. 

This library is developed and using the latest releases. 

As shown the library contains the class. So it might also be some build issue on your side. perhaps clean helps...

**Comment by BigGitWorld** [comment]
I don't know what is the problem. when I removed above "configurations.all" I will receive the following error:
````
Error:Failed to resolve: com.android.support:support-annotations:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/MyWorks/AndroidProjects/niligo-android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:appcompat-v7:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/MyWorks/AndroidProjects/niligo-android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:recyclerview-v7:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/MyWorks/AndroidProjects/niligo-android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: annotationProcessor
<a href="disable.gradle.offline.mode">Disable offline mode and sync project</a><br><a href="openFile:/home/MyWorks/AndroidProjects/niligo-android/app/build.gradle">Open File</a>
```

while I have downloaded latest versions of android sdk and dont have problem with other libraries...

**Comment by mikepenz** [comment]
@BigGitWorld do you use a `MultiDexApplication` does it crash only on specific devices?

**Comment by hungntv** [comment]
I got this crash on Android 12

**App gradle:**
```
compileSdkVersion 31
buildToolsVersion "31.0.0"
targetSdkVersion 31
....
implementation "androidx.drawerlayout:drawerlayout:1.1.1"
implementation "com.mikepenz:materialdrawer:9.0.1"
```

**Crash log:**
```
Caused by: android.view.InflateException: Binary XML file line #26 in <my package name>:layout/material_drawer_header: Binary XML file line #26 in a.b.c:layout/material_drawer_header: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
     Caused by: android.view.InflateException: Binary XML file line #26 in my package name:layout/material_drawer_header: Error inflating class com.mikepenz.materialdrawer.view.BezelImageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.<init>(AccountHeaderView.kt:412)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.<init>(AccountHeaderView.kt:35)
        at...
```

**File `jetified-materialdrawer-901>res>layout>material_drawer_header.xml`**
```
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/material_drawer_account_header"
    android:layout_width="match_parent"
    android:layout_height="@dimen/material_drawer_account_header_height"
    android:clickable="true">

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/material_drawer_account_header_background"
        android:layout_width="match_parent"
        android:layout_height="@dimen/material_drawer_account_header_height"
        android:scaleType="centerCrop"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/material_drawer_statusbar_guideline"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_begin="0dp" />

    <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_current"
        style="@style/BezelImageView"
        android:layout_width="@dimen/material_drawer_account_header_selected"
        android:layout_height="@dimen/material_drawer_account_header_selected"
        android:layout_marginStart="@dimen/material_drawer_vertical_padding"
        android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
        android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
        android:clickable="true"
        android:elevation="@dimen/material_drawer_account_header_profile_elevation"
        android:focusable="true"
        android:scaleType="fitCenter"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/material_drawer_statusbar_guideline" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_current_badge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:elevation="@dimen/material_drawer_account_header_profile_badge_elevation"
        android:fontFamily="sans-serif"
        android:gravity="center"
        android:lines="1"
        android:minWidth="20dp"
        android:paddingLeft="1dp"
        android:paddingRight="1dp"
        android:singleLine="true"
        android:textSize="@dimen/material_drawer_item_badge_text"
        app:layout_constraintBottom_toBottomOf="@id/material_drawer_account_header_current"
        app:layout_constraintStart_toStartOf="@id/material_drawer_account_header_current"
        tools:text="99" />

    <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_first"
        style="@style/BezelImageView"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
        android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="@dimen/material_drawer_account_header_profile_small_elevation"
        android:focusable="true"
        android:scaleType="fitCenter"
        android:visibility="visible"
        app:layout_constraintEnd_toStartOf="@id/material_drawer_account_header_small_second"
        app:layout_constraintTop_toBottomOf="@+id/material_drawer_statusbar_guideline" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_small_first_badge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:elevation="@dimen/material_drawer_account_header_profile_badge_elevation"
        android:fontFamily="sans-serif"
        android:gravity="center"
        android:lines="1"
        android:minWidth="20dp"
        android:paddingLeft="1dp"
        android:paddingRight="1dp"
        android:singleLine="true"
        android:textSize="@dimen/material_drawer_item_badge_small_text"
        app:layout_constraintBottom_toBottomOf="@id/material_drawer_account_header_small_first"
        app:layout_constraintStart_toStartOf="@id/material_drawer_account_header_small_first"
        tools:text="99" />

    <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_second"
        style="@style/BezelImageView"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
        android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="@dimen/material_drawer_account_header_profile_small_elevation"
        android:focusable="true"
        android:scaleType="fitCenter"
        android:visibility="visible"
        app:layout_constraintEnd_toStartOf="@id/material_drawer_account_header_small_third"
        app:layout_constraintTop_toBottomOf="@+id/material_drawer_statusbar_guideline" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_small_second_badge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:elevation="@dimen/material_drawer_account_header_profile_badge_elevation"
        android:fontFamily="sans-serif"
        android:gravity="center"
        android:lines="1"
        android:minWidth="20dp"
        android:paddingLeft="1dp"
        android:paddingRight="1dp"
        android:singleLine="true"
        android:textSize="@dimen/material_drawer_item_badge_small_text"
        app:layout_constraintBottom_toBottomOf="@id/material_drawer_account_header_small_second"
        app:layout_constraintStart_toStartOf="@id/material_drawer_account_header_small_second"
        tools:text="99" />

    <com.mikepenz.materialdrawer.view.BezelImageView
        android:id="@+id/material_drawer_account_header_small_third"
        style="@style/BezelImageView"
        android:layout_width="@dimen/material_drawer_account_header_secondary"
        android:layout_height="@dimen/material_drawer_account_header_secondary"
        android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
        android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:clickable="true"
        android:elevation="@dimen/material_drawer_account_header_profile_small_elevation"
        android:focusable="true"
        android:scaleType="fitCenter"
        android:visibility="visible"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/material_drawer_statusbar_guideline" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_small_third_badge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:elevation="@dimen/material_drawer_account_header_profile_badge_elevation"
        android:fontFamily="sans-serif"
        android:gravity="center"
        android:lines="1"
        android:minWidth="20dp"
        android:paddingLeft="1dp"
        android:paddingRight="1dp"
        android:singleLine="true"
        android:textSize="@dimen/material_drawer_item_badge_small_text"
        app:layout_constraintBottom_toBottomOf="@id/material_drawer_account_header_small_third"
        app:layout_constraintStart_toStartOf="@id/material_drawer_account_header_small_third"
        tools:text="99" />

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/material_drawer_text_guideline"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_end="@dimen/material_drawer_account_header_dropdown_guideline" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_name"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/material_drawer_vertical_padding"
        android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
        android:fontFamily="sans-serif-medium"
        android:lines="1"
        android:maxLines="1"
        android:textSize="@dimen/material_drawer_account_header_title"
        app:layout_constraintBottom_toTopOf="@id/material_drawer_account_header_email"
        app:layout_constraintEnd_toStartOf="@id/material_drawer_account_header_text_switcher"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/material_drawer_text_guideline"
        app:layout_constraintVertical_chainStyle="packed" />

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/material_drawer_account_header_email"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/material_drawer_vertical_padding"
        android:layout_marginLeft="@dimen/material_drawer_vertical_padding"
        android:layout_marginBottom="@dimen/material_drawer_padding"
        android:fontFamily="sans-serif"
        android:lines="1"
        android:maxLines="1"
        android:textSize="@dimen/material_drawer_account_header_subtext"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toStartOf="@id/material_drawer_account_header_text_switcher"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/material_drawer_account_header_name" />

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/material_drawer_account_header_text_switcher"
        android:layout_width="@dimen/material_drawer_account_header_dropdown"
        android:layout_height="@dimen/material_drawer_account_header_dropdown"
        android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
        android:layout_marginRight="@dimen/material_drawer_vertical_padding"
        android:layout_marginBottom="@dimen/material_drawer_account_header_dropdown_margin_bottom"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />
</merge>

```

It works with your materialdrawer version 8

**Comment by mikepenz** [comment]
@hungntv v9 requires the new `Material3` theme: https://github.com/mikepenz/MaterialDrawer#3-add-the-drawerstyle-to-your-theme

**Comment by hungntv** [comment]
> @hungntv v9 requires the new `Material3` theme: https://github.com/mikepenz/MaterialDrawer#3-add-the-drawerstyle-to-your-theme

Thanks!

Requiring Material3 is the key!
My bad
