### ISSUE TITLE
toolbar issue when user DrawerActivity sample code

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2204]
## About this issue
I had several issues with this library.
At first, I received an issue about inflating BezelImageView and then I used "MaterialDrawerTheme" in manifest file as theme.
Now I receive the following error about toolbar. why?
``` 
? E/AndroidRuntime: FATAL EXCEPTION: main
                    Process: com.co.app, PID: 2902
                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.co.app/com.co.app.act.ActTest}: android.view.InflateException: Binary XML file line #7: Error inflating class android.support.v7.widget.Toolbar
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                        at android.app.ActivityThread.access$800(ActivityThread.java:139)
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:136)
                        at android.app.ActivityThread.main(ActivityThread.java:5105)
                        at java.lang.reflect.Method.invokeNative(Native Method)
                        at java.lang.reflect.Method.invoke(Method.java:515)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                        at dalvik.system.NativeStart.main(Native Method)
                     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.support.v7.widget.Toolbar
                        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                        at com.co.app.act.ActTest.onCreate(ActTest.java:42)
                        at android.app.Activity.performCreate(Activity.java:5275)
                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                        at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:136) 
                        at android.app.ActivityThread.main(ActivityThread.java:5105) 
                        at java.lang.reflect.Method.invokeNative(Native Method) 
                        at java.lang.reflect.Method.invoke(Method.java:515) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                        at dalvik.system.NativeStart.main(Native Method) 
                     Caused by: java.lang.reflect.InvocationTargetException
                        at java.lang.reflect.Constructor.constructNative(Native Method)
                        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                        at com.co.app.act.ActTest.onCreate(ActTest.java:42) 
                        at android.app.Activity.performCreate(Activity.java:5275) 
                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                        at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:136) 
                        at android.app.ActivityThread.main(ActivityThread.java:5105) 
                        at java.lang.reflect.Method.invokeNative(Native Method) 
                        at java.lang.reflect.Method.invoke(Method.java:515) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                        at dalvik.system.NativeStart.main(Native Method) 
                     Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f0100ca a=4 r=0x7f0d0077}
                        at android.content.res.Resources.loadDrawable(Resources.java:2108)
                        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                        at android.view.View.<init>(View.java:3558)
                        at android.view.ViewGroup.<init>(ViewGroup.java:470)
                        at android.support.v7.widget.Toolbar.<init>(Toolbar.java:235)
                        at android.support.v7.widget.Toolbar.<init>(Toolbar.java:231)
                        at java.lang.reflect.Constructor.constructNative(Native Method) 
                        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                        at com.co.app.act.ActTest.onCreate(ActTest.java:42) 
                        at android.app.Activity.performCreate(Activity.java:5275) 
                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                        at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:136) 
                        at android.app.ActivityThread.main(ActivityThread.java:5105) 
                        at java.lang.reflect.Method.invokeNative(Native Method) 
                        at java.lang.reflect.Method.invoke(Method.java:515) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by mikepenz** [comment]
@BigGitWorld the `Toolbar` is not part of this library, and not added by this library. 

It is part of the `AppCompat` libraries which you need:

```
implementation "com.android.support:appcompat-v7:${versions.supportLib}"
```

**Comment by BigGitWorld** [comment]
I included this library in build.gradle file : 
```
apply plugin: 'com.android.application'


android {
    compileSdkVersion 27
    buildToolsVersion "27.0.1"
    defaultConfig {
        applicationId "com.co.app"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        setProperty("archivesBaseName", "MaterialDrawer-v$versionName-c$versionCode")
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        preDexLibraries = false
    }
}



dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    //compile 'com.android.support.constraint:constraint-layout:1.0.2'

   

    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.2'

    compile("com.mikepenz:materialdrawer:6.0.5@aar") {
        transitive = true
    }
    //required support lib modules
   
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:cardview-v7:27.0.0'
    compile 'com.android.support:design:27.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha7'
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.android.support:recyclerview-v7:27.0.0'
    compile 'com.android.support:support-annotations:27.0.0'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}


//conflict 25.3.0 and 25.3.1
configurations.all {

    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }

    resolutionStrategy.force "com.mikepenz:iconics-core:3.0.2"
    resolutionStrategy.force "com.mikepenz:fastadapter:3.2.3"
    resolutionStrategy.force "com.android.support:support-v4:27.0.0"
    resolutionStrategy.force "com.android.support:appcompat-v7:27.0.0"
    resolutionStrategy.force "com.android.support:cardview-v7:27.0.0"
    resolutionStrategy.force "com.android.support:recyclerview-v7:27.0.0"
    resolutionStrategy.force "com.android.support:design:27.0.0"
    resolutionStrategy.force "com.android.support:support-annotations:27.0.0"
}
```
I added several other libraries and them work correctly. but I have problem with this library.
your library is very good and has several features, so that I would like solve the problem :((

**Comment by mikepenz** [comment]
I don't think it has anything to do with this library :D 

You seem to have multidex enabled. Do you have the `MultiDexApplication` specified for your application?

**Comment by BigGitWorld** [comment]
Yes. I extends `MultiDexApplication` to create an application class that loaded before all activities.
do you think the problem is for that?

**Comment by mikepenz** [comment]
well it could be. classes which you include are missing. so it sounds like the different dex files are not correctly loaded

**Comment by mikepenz** [comment]
or you need to do a clean

**Comment by mikepenz** [comment]
or a misconfigured proguard

**Comment by BigGitWorld** [comment]
I don't use proguard at all yet.
also I cleaned the project several times, but nothing special occurs.
I will try remove MultiDexApplication now...

**Comment by mikepenz** [comment]
no need to remove it. If it is set up correctly it should not cause issues.

**Comment by BigGitWorld** [comment]
so how can I resolve the problem. I have this problem for several days...please help me :(

**Comment by mikepenz** [comment]
@BigGitWorld can you please remove the resolution strategy at all? 

remove `preDexLibraries` too

remove `setProperty("archivesBaseName", "MaterialDrawer-v$versionName-c$versionCode")` too as it seems very weird that you want to name your app `MaterialDrawer` :P

**Comment by BigGitWorld** [comment]
I removed the `resolution strategy` and `preDexLibraries` too. but does not changed anything :(

**Comment by BigGitWorld** [comment]
I want to create a new project and all all of code again to this new project.
do you think this is good idea or not?

**Comment by mikepenz** [comment]
Can you please create a zip of the project and send it to me. so I can check it out. I am really curious on what's going on

**Comment by BigGitWorld** [comment]
yes of course.it is very big (255 MB). please let me remove unnecessary sections and send to you.
can you please give me your email address to send it?

**Comment by mikepenz** [comment]
You can remove the `build` and `.git` and `.gradle` folders it should already make it tiny.

**Comment by mikepenz** [comment]
my e-mail should be mentioned in the README on the bottom `mikepenz@gmail.com`

**Comment by BigGitWorld** [comment]
I sent it by google drive. because its size is 29 MB (larger than 25 MB).
thank you very much...

**Comment by BigGitWorld** [comment]
Thank you very much...
you are the best person whom I have seen in github.
best wishes...

**Comment by mikepenz** [comment]
Thank you very much. Good luck
