### ISSUE TITLE
Crash: Two different ViewHolders have the same stable ID

### ISSUE THREAD

**Issue by tnducrocq** [mikepenz/MaterialDrawer#2207]
Hello,

I use the MiniDrawer and I have a crash when I select an item when the menu is in mini mode.
   ```
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
                                        ViewHolder 1:ViewHolder{4e045c3 position=1 id=-3, oldPos=-1, pLpos:-1 not recyclable(1)} 
                                        View Holder 2:ViewHolder{5fe01dc position=0 id=-3, oldPos=-1, pLpos:-1} android.support.v7.widget.RecyclerView{d7494d9 VFED..... ......ID 0,0-72,664}, adapter:com.mikepenz.fastadapter.FastAdapter@914e40, layout:android.support.v7.widget.LinearLayoutManager@9360179, context:fr.businessdecision.areva5s.MainActivity@5ab6fea
                                           at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:3826)
                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3751)
                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3421)
                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                           at android.view.View.layout(View.java:17838)
                                           at android.view.ViewGroup.layout(ViewGroup.java:5754)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                           at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1971)
                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1737)
                                           at android.view.View.layout(View.java:17838)
                                           at android.view.ViewGroup.layout(ViewGroup.java:5754)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                           at android.view.View.layout(View.java:17838)
                                           at android.view.ViewGroup.layout(ViewGroup.java:5754)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                           at android.view.View.layout(View.java:17838)
                                           at android.view.ViewGroup.layout(ViewGroup.java:5754)
                                           at android.support.v4.widget.SlidingPaneLayout.onLayout(SlidingPaneLayout.java:717)
                                           at com.mikepenz.crossfader.view.CrossFadeSlidingPaneLayout.onLayout(CrossFadeSlidingPaneLayout.java:101)
```
Do you have any idea what I'm doing wrong?

**Comment by mikepenz** [comment]
@tnducrocq well the crash is very precise about the issue. Make sure you don't have the same identifier twice

**Comment by tnducrocq** [comment]
Ok...
I took the examples again with MiniDrawer, I didn't modify the PrimaryDrawerItem identifiers.
Thank you!
