### ISSUE TITLE
FATAL ERROR: No static method getCompatDrawable

### ISSUE THREAD

**Issue by MoleClement** [mikepenz/MaterialDrawer#2276]
Hi !
First, I'm grateful for the amazing work you've done, can't top you :)

I'm currently using your work ( material drawer -> to use mini-drawer ) for a school project.
Also, I'm new to android studio, I'm used to C++, but hey I've learned java recently, pretty similar, I mean it is POO.
I'm currently stuck on a problem, I've tried things, none worked. 
I checked similar issues and tried to follow the answer you gave, but there again resultless.

This is in my gradle: 
I double checked the transitive = true: 

implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'

    implementation 'com.android.support:design:26.1.0'

    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

    implementation 'com.android.volley:volley:1.0.0'

    compile('com.mikepenz:materialdrawer:6.0.7@aar') {transitive = true}
  
    compile ('com.mikepenz:crossfadedrawerlayout:1.0.1@aar')
            {transitive = true}

    compile ('com.mikepenz:crossfader:1.5.2@aar')
            {transitive = true }

    compile ('com.mikepenz:materialize:1.1.2@aar')
            {transitive = true;}

    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:support-annotations:27.1.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

Here is the error log: 
 E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.fengh.studeasy, PID: 9836
                  java.lang.NoSuchMethodError: No static method getCompatDrawable(Landroid/content/Context;I)Landroid/graphics/drawable/Drawable; in class Lcom/mikepenz/materialize/util/UIUtils; or its super classes (declaration of 'com.mikepenz.materialize.util.UIUtils' appears in /data/app/com.fengh.studeasy-2/split_lib_dependencies_apk.apk)
                      at com.mikepenz.materialdrawer.AccountHeaderBuilder.handleSelectionView(AccountHeaderBuilder.java:723)
                      at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:820)
                      at com.fengh.studeasy.HomeActivity.onCreate(HomeActivity.java:85)
                      at android.app.Activity.performCreate(Activity.java:6912)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6692)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

Sorry it is a bit long, but I'm afraid to truncate something important :)

Did I miss some compile / implementation, I don't think so.
I'm following this guide you wrote : 

https://github.com/mikepenz/CrossfadeDrawerLayout

Excuse me if there's any faults I'm French, although I tried my best.
Cheers from Paris.

EDIT:
This error happened after I tried to use mini drawer : normal drawer work ! -> using MaterialDrawer.
I repeat but the error showed since I started using mini drawer !
But for my project I'd like to use this mini drawer :).

**Comment by MoleClement** [comment]
I've started a new project,
updated my android studio,
double checked all version.
It works now. 
But still don't know the cause of the previous problem.

**Comment by mikepenz** [comment]
@MoleClement the latest library uses the latest support libs: https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L11

you need to be 27+ support libs
