### ISSUE TITLE
Error inflate AccountHeaderBuilder()

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2278]
I can't use version of support lib lower than 27.1.1. When I update from 27.0.1 to 27.1.1, i get this:

```
04-16 12:23:28.232 12791-12791/uz.paycom.merchantcabinet W/System.err: android.view.InflateException: Binary XML file line #80: Binary XML file line #80: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #80: Error inflating class TextView
04-16 12:23:28.233 12791-12791/uz.paycom.merchantcabinet W/System.err: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=37; index=796
        at android.content.res.StringBlock.get(StringBlock.java:65)
        at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1212)
        at android.content.res.TypedArray.getString(TypedArray.java:202)
        at android.support.v7.widget.TintTypedArray.getString(TintTypedArray.java:142)
        at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:243)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:165)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:82)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
04-16 12:23:28.234 12791-12791/uz.paycom.merchantcabinet W/System.err:     at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.java:597)
        at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:760)
        at uz.paycom.merchantcabinet.ui.main.MainActivity.showBusiness(MainActivity.kt:119)
04-16 12:23:28.235 12791-12791/uz.paycom.merchantcabinet W/System.err:     at uz.paycom.merchantcabinet.ui.main.MainPresenter$loadBusiness$2.accept(MainPresenter.kt:39)
        at uz.paycom.merchantcabinet.ui.main.MainPresenter$loadBusiness$2.accept(MainPresenter.kt:20)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
04-16 12:23:28.236 12791-12791/uz.paycom.merchantcabinet W/System.err:     at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I use latest version of materialdrawer (6.0.7). How to fix this? Please help

**Comment by N-i-p-o-l** [comment]
I use AS 3.1.1 (latest stable version) with multidex 1.0.3

**Comment by N-i-p-o-l** [comment]
Disable multidex, run debug version without proguard same error

**Comment by mikepenz** [comment]
the latest version of the materialDrawer currently uses support libs 27.1.0: https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L11

did you clean everything?

**Comment by N-i-p-o-l** [comment]
Clean && Rebuild no effect(

**Comment by N-i-p-o-l** [comment]
I don't know why, but if remove all fontFamily tags in material_drawer*.xml layouts problem disappears

**Comment by mikepenz** [comment]
I don't know seems to be some conflict of some of your dependencies, nobody else is reporting this :)
