### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x7f08006a

### ISSUE THREAD

**Issue by J-Ttt** [mikepenz/MaterialDrawer#2346]
Application works on Android version 8.1.0, API 27 (OnePlus 5)
But when started on Android version 6.0.1, API 23 (Sony Xperia Z3)

I don't think there is anything wrong on the code since it works just fine on OnePlus 5
Here is stacktrace:
```
08-17 13:22:48.597 15578-15578/com.example.omistaja.universal_io E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.omistaja.universal_io, PID: 15578
    android.content.res.Resources$NotFoundException: Resource ID #0x7f08006a
        at android.content.res.Resources.getValue(Resources.java:1358)
        at androidx.appcompat.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:331)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
        at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:103)
        at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:135)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:97)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:18)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:27)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:740)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16722)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    	at android.widget.Linear
```

The stacktrace weirdly ends like that as well.

## Details
- [ 6.0.8 and tried 6.1.0-rc01 ] Used library version
- [ appcompat:1.0.0-alpha1 & legacy-support-v4:1.0.0-alpha1 ] Used support library version
- [ 3.3.0-alpha05 ] Used gradle build tools version
- [ Android Studio 3.3 Canary 5 ] Used tooling / Android Studio version
- [ 'com.google.guava:guava:25.1-jre' 'com.github.anshulagarwal06:PasswordEditText:v1.0' 'com.google.android.material:material:1.0.0-alpha1' 'androidx.constraintlayout:constraintlayout:1.1.2' 'androidx.media:media:1.0.0-beta01' ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
does the same crash happen with the sample app?

It seems to crash during binding an item. could it be you use a drawable which is not available on an old android version?

**Comment by mikepenz** [comment]
Please report back :). closing for now
