### ISSUE TITLE
 java.lang.NoClassDefFoundError: android.graphics.drawable.RippleDrawable

### ISSUE THREAD

**Issue by root1** [mikepenz/MaterialDrawer#2362]
Getting the following error when i try to use the library

    java.lang.NoClassDefFoundError: android.graphics.drawable.RippleDrawable
        at com.mikepenz.materialdrawer.util.DrawerUIUtils.themeDrawerItem(DrawerUIUtils.java:81)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:80)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:18)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:27)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:740)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)

**Comment by root1** [comment]
This is my gradle file

    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.mikepenz:materialdrawer:6.1.0-rc02"
    implementation "androidx.appcompat:appcompat:1.0.0-rc02"
    implementation "androidx.recyclerview:recyclerview:1.0.0-rc02"
    implementation "androidx.annotation:annotation:1.0.0-rc02"
    implementation "com.google.android.material:material:1.0.0-rc02"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation 'com.mikepenz:google-material-typeface:3.0.1.1.original@aar'
    implementation 'com.mikepenz:fontawesome-typeface:5.0.6.0@aar'
    implementation 'com.mikepenz:octicons-typeface:3.0.0.1@aar'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.bumptech.glide:glide:3.8.0'
    implementation 'com.mikepenz:itemanimators:1.1.0-rc01'
    implementation 'com.mikepenz:fastadapter-commons:3.3.0-rc01'
    implementation "androidx.room:room-runtime:2.0.0-rc01"
    annotationProcessor "androidx.room:room-compiler:2.0.0-rc01"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    }

**Comment by mikepenz** [comment]
What's the android version you run this on? 

The class missing comes from the android system. and is not included in the library

**Comment by mikepenz** [comment]
Also do you re-style the drawerItem in any way? applying a different background or such?

**Comment by root1** [comment]
I am running it on android version 4.4.2 and i am not doing any drawer item styling

**Comment by mikepenz** [comment]
Can you run the sample app on your phone please. 
It might be due to the upgrade to androidX that android 4.4. support broke
