### ISSUE TITLE
App crashes after onclicklistener is resolve

### ISSUE THREAD

**Issue by Psiale** [mikepenz/MaterialDrawer#2363]
## About this issue

- Hi! It's my first time using your library. 
After I click the item and the intent send me to the activity I want, I can't click on anything inside that activity cause it crashes.
This is the error: 
### 09-24 19:53:24.607 9002-9002/com.example.psiale.cuntochupar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.psiale.cuntochupar, PID: 9002
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.psiale.cuntochupar/com.example.psiale.cuntochupar.Drinks}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1068)
        at java.lang.Double.valueOf(Double.java:511)
        at com.example.psiale.cuntochupar.Drinks.onCreate(Drinks.java:67)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

And 
Here's my code `//Drawer
        final IProfile profile = new ProfileDrawerItem().withName("Borrachín Anonimo")
                .withIcon(R.drawable.anonymusdrunk)
                .withIdentifier(100);

         headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(profile)
                 .withSavedInstance(savedInstanceState)
                 .build();

         result = new DrawerBuilder()
                 .withActivity(this)
                .withHasStableIds(true)
                .withAccountHeader(headerResult)
                 .addDrawerItems(
                         new PrimaryDrawerItem().withName(R.string.Grados_de_ebriedad).withIdentifier(1).withSelectable(true)
                 )
                 .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                     @Override
                     public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                         if(drawerItem != null) {
                             Intent intent = new Intent(getApplicationContext(), DrunkinMenu.class);
                             startActivity(intent);
                         }
                         return false;
                     }
                 })
                .build();`
## Details
This happens no matter what activity I redirect, please help me.

**Comment by Psiale** [comment]
Already fixed it, the problem was a Log that was empty, sorry xD
