### ISSUE TITLE
 Issue in Marshmallow and Lollipop

### ISSUE THREAD

**Issue by Nitishr15** [mikepenz/MaterialDrawer#2365]
I am getting following error in marshmallow and Lollipop but it is working fine in Nougat and Oreo

```
 android.content.res.Resources$NotFoundException: Resource ID #0x7f080072
                      at android.content.res.Resources.getValue(Resources.java:1351)
                      at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:328)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                      at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                      at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:103)
                      at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:135)
                      at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:97)
                      at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
                      at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:18)
                      at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:27)
                      at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:740)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
                      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1195)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                      at android.view.View.layout(View.java:16630)
                      at android.view.ViewGroup.layout(ViewGroup.java:5437)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                  	at android.widget.Fram
```

 build.gradle (Module:app)

```gradle
android {
    compileSdkVersion 27
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        minSdkVersion 22
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
}

implementation('com.mikepenz:materialdrawer:6.0.9@aar') {
        transitive = true
    }
```

my code:

```java
        public Drawer adddrawer(final Context context, Bundle savedInstanceState, Drawer result, 
        AccountHeader headerResult, Toolbar toolbar) {

        final IProfile profile = new ProfileDrawerItem().withName("Name").withEmail("abc@gmail.com"));

        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withHeaderBackground(R.color.md_grey_800)
                .withSelectionListEnabledForSingleProfile(false)
                .addProfiles(
                        profile )
                .withSavedInstance(savedInstanceState)
                .build();

        result = new DrawerBuilder()
                .withSavedInstance(savedInstanceState)
                .withActivity((Activity) context)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withCloseOnClick(true)
                .withSelectedItem(-1)
                .withDrawerLayout(R.layout.material_drawer_fits_not)
                .addDrawerItems(
                        new 
      PrimaryDrawerItem().withIdentifier(1).withName("NAME!").withIcon(R.drawable.ic_album_black_24dp),
                        new SectionDrawerItem(),
                        new 
      SecondaryDrawerItem().withIdentifier(2).withName("Logout").withIcon(R.drawable.ic_exit)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        switch ((int) drawerItem.getIdentifier()) {
                            case 1:
                                startActivity(new Intent(context, Activity.class));
                                break;
                            case 2:
                                Parms.SaveSharedPreferenceData(context, Parms.isRemember, "0");
                                finishAffinity();
                                showMessage("Logging out");
                                break;
                        }

                        return false;
                    }
                }).build();

        return result;
    }
```

Can anyone help me:

**Comment by mikepenz** [comment]
Do you see the same in the sample app?

**Comment by mikepenz** [comment]
Please report back. Close until then
