### ISSUE TITLE
Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView

### ISSUE THREAD

**Issue by roip890** [mikepenz/MaterialDrawer#2391]
Hi,

I run into error when using the material drewer.

```
private void buildDrawer(Bundle savedInstanceState) {
        this.drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(this.toolbar)
                .withAccountHeader(this.headerResult)
                .addDrawerItems(
                        this.homeDrawerItem,
                        this.accountDrawerItem
                .withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View clickedView) {
                        MainActivity.this.finish();
                    }
                })
                .withSavedInstance(savedInstanceState)
                .withSliderBackgroundColor(Color.Black)
                .build();
    }
```

And I run into this error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bob.bobmobileapp, PID: 25122
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bob.bobmobileapp/com.bob.bobmobileapp.activities.main.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.mikepenz.materialdrawer.DrawerBuilder.createContent(DrawerBuilder.java:1663)
        at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1553)
        at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1351)
        at com.bob.bobmobileapp.activities.main.MainActivity.buildDrawer(MainActivity.java:479)
        at com.bob.bobmobileapp.activities.main.MainActivity.onCreate(MainActivity.java:150)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NoSuchFieldError: No static field RecyclerView of type [I in class Landroidx/recyclerview/R$styleable; or its superclasses (declaration of 'androidx.recyclerview.R$styleable' appears in /data/app/com.bob.bobmobileapp-x3dxCKkpVcNcdhGr4bV6iA==/split_lib_slice_6_apk.apk)
        at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:691)
        at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:647)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.mikepenz.materialdrawer.DrawerBuilder.createContent(DrawerBuilder.java:1663) 
        at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1553) 
        at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1351) 
        at com.bob.bobmobileapp.activities.main.MainActivity.buildDrawer(MainActivity.java:479) 
        at com.bob.bobmobileapp.activities.main.MainActivity.onCreate(MainActivity.java:150) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

```

Those are the important lines:

```
        at com.mikepenz.materialdrawer.DrawerBuilder.createContent(DrawerBuilder.java:1663)
        at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1553)
        at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1351)
        at com.bob.bobmobileapp.activities.main.MainActivity.buildDrawer(MainActivity.java:479)
        at com.bob.bobmobileapp.activities.main.MainActivity.onCreate(MainActivity.java:150)

```
```
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class androidx.recyclerview.widget.RecyclerView

```

I am using 6.1.0 version.
And I am using all latest androidx versions.

**Comment by mikepenz** [comment]
@roip890 the error shows that you do not have the androidx `RecyclerView` in your project. 

Please ensure you have the required modules in your gradle:

```
implementation "com.mikepenz:materialdrawer:6.1.1"

//required support lib modules
implementation "androidx.appcompat:appcompat:${versions.androidX}"
implementation "androidx.recyclerview:recyclerview:${versions.androidX}"
implementation "androidx.annotation:annotation:${versions.androidX}"
implementation "com.google.android.material:material:${versions.androidX}"
implementation "androidx.constraintlayout:constraintlayout:${versions.constraintLayout}"
```

**Comment by roip890** [comment]
@mikepenz 
Hi,
I do have all of those in my gradle file:

```
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'

```

**Comment by AnkuKmrRoy** [comment]
all libraries included well but still getting such error. even same recycler view working on few activities.

**Comment by Guy1982** [comment]
I changed the signature in the XML to androidx.recyclerview.widget.RecyclerView and It worked.

**Comment by Mwangii** [comment]
Change to this <androidx.cardview.widget.CardView
from  <android.support.v7.widget.CardView

Works after that.
