### ISSUE TITLE
Mini Drawer issue generate issue 

### ISSUE THREAD

**Issue by geniusforapp** [mikepenz/MaterialDrawer#2426]
## About this issue

- When i create the drawer the mini drawer it crash before the app start and show this error

 java.lang.RuntimeException: Unable to start activity ComponentInfo{carriage.com.myapplication/carriage.com.myapplication.MainActivity}: kotlin.TypeCastException: null cannot be cast to non-null type T
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2962)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6949)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type T
        at com.mikepenz.fastadapter.FastAdapter.getExtension(FastAdapter.kt:280)
        at com.mikepenz.materialdrawer.MiniDrawer.build(MiniDrawer.java:330)
        at carriage.com.myapplication.MainActivity.onCreate(MainActivity.java:88)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2915)

## Details
- [ 7+ alpha2] Used library version
- [ android x 1.0+] Used support library version
- [ 3.4] Used gradle build tools version
- [fast adapter] Other used libraries, potential conflicting libraries

## Checklist

- [ yes] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [yes] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [yes ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [yes ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ yes] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [yes ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by geniusforapp** [comment]
@mikepenz any help please

**Comment by mikepenz** [comment]
well that is something in your code:

```
ComponentInfo{carriage.com.myapplication/carriage.com.myapplication.MainActivity}: kotlin.TypeCastException: null cannot be cast to non-null type T
```

**Comment by geniusforapp** [comment]
Yes I have checked the code and the proplim with fast adapter inside the drawer layou when we try to creat it it crash because it’s another version i am using fast adapter 4.0.0 and the drawer is 7-alpha2

**Comment by mikepenz** [comment]
which version of FastAdapter do you use? the very latest release?

**Comment by mikepenz** [comment]
please update to  MaterialDrawer 7.0.0-beta01 which uses FastAdapter v4.0.0-rc03 and Android-Iconics v4.0.0-b1
