### ISSUE TITLE
java.lang.IllegalArgumentException: No drawer view found with gravity LEFT

### ISSUE THREAD

**Issue by OuterObsessionSoftware** [mikepenz/MaterialDrawer#2455]
## About this issue

- Briefly describe the issue

After making some simple changes to the MiniDrawerActivity sample, I keep on getting crashes when clicking on the profile picture to close the drawer.

Building the unmodified MiniDrawerActivity sample works fine. I've tried systemically modifying the example to try and pin point what causes the crash with no luck.

Log:
`2019-07-01 11:47:44.631 28108-28108/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shfr.ihit.app.debug, PID: 28108
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shfr.ihit.app.debug/com.shfr.ihit.app.MiniDrawerActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4454)
        at android.view.ViewGroup.addView(ViewGroup.java:4295)
        at android.view.ViewGroup.addView(ViewGroup.java:4252)
        at com.mikepenz.crossfader.Crossfader.build(Crossfader.java:309)
        at com.shfr.ihit.app.MiniDrawerActivity.onCreate(MiniDrawerActivity.java:180)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

- How can the issue be reproduced / sample code

I tried similar code in both Kotlin and Java with same result
Sample Code:
[MiniDrawerActivityJava.txt](https://github.com/mikepenz/MaterialDrawer/files/3343683/MiniDrawerActivityJava.txt)
[MiniDrawerActivityKotlin.txt](https://github.com/mikepenz/MaterialDrawer/files/3343684/MiniDrawerActivityKotlin.txt)

## Details
Used library version 7.0.0-rc01
Used support library version materialize 1.2.1
Used gradle build tools version 29.0.0
Used tooling / Android Studio version 3.4.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by OuterObsessionSoftware** [comment]
Additional Information:
When I try to use .build instead .buildView I get:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shfr.ihit.app.debug/com.shfr.ihit.app.MiniDrawerActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

I think this is happening because I am using crossfader which gets upset if the drawer is inflated automatically.

I still don't understand what change I made to break the sample :/

**Comment by OuterObsessionSoftware** [comment]
Hmm MaterialDrawer v6.1.2 seems to work fine, maybe there's an issue with mixing kotlin/java. I'll use v6.1.2 for now but would still be interested in what's going on.

**Comment by AllanWang** [comment]
I just pasted your kotlin code into the sample's `MiniDrawerActivity` and it works fine.
Your title's exception also doesn't match that of your logs.
In the future, it may also be helpful to paste your code inline using backticks instead of uploading a txt file so others can see it without downloading.

Unless this is still occurring, I think this can be closed.

**Comment by AllanWang** [comment]
The problem might also be with your layouts. As the exception says, you might have attached your view to another parent already

**Comment by OuterObsessionSoftware** [comment]
Thanks for taking a look. I didn't use backticks for my code as I often get annoyed having to scroll for ages through code. I might start using backticks again.

Because I was trying a hundred different permutations in hopes of identifying the problem I was actually getting two different exceptions depending on how I setup the drawer, just a bad copy/paste error.

Anyway I think you're right there must have been some small unintentional change to the layout (or maybe even something else) As I prefer working with Java (despite all the null issues) I'll just stick with V6.1.2 as I don't think there's any super important reason to be using the newer Kotlin release.

**Comment by AllanWang** [comment]
It's still a bit weird if your exact code works with an older version but not with a new one. And correct, as of now the update is primarily just to change to kotlin

**Comment by OuterObsessionSoftware** [comment]
Yes and it's weird how that behavior was only happening when clicking on the profile picture to close the drawer. Like why isn't the same behavior present when closing the drawer with the other buttons?

Anyway not going to waste too much time thinking about it.

**Comment by mikepenz** [comment]
@OuterObsessionSoftware the `ActionBarDrawerToggle` handles the closing/opening internally so the code might slightly differ from directly calling the according open functions on the `DrawerLayout`

but it should actually not make a difference between v6 and v7 :/
