### ISSUE TITLE
Material Library alpha10 incompatible

### ISSUE THREAD

**Issue by anggrayudi** [mikepenz/MaterialDrawer#2499]
## About this issue

This issue appears after updating Google's Material library to `1.1.0-alpha10`:

    implementation 'com.google.android.material:material:1.1.0-alpha10'

However, I have to downgrade it to `1.1.0-alpha09` in order to prevents the error from showing up.

## Details

Library version: `7.0.0-rc06`

### Error message
```
    java.lang.NoSuchMethodError: No virtual method setCornerRadius(F)V in class Lcom/google/android/material/shape/ShapeAppearanceModel; or its super classes (declaration of 'com.google.android.material.shape.ShapeAppearanceModel' appears in /data/app/com.anggrayudi.watercat-CS8DSC6UE2LzyuhDOW5gSg==/base.apk!classes3.dex)
        at com.mikepenz.materialdrawer.model.AbstractDrawerItem.getShapeAppearanceModel(AbstractDrawerItem.kt:419)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.kt:64)
        at com.mikepenz.materialdrawer.model.ExpandableDrawerItem.bindView(ExpandableDrawerItem.kt:88)
        at com.mikepenz.materialdrawer.model.ExpandableDrawerItem.bindView(ExpandableDrawerItem.kt:23)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:21)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:390)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7088)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6000)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6267)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6106)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6102)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4122)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3839)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4392)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1264)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2840)
2019-09-08 23:35:09.326 1400-1400/com.anggrayudi.watercat E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:888)
        at android.view.Choreographer.doFrame(Choreographer.java:819)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:991)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by mikepenz** [comment]
@anggrayudi this was already fixed by @rubengees here: https://github.com/mikepenz/MaterialDrawer/pull/2497

The API broke with the latest alpha update. 

I have not yet released a new release candidate as I am still hoping to get in some improvements for the navigationController support.

**Comment by anggrayudi** [comment]
@mikepenz If that so, we can close this issue.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/releases/tag/v7.0.0-rc07
