### ISSUE TITLE
AppCompat 1.1.0 No virtual method setCornerRadius

### ISSUE THREAD

**Issue by RumataEstorish** [mikepenz/MaterialDrawer#2503]
## About this issue
When updating 'com.google.android.material:material:1.1.0-alpha09' to 'com.google.android.material:material:1.1.0-alpha10'

drawer crashes with exception:
java.lang.NoSuchMethodError: No virtual method setCornerRadius(F)V in class Lcom/google/android/material/shape/ShapeAppearanceModel; or its super classes (declaration of 'com.google.android.material.shape.ShapeAppearanceModel'

at com.mikepenz.materialdrawer.model.AbstractDrawerItem.getShapeAppearanceModel(AbstractDrawerItem.kt:419)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.kt:64)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:51)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:15)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:21)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:390)

**Comment by mikepenz** [comment]
this ticket is a duplicate. This will be fixed in the next RC :)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/releases/tag/v7.0.0-rc07
