### ISSUE TITLE
Now such method error after updating com.google.android.material to version 1.1.0-alpha10

### ISSUE THREAD

**Issue by DenisMakovskyi** [mikepenz/MaterialDrawer#2504]
java.lang.NoSuchMethodError: No virtual method setCornerRadius(F)V in class Lcom/google/android/material/shape/ShapeAppearanceModel; or its super classes (declaration of 'com.google.android.material.shape.ShapeAppearanceModel' appears in /data/app/ua.com.wl.faynomarket.debug-AOMAadZOGn49sGNndMtejA==/base.apk)
        at com.mikepenz.materialdrawer.model.AbstractDrawerItem.getShapeAppearanceModel(AbstractDrawerItem.kt:419)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.kt:64)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:51)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:15)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:21)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:390)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7098)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6010)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6277)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6116)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6112)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4132)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4402)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1264)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
2019-09-12 16:03:42.922 6327-6327/ua.com.wl.faynomarket.debug E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3366)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2830)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1876)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8499)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/releases/tag/v7.0.0-rc07
