### ISSUE TITLE
Resources$NotFoundException at ImageHolder.java:103

### ISSUE THREAD

**Issue by usmanfarhat** [mikepenz/MaterialDrawer#2514]
## About this issue
I have recently updated android support libraries and when I deployed my app, I started getting these crashes at ImageHolder.java:103. The app works fine for me and for most users, but several users are getting this crash. The app worked perfectly before this change. Resources are valid too.

Another thing I changed is that I published using Android App Bundle.

This is the stack trace:
```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f08008a
       at android.content.res.Resources.getValue(Resources.java:1572)
       at android.content.res.VivoResources.getValue(VivoResources.java:191)
       at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:252)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
       at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:103)
       at com.mikepenz.materialdrawer.holder.ImageHolder.decideIcon(ImageHolder.java:135)
       at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:98)
       at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
       at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:18)
       at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:28)
       at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:741)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2825)
       at android.view.View.layout(View.java:16947)
       at android.view.ViewGroup.layout(ViewGroup.java:5711)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2547)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2250)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6748)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:713)
       at android.view.Choreographer.doFrame(Choreographer.java:648)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5790)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1015)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

Here is the relevant code:

```
		PrimaryDrawerItem allFiles = new PrimaryDrawerItem()
				.withName("All Files")
				.withIdentifier(DRAWER_IDENTIFIER_ALL_FILES)
				//  .withSetSelected(true)
				.withIcon(R.drawable.ic_music_note_white_24dp)
				.withIconTintingEnabled(true)
				.withTag(DRAWER_ALL_FILES);
		PrimaryDrawerItem allVideos = new PrimaryDrawerItem()
				.withName("Videos")
				.withIdentifier(DRAWER_IDENTIFIER_VIDEOS)
				//  .withSetSelected(true)
				.withIcon(R.drawable.ic_movie_white_24dp)
				.withIconTintingEnabled(true)
				.withTag(DRAWER_ALL_VIDEOS);
		PrimaryDrawerItem header = new PrimaryDrawerItem()
				.withName("Stealth Player")
				.withBadge(version)
				.withDisabledTextColorRes(R.color.colorAudioIcon)
				.withSelectable(false)
				.withEnabled(false);

// ... and other items

drawer = new DrawerBuilder()
				//    .withAccountHeader(headerResult)
				.withActivity(this)
				.withToolbar(myToolbar)
				.addDrawerItems(
						header,
						new DividerDrawerItem(),
						universal,
						allFiles,
						allVideos,
						folders,
						invite,
						about,
						settings
				)
				.withOnDrawerItemClickListener(listener)
				.withSelectedItem(DRAWER_IDENTIFIER_ALL_FILES)
				.build();

```

## Details
- [ ] Used library version: com.mikepenz:materialdrawer:6.1.2
- [ ] Used support library version: androidx.appcompat:appcompat:1.1.0
- [ ] Used gradle build tools version: com.android.tools.build:gradle:3.5.0
- [ ] Used tooling / Android Studio version: 3.5
- [ ] Other used libraries, potential conflicting libraries: Following:
```
dependencies {
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.browser:browser:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.google.firebase:firebase-perf:19.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.firebase:firebase-invites:17.0.0'
    implementation 'com.google.firebase:firebase-ads:18.2.0'
    implementation 'com.google.firebase:firebase-crash:16.2.1'
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation "com.mikepenz:materialdrawer:6.1.2"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'

    implementation 'com.android.billingclient:billing:2.0.3'
    implementation 'com.github.codekidX:storage-chooser:2.0.3'
    implementation 'com.google.android.ads.consent:consent-library:1.0.7'
    implementation 'com.adcolony:sdk:3.3.11'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'com.google.ads.mediation:adcolony:3.3.11.0'

    implementation 'com.android.support:multidex:1.0.3'

    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'


}
```

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues) 🆗  
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app) 🆗 
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md) 🆗 
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases) 🆗 
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md) 🆗 
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md) 🆗

**Comment by mikepenz** [comment]
Are the crashes limited to a specific manufacturer?

**Comment by mikepenz** [comment]
Also there seems to be problems with app bundle releases :/  (not related to MaterialDrawer)
A different user also reported that sometimes icons are missing in app bundle releases

**Comment by usmanfarhat** [comment]
Crashes are mostly limited to Galaxy A5 and some vivo devices. I understand that both of these often cause unforeseen crashes. If I see more devices crash, I may try to revert back to apk releases.

However, do you think that this can be avoided by using a try/catch logic in ImageHolder.java ?

**Comment by mikepenz** [comment]
Well having it surrounded with a try and catch sounds problematic as the icon is set for a reason and you want it to be displayed. you can try to load the icon on your side, and set as drawable to the drawer. 

then you are in control of the loading

**Comment by mikepenz** [comment]
have you found more details about the crashes cause? 

Closing as it seems to be not related directly to the drawer, but more to the resource provided
