### ISSUE TITLE
App crash in Android 9

### ISSUE THREAD

**Issue by MuraliThangavel** [mikepenz/MaterialDrawer#2519]
## About this issue

Application crashes while opening navigation drawer in Android 9 mobiles.

## Details
- [  implementation 'com.mikepenz:actionitembadge:3.2.2@aar' ] Used library version
- [ 27.0.3] Used gradle build tools version
- [ 3.5] Used tooling / Android Studio version

```
2019-11-02 17:11:23.873 28511-28511/com.etutorel.rkss E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.etutorel.rkss, PID: 28511
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:390)
        at android.graphics.Canvas.saveLayer(Canvas.java:467)
        at com.mikepenz.materialdrawer.view.BezelImageView.onDraw(BezelImageView.java:213)
        at android.view.View.draw(View.java:20443)
        at android.view.View.updateDisplayListIfDirty(View.java:19263)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.updateDisplayListIfDirty(View.java:19254)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.updateDisplayListIfDirty(View.java:19254)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.updateDisplayListIfDirty(View.java:19254)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4581)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.draw(View.java:20446)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3987)
        at android.view.View.updateDisplayListIfDirty(View.java:19263)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.draw(View.java:20446)
        at com.mikepenz.materialize.view.ScrimInsetsRelativeLayout.draw(ScrimInsetsRelativeLayout.java:77)
        at android.view.View.updateDisplayListIfDirty(View.java:19263)
        at android.view.View.draw(View.java:20137)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4511)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4282)
        at android.view.View.draw(View.java:20446)
        at android.view.View.updateDisplayListIfDirty(View.java:19263)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4490)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4463)
        at android.view.View.updateDisplayListIfDirty(View.java:19218)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4490)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4463)
        at android.view.View.updateDisplayListIfDirty(View.java:19218)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4490)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4463)
        at android.view.View.updateDisplayListIfDirty(View.java:19218)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4490)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4463)
        at android.view.View.updateDisplayListIfDirty(View.java:19218)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4490)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4463)
        at android.view.View.updateDisplayListIfDirty(View.java:19218)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3413)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3206)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2575)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7413)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
2019-11-02 17:11:23.874 28511-28511/com.etutorel.rkss E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:807)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1049)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7055)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

## Checklist
![image](https://user-images.githubusercontent.com/55432699/68070312-ddd09e00-fd92-11e9-86e0-f475535f0137.png)

canvas saveFlags depricated

**Comment by mikepenz** [comment]
These flags are not applied anymore on recent releases.

Please update the MaterialDrawer 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/view/BezelImageView.kt

**Comment by mikepenz** [comment]
Also v7 does not contain it anymore:
https://github.com/mikepenz/MaterialDrawer/blob/v7.0.0-rc08/library/src/main/java/com/mikepenz/materialdrawer/view/BezelImageView.kt
Neither v6.0.9 or v6.1.2
https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/view/BezelImageView.java


Sadly I can only support recent releases
