### ISSUE TITLE
I cannot start my application or use the dependency when updating to the latest version

### ISSUE THREAD

**Issue by mak3ru-in0ch1** [mikepenz/MaterialDrawer#2521]
Recently I was using **Material Drawer 7.0.0-rc08** _without any problem_, but gradle notified me that there was a new update, **version 8.0.0-a01** but now the problem is coming.

**I have not changed the code** as I had before with version **7.0.0-rc08** but now when I run my application with the version of **Material Drawer 8.0.0-a01 I close the application and send me the following error via logcat**:

```
2019-11-04 11:27:04.552 2843-2843/com.akatsuki.makeru E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.akatsuki.makeru, PID: 2843
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.akatsuki.makeru/com.akatsuki.makeru.Home}: android.view.InflateException: Binary XML file line #1: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.InflateException: Binary XML file line #1: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
     Caused by: android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
```
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.mikepenz.materialdrawer.AccountHeaderBuilder.withAccountHeader(AccountHeaderBuilder.kt:718)
        at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.kt:867)
        at com.akatsuki.makeru.Home.initializePage(Home.java:198)
        at com.akatsuki.makeru.Home.onCreate(Home.java:113)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

I see that the error is due to the **AccountHeaderBuilder** of my application, but I do not see the problem, **any changes I should make for this new version?**

**Attached AccountHeaderBuilder code:**

```
mAkatsukiMainMenuHeader = new AccountHeaderBuilder()
                .withActivity(Home.this)
                .withTextColor(Color.WHITE)
                .withDividerBelowHeader(false)
                .withTextColor(ContextCompat.getColor(Home.this, R.color.colorTextNormal))
                .build();
```

If you are kind enough to respond shortly because I need to repair it soon. Thank you very much in advance. 

Notes:
Use **Java as programming**  language and **Android Studio 3.5.1** .

**Comment by mikepenz** [comment]
a01 is a alpha release which has a new API and will not work as prior releases:
https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.0.0-a01

**Comment by mikepenz** [comment]
@mak3ru-in0ch1 you should definitely stay at the rc08.

v8 will still need a few weeks to be in a rc state

**Comment by mak3ru-in0ch1** [comment]
Okay, I hope you can update the README.md so I can make the corresponding changes. :)
