### ISSUE TITLE
Crash when loading images with Glide.asBitmap()

### ISSUE THREAD

**Issue by connyduck** [mikepenz/MaterialDrawer#2579]
## About this issue

- when I load images with Glide and add `.asBitmap()` in the `DrawerImageLoader`, the app crashes. This did not happen with Materialdrawer 6. I did not change the Glide version.
- to reproduce, add `.asBitmap()` to the sample app `DrawerImageLoader` after `GlideApp.with(imageView.context)` here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.kt#L42
- `asBitmap` is needed to stop gifs from animating

<details>
  <summary>Stacktrace</summary>
  
  ```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikepenz.materialdrawer.app.debug/com.mikepenz.materialdrawer.app.DrawerActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter bm
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter bm
        at com.mikepenz.materialdrawer.view.BezelImageView.setImageBitmap(Unknown Source:2)
        at com.bumptech.glide.request.target.BitmapImageViewTarget.setResource(BitmapImageViewTarget.java:33)
        at com.bumptech.glide.request.target.BitmapImageViewTarget.setResource(BitmapImageViewTarget.java:10)
        at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:124)
        at com.bumptech.glide.request.target.ImageViewTarget.onLoadStarted(ImageViewTarget.java:65)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:256)
        at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:43)
        at com.bumptech.glide.RequestManager.track(RequestManager.java:674)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:641)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:700)
        at com.mikepenz.materialdrawer.app.CustomApplication$onCreate$1.set(CustomApplication.kt:42)
        at com.mikepenz.materialdrawer.util.DrawerImageLoader.setImage(DrawerImageLoader.kt:44)
        at com.mikepenz.materialdrawer.view.BezelImageView.setImageURI(BezelImageView.kt:278)
        at com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.kt:62)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.setImageOrPlaceholder(AccountHeaderView.kt:1011)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.buildProfiles$materialdrawer(AccountHeaderView.kt:895)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.updateHeaderAndList(AccountHeaderView.kt:1126)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.apply(AccountHeaderView.kt:1212)
        at com.mikepenz.materialdrawer.app.DrawerActivity.onCreate(DrawerActivity.kt:61)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
  ```
  
</details>

## Details
- Used library version: 8.0.0 / current develop
- Other used libraries, potential conflicting libraries: tried both Glide 4.11.0 and 4.10.0, same problem

**Comment by mikepenz** [comment]
We will update the `BezelImageView` to allow for `null` `Bitmap`s

**Comment by mikepenz** [comment]
Adjusted the view in v8.0.1

**Comment by connyduck** [comment]
Awesome! Thx for the great Kotlin migration and the quick response time!
