### ISSUE TITLE
Error while migrating to v8

### ISSUE THREAD

**Issue by Kashish-Sharma** [mikepenz/MaterialDrawer#2581]
## About this issue

- Tried migrating to v8 from v7, app wont start and crashes.

## Details
- [ 8.0.1] Used library version
- [ 3.5.3] Used gradle build tools version
- [3.6 ] Used tooling / Android Studio version

I'm getting this error when I migrated my code from v7 to v8:
```
rocess: com.cinopsys.movieshows, PID: 10804
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cinopsys.movieshows/com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity}: android.view.InflateException: Binary XML file line #67 in com.cinopsys.movieshows:layout/activity_movies: Binary XML file line #67 in com.cinopsys.movieshows:layout/activity_movies: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: android.view.InflateException: Binary XML file line #67 in com.cinopsys.movieshows:layout/activity_movies: Binary XML file line #67 in com.cinopsys.movieshows:layout/activity_movies: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: android.view.InflateException: Binary XML file line #67 in com.cinopsys.movieshows:layout/activity_movies: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: java.lang.reflect.InvocationTargetException
2020-04-12 14:10:56.414 18892-18892/com.cinopsys.movieshows E/AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400ca a=7}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:405)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:55)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(Unknown Source:6)
```

Here's the layout
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.drawerlayout.widget.DrawerLayout
    android:id="@+id/activity_movie_root_layout"
    android:fitsSystemWindows="true"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/backgroundColor">

        <com.google.android.material.appbar.AppBarLayout
            android:theme="@style/AppTheme.AppBarOverlay"
            android:id="@+id/activity_movies_app_bar_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <androidx.appcompat.widget.Toolbar
                app:layout_scrollFlags="scroll|enterAlways|snap"
                android:id="@+id/activity_movies_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light">
                <TextView
                    android:textSize="28sp"
                    android:fontFamily="@font/pacifico_regular"
                    android:textColor="@color/white"
                    android:text="@string/app_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content" />
            </androidx.appcompat.widget.Toolbar>

            <com.google.android.material.tabs.TabLayout
                app:tabIndicatorHeight="4dp"
                style="@style/TabAppearance"
                android:layout_below="@id/activity_movies_toolbar"
                android:id="@+id/activity_movies_tab_layout"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:tabMode="scrollable"
                app:tabGravity="fill"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
            </com.google.android.material.tabs.TabLayout>

        </com.google.android.material.appbar.AppBarLayout>

        <androidx.viewpager2.widget.ViewPager2
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:id="@+id/activity_movies_view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
        </androidx.viewpager2.widget.ViewPager2>

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

    <com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
        android:id="@+id/slider_movies"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:fitsSystemWindows="true" />

</androidx.drawerlayout.widget.DrawerLayout>
```

Need help to fix this. Thanks!

**Comment by Kashish-Sharma** [comment]
Changing the base theme fixed the issue!

**Comment by dexion** [comment]
I have the same problem. @Kashish-Sharma , on which theme do you changed? Or which params?

**Comment by Kashish-Sharma** [comment]
Here
```
​<​style​ ​name​=​"​SampleApp.DayNight​"​ ​parent​=​"​Theme.MaterialComponents.DayNight.NoActionBar​"​>
    ...
    <​item​ ​name​=​"​materialDrawerStyle​"​>@style/Widget.MaterialDrawerStyle</​item​>
    <​item​ ​name​=​"​materialDrawerHeaderStyle​"​>@style/Widget.MaterialDrawerHeaderStyle</​item​>
</​style​>
```

Add this to your styles.

**Comment by dexion** [comment]
I'm already  have those strings in my style.

**Comment by Kashish-Sharma** [comment]
Yup! I've mentioned parent theme also in the above comment!

If you have any idea on how use a custom account header view in v8 of material drawer, then please help me.
