### ISSUE TITLE
Setting a custom AccountHeaderView

### ISSUE THREAD

**Issue by Kashish-Sharma** [mikepenz/MaterialDrawer#2582]
## About this issue

- I have a layout named `material_drawer_compact_header`, how to use it as custom `AccountHeaderView`

## Details
- [8.0.1 ] Used library version
- [3.5.3 ] Used gradle build tools version
- [ 3.6] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
This is already the same layout name as the original. so it will be automatically overwriten by the build tooling

You can build you header programatically as shown here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.kt#L102

or you set the compact style via theme
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/themes.xml#L27
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/styles.xml#L23-L27

**Comment by Kashish-Sharma** [comment]
I've tried setting it via theme and getting this error:
```
2020-04-13 13:27:35.719 7624-7624/com.cinopsys.movieshows E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cinopsys.movieshows, PID: 7624
    java.lang.IllegalStateException: findViewById(R.id.materi…unt_header_current_badge) must not be null
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.<init>(AccountHeaderView.kt:414)
        at com.mikepenz.materialdrawer.widget.AccountHeaderView.<init>(AccountHeaderView.kt:35)
        at com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity.getAccountHeader(MoviesActivity.kt:592)
        at com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity.setupDrawer(MoviesActivity.kt:410)
        at com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity.access$setupDrawer(MoviesActivity.kt:102)
        at com.cinopsys.movieshows.ui.Activities.Movie.MoviesActivity$setupProfileItem$1.invokeSuspend(MoviesActivity.kt:378)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

My account header
```kotlin
private fun getAccountHeader(profileDrawerItem: ProfileDrawerItem): AccountHeaderView {
        return AccountHeaderView(this).apply{
            attachToSliderView(mSlider)
            addProfiles(profileDrawerItem)
        }
    }
```


After setting account header:
```
        mHeaderStatsLinearLayout = mSlider.accountHeader!!.findViewById(R.id.material_drawer_account_header_user_stats)
        mHeaderWatchedMoviesCount = mSlider.accountHeader!!.findViewById(R.id.material_drawer_account_header_watched_items)
        mHeaderWatchedMoviesHours = mSlider.accountHeader!!.findViewById(R.id.material_drawer_account_header_watched_time)
        mHeaderRatedMoviesCount = mSlider.accountHeader!!.findViewById(R.id.material_drawer_account_header_rated_items)
```

**Comment by mikepenz** [comment]
@Kashish-Sharma if you overwrite the existing layout for the account header you have to keep all views and their identifiers. you are not allowed to remove any. 

if you want to create your very own header (which is no account header) you. may just provide a custom header to the drawer

**Comment by Kashish-Sharma** [comment]
Works, Thanks!
Should have read the logs more carefully.
