### ISSUE TITLE
Resources$NotFoundException when adding badging

### ISSUE THREAD

**Issue by ardevd** [mikepenz/MaterialDrawer#2592]
Using version 7.0.0 my app crashes when trying to add a badge.

```java
        PrimaryDrawerItem itemAlerts = new PrimaryDrawerItem()
                .withIdentifier(DRAWER_ITEM_ALERTS)
                .withName(getString(R.string.base_alerts))
                .withIconTintingEnabled(true)
                .withIcon(R.drawable.ic_alert);

            itemAlerts.withBadge(10);
```
The following stacktrace is produced. 

```
04-24 09:05:43.121  7007  7007 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0xa
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:367)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.TextView.setText(TextView.java:6402)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:59)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.materialize.holder.StringHolder.applyToOrHide(StringHolder.java:86)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.materialdrawer.holder.StringHolder$Companion.applyToOrHide(StringHolder.kt:22)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:54)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:15)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:21)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:395)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1264)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.View.layout(View.java:22105)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3338)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2815)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1935)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8023)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:902)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1091)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7695)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-24 09:05:43.121  7007  7007 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by ardevd** [comment]
Nvm, realized I can't pass an integer value to `withBadge`. Must be a String. My bad.
