### ISSUE TITLE
App crash InflateException

### ISSUE THREAD

**Issue by paradoxfm** [mikepenz/MaterialDrawer#2619]
```
	<com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
		android:id="@+id/slider"
		android:layout_width="wrap_content"
		android:layout_height="match_parent"
		android:theme="@style/Widget.MaterialDrawerStyleCustom"
		android:layout_gravity="start"/>
```

```
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400d2 a=12}
        at android.content.res.TypedArray.getDrawableForDensity(Unknown Source:67)
        at android.content.res.TypedArray.getDrawable(Unknown Source:1)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:399)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:49)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(Unknown Source:6)
        	... 29 more
```

**Comment by paradoxfm** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/2589
