### ISSUE TITLE
Quick start guide doesn't work properly (or what am I doing wrong?)

### ISSUE THREAD

**Issue by CakeWalker1337** [mikepenz/MaterialDrawer#2632]
Hello! I am using material drawer first time and have struggled with the issue: when I implement drawer according to setup guide from README, I get the exception while inflating the layout:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.retroblade.navdrawertest, PID: 8091
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.retroblade.navdrawertest/com.retroblade.navdrawertest.MainActivity}: android.view.InflateException: Binary XML file line #28 in com.retroblade.navdrawertest:layout/activity_main: Binary XML file line #28 in com.retroblade.navdrawertest:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #28 in com.retroblade.navdrawertest:layout/activity_main: Binary XML file line #28 in com.retroblade.navdrawertest:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: android.view.InflateException: Binary XML file line #28 in com.retroblade.navdrawertest:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:695)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.retroblade.navdrawertest.MainActivity.onCreate(MainActivity.kt:9)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300bd a=6}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:399)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:49)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(Unknown Source:6)
        	... 28 more

```
I tried to compare sample project with mine one, but I can't see any difference:( actually, in the other issue I found is said that similar exception can be caused of wrong styles. Though, in my case all was set up according to quickstart guide. Please, help:(

The test example for this issue: https://github.com/CakeWalker1337/MaterialDrawerTest-report

P.S. You're awesome, Mike! Thanks for your work!

**Comment by CakeWalker1337** [comment]
Oh, well, I found a mistake: the app style **MUST BE** inherited from "**Theme.MaterialComponents.DayNight.NoActionBar**". Read guides carefully ;p
Maybe it would help someone:)

**Comment by mikepenz** [comment]
Glad you were able to resolve the problem :)
