### ISSUE TITLE
Issue inflating the MaterialDrawerSliderView while migrating from v6 to v8

### ISSUE THREAD

**Issue by carlos-mg89** [mikepenz/MaterialDrawer#2673]
## About this issue

- Issue inflating with migration from 6.1.2 to latest v8 of the library

So, I have followed all the steps in the readme for the setup:

**1. I've checked all the dependencies are in my app's build.gradle:**

```
implementation "androidx.appcompat:appcompat:1.2.0"
implementation 'androidx.annotation:annotation:1.1.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
implementation 'androidx.recyclerview:recyclerview:1.1.0'
implementation "com.google.android.material:material:1.2.1"

implementation 'com.mikepenz:materialdrawer:8.1.7'
implementation "com.mikepenz:materialdrawer-nav:8.1.7"
implementation "com.mikepenz:materialdrawer-iconics:8.1.7"
```

**2. I have added the Drawer into the XML:**

In two ways, I tried first to include the DrawerLayout view as the last child of my root's activity layout, and as the root's parent as well. Both ways gave me the error below.

**3. I have added the DrawerStyle to my theme exactly as detailed in the readme**

Any ideas???

## Additional details:

* I've already checked similar issues: https://github.com/mikepenz/MaterialDrawer/issues?q=is%3Aissue+Error+inflating+class+com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView with no luck
* I've checked the migration guide, but couldn't see anything there that leads me to the resolution of my issue.
* I've checked as well the sample app: https://github.com/mikepenz/MaterialDrawer/tree/develop/app
* And I've commented the code that adds the AccountHeaderView and the list of IDrawerItem (mainly PrimaryDrawerItem and SecondaryDrawerItem), just in case the error was there. I faced soem compiling issues, due to the significant changes between the code base of v6 and v8. However, I think I've pretty much migrated it successfully at first glance. Anyway, this is out of the scope of this issue, since commenting the code that adds all those items into the MaterialDrawerSliderView has been commented and the error persists.

## Details
- [ ] Used library version: 8.1.7
- [ ] Used support library version: 30.0.0
- [ ] Used gradle build tools version: 4.1.0
- [ ] Used tooling / Android Studio version: 4.1
- [ ] Other used libraries, potential conflicting libraries: I'm using many libraries, could share the complete list if needed

This is my activity layout:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.drawerlayout.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/mapActivityDrawerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:animateLayoutChanges="true"
    tools:context=".view.activities.MapActivity"
    android:fitsSystemWindows="true">

    <RelativeLayout
        android:id="@+id/mapActivityLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animateLayoutChanges="true"
        tools:context=".view.activities.MapActivity">

        <!-- Some other views are here but totally irrelevant in theory (they all get inflated properly while using v6 of this library) -->

        <com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
            android:id="@+id/slider"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:fitsSystemWindows="true" />

    </RelativeLayout>

</androidx.drawerlayout.widget.DrawerLayout>
```

Error log:

```
2020-10-29 10:22:07.596 22256-22256/com.walkaholic.hikeapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.walkaholic.hikeapp, PID: 22256
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.walkaholic.hikeapp/com.walkaholic.hikeapp.view.activities.MapActivity}: android.view.InflateException: Binary XML file line #250 in com.walkaholic.hikeapp:layout/map_activity: Binary XML file line #250 in com.walkaholic.hikeapp:layout/map_activity: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #250 in com.walkaholic.hikeapp:layout/map_activity: Binary XML file line #250 in com.walkaholic.hikeapp:layout/map_activity: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: android.view.InflateException: Binary XML file line #250 in com.walkaholic.hikeapp:layout/map_activity: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:455)
        at android.app.Activity.setContentView(Activity.java:3468)
        at com.walkaholic.hikeapp.view.activities.MapBaseActivity.onCreate(MapBaseActivity.kt:161)
        at com.walkaholic.hikeapp.view.activities.MapActivity.onCreate(MapActivity.kt:56)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-10-29 10:22:07.598 22256-22256/com.walkaholic.hikeapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300c4 a=7}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:997)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:399)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:49)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(Unknown Source:6)
```

**Comment by mikepenz** [comment]
@carlos-mg89 which theme does your app use? 

The theme the activity hosting the drawer should specify the drawer theme similar like:

```
// define the custom styles for the theme
<style name="SampleApp" parent="Theme.MaterialComponents.Light.NoActionBar">
    ...
    <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyleCustom</item>
    <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyleCustom</item>
    ...
</style>
```

Also the theme's parent should be the `MaterialComponents` one

**Comment by carlos-mg89** [comment]
That was the issue. My bad! I added the style, but I wasn't using it in my activity.

Now I can see that my migration is not completed, since the MaterialDrawer appears totally white. So I might have missed something while migrating the older drawer items.

Thanks for the assistance!
