### ISSUE TITLE
Binary XML file line #73: Error inflating class com.mikepenz.materialdrawer.widget

### ISSUE THREAD

**Issue by kaushiksa** [mikepenz/MaterialDrawer#2752]
Getting this error. I am using version 8.4.4 . 
```
.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: android.view.InflateException: Binary XML file line #73: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.projects.finzen.MainActivity.onCreate(MainActivity.kt:27)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

dependencies:

```
implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.5'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
    implementation 'androidx.annotation:annotation:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation platform('com.google.firebase:firebase-bom:28.4.2')
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.6.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation 'com.google.firebase:firebase-auth:21.0.1'
    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.5"
    implementation "androidx.navigation:navigation-ui-ktx:2.3.5"
    implementation "androidx.viewpager2:viewpager2:1.0.0"
    implementation 'me.relex:circleindicator:2.1.6'
    implementation 'com.airbnb.android:lottie:4.2.0'
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.5" // Navigation
    implementation "androidx.navigation:navigation-ui-ktx:2.3.5" // Navigation
    implementation "org.koin:koin-android:2.0.0-beta-1"
    testImplementation "org.koin:koin-test:2.0.0"
    implementation 'com.google.code.gson:gson:2.8.8' // Gson
    implementation 'com.github.AppIntro:AppIntro:6.1.0'
    implementation "androidx.datastore:datastore-preferences:1.0.0"

//    for drawer
    implementation "com.mikepenz:materialdrawer:8.4.4"

//required support lib modules
    implementation "androidx.recyclerview:recyclerview:1.2.1"
// Add for NavController support
    implementation "com.mikepenz:materialdrawer-nav:8.4.4"

// Add for Android-Iconics support
    implementation "com.mikepenz:materialdrawer-iconics:8.4.4"

```
    

Have also added styles in theme

**Comment by mikepenz** [comment]
@kaushiksa can you please double check that the theme is really used?

Otherwise I'd please need a sample app to reproduce the project, as I seem to not be able to reproduce it in the sample app itself

**Comment by hussein16hamada** [comment]
i have the same issue

**Comment by mikepenz** [comment]
@hussein16hamada please provide which theme is used, which version of the library. 

As noted here: https://github.com/mikepenz/MaterialDrawer/tree/issue/2752 I was not able to reproduce this

**Comment by hussein16hamada** [comment]
version is 8.4.5  and this is the theme
    <style name="AppTheme.Base" parent="@style/Theme.AppCompat.Light.NoActionBar">

        <item name="colorPrimary">@color/lightblue</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="actionModeBackground">@color/accent</item>
        <item name="android:fontFamily">@font/uthman</item>
        <item name="android:textColor">#5c9093</item>
        <item name="android:statusBarColor" tools:ignore="NewApi">@color/lightblue</item>
        <item name="android:navigationBarColor" tools:ignore="NewApi">@color/lightblue</item>


    </style>

**Comment by mikepenz** [comment]
@hussein16hamada the library (in v8.x) requires a `MaterialComponents` theme as base:

https://github.com/mikepenz/MaterialDrawer/tree/v8.4.5#3-add-the-drawerstyle-to-your-theme

v9.x will require a `Material3` theme as base.

**Comment by hussein16hamada** [comment]
okay thanks

**Comment by hussein16hamada** [comment]
can you tel me how to change the style ?
because i am trying to change background and other things but not working

    <style name="AppTheme.Base" parent="@style/Theme.MaterialComponents.Light.NoActionBar">

        <item name="colorPrimary">@color/lightblue</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="actionModeBackground">@color/accent</item>
        <item name="android:fontFamily">@font/uthman</item>
        <item name="android:textColor">#5c9093</item>
        <item name="android:statusBarColor" tools:ignore="NewApi">@color/lightblue</item>
        <item name="android:navigationBarColor" tools:ignore="NewApi">@color/lightblue</item>

        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyle</item>
        <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyle</item>

    </style>

    <style name="Widget.MaterialDrawerStyleCustom" parent="Widget.MaterialDrawerStyle">
        
        <item name="materialDrawerBackground">#AD2B2B</item>
        <item name="materialDrawerPrimaryText">@color/primary_dark</item>
        <item name="materialDrawerSecondaryText">@color/gray</item>
        <item name="materialDrawerDividerColor">#B71C1C</item>
        <item name="materialDrawerSelectedBackgroundColor">#1FF1433C</item>
    </style>

**Comment by mikepenz** [comment]
@hussein16hamada I can't assist with the setup for the material theme for a whole application itself. Only for this library related matter. 

Please refer to the official google docs for the `MaterialComponents` theme: https://material.io/develop/android

**Comment by mikepenz** [comment]
Closing due to inactivity. Please (original author) report back if this is still a concern
