### ISSUE TITLE
Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView

### ISSUE THREAD

**Issue by nachiket96** [mikepenz/MaterialDrawer#2804]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.almasons.giniLive/com.almasons.gini.activities.MainActivity}: android.view.InflateException: Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #284 in com.almasons.giniLive:layout/activity_main: Error inflating class com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.almasons.gini.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:153)
                                                                                                    	at com.almasons.gini.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:147)
                                                                                                    	at com.almasons.gini.activities.MainActivity.onCreate(MainActivity.kt:192)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2024-04-05 14:40:45.448 11298-11298 AndroidRuntime          com.almasons.giniLive                E  Caused by: android.view.InflateException: Binary XML file line #1 in com.almasons.giniLive:layout/material_drawer_item_toggle: Binary XML file line #1 in com.almasons.giniLive:layout/material_drawer_item_toggle: Error inflating class x
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #1 in com.almasons.giniLive:layout/material_drawer_item_toggle: Error inflating class x
                                                                                                    Caused by: java.lang.ClassNotFoundException: android.view.x
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:819)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
                                                                                                    	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:917)
                                                                                                    	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                                                                                                    	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
                                                                                                    	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.createContent(MaterialDrawerSliderView.kt:547)
                                                                                                    	at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:402)
                                                                                                    	at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:48)
                                                                                                    	at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:0)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.almasons.gini.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:153)
                                                                                                    	at com.almasons.gini.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:147)
                                                                                                    	at com.almasons.gini.activities.MainActivity.onCreate(MainActivity.kt:192)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7893)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7880)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2024-04-05 14:40:45.448 11298-11298 AndroidRuntime          com.almasons.giniLive                E  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file "/data/app/com.almasons.giniLive-3C-PCPQzsCIcg0DTw3adiw==/base.apk"],nativeLibraryDirectories=[/data/app/com.almasons.giniLive-3C-PCPQzsCIcg0DTw3adiw==/lib/arm64, /data/app/com.almasons.giniLive-3C-PCPQzsCIcg0DTw3adiw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by nachiket96** [comment]
it was working fine suddenly this issue came now

**Comment by mikepenz** [comment]
```
2024-04-05 14:40:45.448 11298-11298 AndroidRuntime com.almasons.giniLive E Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.x" on path: DexPathList[[zip file
```

Appears to be related to either obfuscation or something similar. Based on the crash log, this is unrelated to this project.

**Comment by mikepenz** [comment]
Close due to inactivity
