### ISSUE TITLE
ScrimInsetsFrameLayout.java line 85 StackOverflowError

### ISSUE THREAD

**Issue by NodensN** [mikepenz/MaterialDrawer#308]
Hello Mike how are you ? 
I have this issue on my Crashlytics dashboard, I use the 2.9.5 release. 
The device was an Sony C6603 on Android 4.4.4 

Have you any idea where it could come from ? 

Thanks in advance 

```
com.mikepenz.materialdrawer.view.ScrimInsetsFrameLayout.draw
java.lang.StackOverflowError
       at android.view.GLES20Canvas.<init>(GLES20Canvas.java:101)
       at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:39)
       at android.view.GLES20RecordingCanvas.obtain(GLES20RecordingCanvas.java:45)
       at android.view.GLES20DisplayList.start(GLES20DisplayList.java:61)
       at android.view.View.getDisplayList(View.java:13471)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:2735)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14616)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.mikepenz.materialdrawer.view.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:85)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13505)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.View.draw(View.java:14330)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14616)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2333)
       at android.view.View.getDisplayList(View.java:13510)
       at android.view.View.getDisplayList(View.java:13552)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5622)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5135)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mikepenz** [comment]
How do you init the Drawer?

**Comment by NodensN** [comment]
In my MainActivity's onResume function, I only init the Drawer if I'm logged in.

headerResult = new AccountHeader()
                .withActivity(MainActivity.this)
                .withHeaderBackground(ResourcesCompat.getDrawable(getResources(), R.drawable.bg_menu, null))
                .withHeaderBackgroundScaleType(ImageView.ScaleType.CENTER_CROP)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
...
}).build();

drawerResult = new Drawer()
                .withActivity(MainActivity.this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggle(false)
                .withAccountHeader(headerResult)
                .addDrawerItems(
...
                        )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
...
}).build();

**Comment by mikepenz** [comment]
@NodensN i would recommend to create it in the `onCreate` method so it won't be created again if it is not necessary. 

hmmm else looks everything fine. Haven't had such an issue with my apps live in the playstore either.

**Comment by NodensN** [comment]
@mikepenz Ok will do that and let you know if I have another issue

**Comment by mikepenz** [comment]
@NodensN normally you should only create the drawer in the onCreate once, as long as the current view exists. If the view is recreated the drawer also needs to be recreated. No need to do it inside onResume().

**Comment by mikepenz** [comment]
@NodensN i will close this. Just report back if you still see this issue.
