### ISSUE TITLE
Multi Drawer Selection

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#314]
On Opening Right Drawer If I press Home or Arrow Vector then instead of Closing Right Drawer the Left Drawer is get open.
I want if Right Drawer is open then if i press Home Button in Toolbar then Right Drawer should be Close & then if it's not opened then Left Drawer should be open

**Comment by mikepenz** [comment]
@patelakshay13890 perhaps you can add screenshots. I don'T understand which vectors you mean. and what you want to achieve.

**Comment by mikepenz** [comment]
Ok i found your FC. It is because the `ActionBarDrawerToggle` (which is created by Android and included in the support libs) won't handle a different Drawer than a `LEFT` sided Drawer. This means you have to handle the ActionBarDrawerToggle, or to be more specific the icon and the navigation up there, on your own. To do this just don't pass the `Toolbar` to the MaterialDrawer and handle it as you would with any other `DrawerLayout`.


Here the FC. You can see the message on the top.

** No drawer view found with gravity LEFT**
```
 java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
            at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1322)
            at android.support.v7.app.ActionBarDrawerToggle.toggle(ActionBarDrawerToggle.java:289)
            at android.support.v7.app.ActionBarDrawerToggle.access$100(ActionBarDrawerToggle.java:65)
            at android.support.v7.app.ActionBarDrawerToggle$1.onClick(ActionBarDrawerToggle.java:201)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by mikepenz** [comment]
@patelakshay13890 i close this for now. please reopen if you have more information
