### ISSUE TITLE
Exception ScrimInsetsLayout

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#369]
I just found the following Exception in my CrashlyticsAccount:

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
       at android.support.v7.widget.RecyclerView.computeVerticalScrollRange(RecyclerView.java:1376)
       at android.view.View.onDrawScrollBars(View.java:12943)
       at android.view.View.draw(View.java:15237)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:2735)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.mikepenz.materialdrawer.view.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:85)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
```

It's from May, 18.
I don't know if there is already a fix for this issue, but better be sure :D

**Comment by mikepenz** [comment]
@RubenGees it's no exception of the ScrimInsetsLayout. The exception is a RecyclerView exception and if you take a detailed look at the stackTrace you see it's thrown in the draw() method. 

Not sure if there is already an official android bug report regarding this

**Comment by RubenGees** [comment]
Oh yeah, sorry I missed that. I saw materialdrawer and thought it would have to do with the library. But I think it's better to ask them to have a bug nobody knows about.

**Comment by mikepenz** [comment]
@RubenGees i am not sure if there is already a bug report about this. i read something similar a few days ago
