### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#373]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{LoginActivity}: java.lang.ClassCastException: android.support.v7.internal.widget.ContentFrameLayout cannot be cast to android.support.v7.internal.widget.NativeActionModeAwareLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2114)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
	at android.app.ActivityThread.access$700(ActivityThread.java:143)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4960)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: android.support.v7.internal.widget.ContentFrameLayout cannot be cast to android.support.v7.internal.widget.NativeActionModeAwareLayout
	at android.support.v7.app.AppCompatDelegateImplV11.onSubDecorInstalled(AppCompatDelegateImplV11.java:44)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:405)
	at android.support.v7.app.AppCompatDelegateImplV7.onPostCreate(AppCompatDelegateImplV7.java:166)
	at android.support.v7.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:65)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1157)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097
```

**Comment by mikepenz** [comment]
@patelakshay13890 doesn't seem to be MaterialDrawer related? Any additional information?

**Comment by patelakshay13890** [comment]
WithOut lib. there is not any Error

**Comment by patelakshay13890** [comment]
Using lib. it gives me this error

**Comment by mikepenz** [comment]
@patelakshay13890 i am sure this error is caused by any other code, or some custom stuff you do.

My best bet (without googling for it) is that you have some troubles with the appcompat style and with things you need to change to use the appcompat library and style.
