### ISSUE TITLE
disable header clickable

### ISSUE THREAD

**Issue by chenleicpp** [mikepenz/MaterialDrawer#38]
this is the logcat?Can we disable header clickable?
02-26 14:17:21.657    9330-9330/com.mikepenz.materialdrawer.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mikepenz.materialdrawer.app, PID: 9330
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.mikepenz.materialdrawer.model.interfaces.IDrawerItem.getIdentifier()' on a null object reference
            at com.mikepenz.materialdrawer.app.SimpleDrawerActivity$1.onItemClick(SimpleDrawerActivity.java:116)
            at com.mikepenz.materialdrawer.Drawer$3.onItemClick(Drawer.java:803)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3046)
            at android.widget.AbsListView$3.run(AbsListView.java:3835)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5223)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

**Comment by mikepenz** [comment]
@chenleicpp that's true the header-element is clickable. 

in fact the onClick method can be fired without a DrawerItem, this has many different reasons.

It's always safer to check the drawerItem to be not null. 

Probably it would make sense to add a additional callback for onClick calls without a drawerItem?

**Comment by chenleicpp** [comment]
@mikepenz I just download your sample code and import to android studio,do nothing else,I think your code has a little bug with that and I read your document and can't found a public method to prevent or disable header click?Sorry for my bad English

**Comment by mikepenz** [comment]
@chenleicpp yeah i just took a look at the sample code. You are right i missed it there. Will update the sample with a fix for this. 

Preventing the click on a header isn't in, but definitely a good idea. Will add it to one of the next versions

**Comment by chenleicpp** [comment]
@mikepenz Thank your for your reply,wait for your update and learn from you
