### ISSUE TITLE
Error inflating class 

### ISSUE THREAD

**Issue by intxeon** [mikepenz/MaterialDrawer#409]
Hi Everyone
I'm trying to port an app on my phone but I'm getting this error:

```
E/AndroidRuntime(12948): FATAL EXCEPTION: main

E/AndroidRuntime(12948): Process: com.samsung.android.email.composer, PID: 12948

E/AndroidRuntime(12948): android.view.InflateException: Binary XML file line #54: Error inflating class com.samsung.android.email.composer.htmleditor.ToolBarView

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.createView(LayoutInflater.java:640)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)

E/AndroidRuntime(12948): 	at android.view.ViewStub.inflate(ViewStub.java:264)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.activity.MessageCompose.inflate_richtextToolbar(MessageCompose.java:3804)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.activity.MessageCompose.onFocusChange(MessageCompose.java:5679)

E/AndroidRuntime(12948): 	at android.view.View.onFocusChanged(View.java:5592)

E/AndroidRuntime(12948): 	at android.webkit.WebView.onFocusChanged(WebView.java:2420)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.HtmlEditingView.onFocusChanged(HtmlEditingView.java:452)

E/AndroidRuntime(12948): 	at android.view.View.handleFocusGainInternal(View.java:5347)

E/AndroidRuntime(12948): 	at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:652)

E/AndroidRuntime(12948): 	at android.view.View.requestFocusNoSearch(View.java:8080)

E/AndroidRuntime(12948): 	at android.view.View.requestFocus(View.java:8059)

E/AndroidRuntime(12948): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:2887)

E/AndroidRuntime(12948): 	at android.webkit.WebView.access$1001(WebView.java:249)

E/AndroidRuntime(12948): 	at android.webkit.WebView$PrivateAccess.super_requestFocus(WebView.java:2057)

E/AndroidRuntime(12948): 	at com.android.webview.chromium.WebViewChromium.requestFocus(WebViewChromium.java:1872)

E/AndroidRuntime(12948): 	at android.webkit.WebView.requestFocus(WebView.java:2448)

E/AndroidRuntime(12948): 	at android.view.View.requestFocus(View.java:8026)

E/AndroidRuntime(12948): 	at android.view.View.requestFocus(View.java:8005)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.activity.MessageCompose.onClick(MessageCompose.java:9377)

E/AndroidRuntime(12948): 	at android.view.View.performClick(View.java:5156)

E/AndroidRuntime(12948): 	at android.view.View$PerformClick.run(View.java:20755)

E/AndroidRuntime(12948): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(12948): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(12948): 	at android.os.Looper.loop(Looper.java:145)

E/AndroidRuntime(12948): 	at android.app.ActivityThread.main(ActivityThread.java:5832)

E/AndroidRuntime(12948): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(12948): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(12948): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)

E/AndroidRuntime(12948): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

E/AndroidRuntime(12948): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(12948): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(12948): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.createView(LayoutInflater.java:614)

E/AndroidRuntime(12948): 	... 33 more

E/AndroidRuntime(12948): Caused by: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.createView(LayoutInflater.java:640)

E/AndroidRuntime(12948): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)

E/AndroidRuntime(12948): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.ToolBarView$ToolBarScrollView.init(ToolBarView.java:1743)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.ToolBarView$ToolBarScrollView.<init>(ToolBarView.java:1733)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.ToolBarView$ToolBarScrollView.<init>(ToolBarView.java:1689)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.ToolBarView.createToolBarScrollView(ToolBarView.java:207)

E/AndroidRuntime(12948): 	at com.samsung.android.email.composer.htmleditor.ToolBarView.init(ToolBarVi
```

Can someone help me??

**Comment by mikepenz** [comment]
@intxeon this has nothing to do with the MaterialDrawer. ask @ stackoverflow or in any dev community. sorry.
