### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#419]
One of the users of my app got the following crash: 
```java
java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:625)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:478)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:781)
       at android.content.res.Resources.loadDrawable(Resources.java:1963)
       at android.content.res.Resources.getDrawable(Resources.java:672)
       at com.mikepenz.materialdrawer.util.UIUtils.getCompatDrawable(UIUtils.java:149)
       at com.mikepenz.materialdrawer.util.UIUtils.decideIcon(UIUtils.java:339)
       at com.mikepenz.materialdrawer.model.PrimaryDrawerItem.convertView(PrimaryDrawerItem.java:199)
       at com.mikepenz.materialdrawer.adapter.DrawerAdapter.getView(DrawerAdapter.java:141)
```

The Crash Logging Tool I use (Crashlytics) says he had around 100MB RAM left at the crash. Maybe you could dig into that?

**Comment by mikepenz** [comment]
@RubenGees for me this seems as a random crash. as the free RAM does not mean anything. I am also pretty sure the materialDrawer reference here is just random as it loaded the drawable, and this could happen everywhere. it was just bad luck that it states materialdrawer

**Comment by RubenGees** [comment]
Hmm, should I ignore it and hope it to never appear again? :D

**Comment by mikepenz** [comment]
@RubenGees there are some cases a OutOfMemory will happen and you can't do much about it. I don't know what the rest of your application does? My application wallsplash shows a lot of images and never had an OutOfMemory with the drawer, but with loading the images and other stuff. I was able to optimaze it and to minimize it, but i'm not able to totally remove them. If it happens all the time you have probably done something wrong. But if it happens once in a week or so with 1000 daily users you should be fine.

**Comment by RubenGees** [comment]
Hmm, okay thanks for the advice. The Memory of my App is mainly used by strings in the RAM (and that should not be much). It was the first crash of this type since release, 3 days ago.

**Comment by mikepenz** [comment]
@RubenGees what icons do you set for the drawer?

**Comment by RubenGees** [comment]
Regular drawables. This is one for example: https://github.com/RubenGees/Vocabletrainer/blob/master/app/src/main/res/drawable-hdpi/ic_list.png

**Comment by mikepenz** [comment]
@RubenGees ok should be fine. as long as the correct sizes are used.

**Comment by RubenGees** [comment]
Okay, I'll ignore it then. If this happens often and I can't find the issue myself, I'll report back.
