### ISSUE TITLE
.withShowDrawerOnFirstLaunch causing java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by wKovacs64** [mikepenz/MaterialDrawer#465]
Seems it broke in 3.1.1. Working as expected in 3.1.0. Here's the full stack trace:

```
07-08 21:52:18.970    7960-7960/com.example.drawertest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.drawertest/com.example.drawertest.MainActivity}: java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
            at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1322)
            at com.mikepenz.materialdrawer.DrawerBuilder.handleShowOnFirstLaunch(DrawerBuilder.java:1027)
            at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1299)
            at com.mikepenz.materialdrawer.DrawerBuilder.build(DrawerBuilder.java:1244)
            at com.example.drawertest.MainActivity.onCreate(MainActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

Reproduced on several emulators and a couple physical devices, across various Android versions. I created a [sample project](https://github.com/wKovacs64/DrawerTest) for testing purposes.

**Comment by mikepenz** [comment]
@wKovacs64 oh i see :/ broke it with this commit https://github.com/mikepenz/MaterialDrawer/commit/7c2385f21e9db55654a623f89b79f0bfde43781a
