### ISSUE TITLE
  java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.

### ISSUE THREAD

**Issue by Fshamri** [mikepenz/MaterialDrawer#518]
Hi,
Thanks for this awesome library, in fact, i tried to use it in my main activity but got the following error: 
  >   <h4>   java.lang.IllegalArgumentException: DrawerLayout must be measured with    MeasureSpec.EXACTLY.</h4>
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:831)
            at android.view.View.measure(View.java:16848)
            at android.widget.ListView.setupChild(ListView.java:1932)
            at android.widget.ListView.makeAndAddView(ListView.java:1857)
            at android.widget.ListView.fillUp(ListView.java:718)
            at android.widget.ListView.correctTooHigh(ListView.java:1410)
            at android.widget.ListView.fillSpecific(ListView.java:1348)
            at android.widget.ListView.layoutChildren(ListView.java:1657)
            at android.widget.AbsListView.onLayout(AbsListView.java:2444)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:931)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:15221)
            at android.view.ViewGroup.layout(ViewGroup.java:4793)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2260)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)

my code is like:

    @Override
       protected void onCreate(Bundle savedInstanceState) {
                        super.onCreate(savedInstanceState);
                        toolbar.setTitle(getString(R.string.today_story));
                        initDrawer(savedInstanceState);
                      //setFrame(1);
                      if (savedInstanceState == null) {
                               storyListFragment = new StoryListFragment();
                              storyListFragment.setToolbar(toolbar);
                             getSupportFragmentManager().beginTransaction()
                            .add(R.id.content_container, storyListFragment)
                           .commit();
                                 }
       }

the initDrawer function is:

    private void initDrawer(Bundle savedInstanceState) {
              mDrawer = new DrawerBuilder(this).withActivity(this)
                       .withToolbar(toolbar).withActionBarDrawerToggleAnimated(true)
                       .withHeader(R.layout.material_drawer).withHeaderDivider(false)
                       .withTranslucentStatusBar(false)
                      .addDrawerItems(new PrimaryDrawerItem().withName(R.string.drawer_item_stories).withIcon(getResources()
                            .getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(1),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_resources_stories).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(2),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_saved_Stories).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(3),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_sign_in).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(4),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_app_tour).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(5),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_settings).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(6),
                      new PrimaryDrawerItem().withName(R.string.drawer_item_info).withIcon(getResources().getDrawable(R.drawable.ic_drawer_top_stories)).withIdentifier(7)
              )
    .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener(){
                  @Override
                  public boolean onItemClick(AdapterView<?> adapterView, View view, int position, long id,      IDrawerItem mDrawerItem) {
                    if (mDrawerItem != null){
                         return true;
                       }
                         return false;
                     }
              }).withSavedInstance(savedInstanceState)
              .build();
       }

**Comment by mikepenz** [comment]
@Fshamri interesting. Which version are you using? How does your layout look like?


(you do not have to set the activity again if you already pass it via the constructor)

**Comment by Fshamri** [comment]
Hi,
I am using the latest version of your library along with support library v22
my activity_main layout is like: 

      <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
            xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
            android:layout_height="match_parent"
           android:orientation="vertical"
           tools:context=".MainActivity">

    
        <include
            layout="@layout/toolbar"/>

        
        <FrameLayout
            android:id="@+id/content_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </LinearLayout>

fragment_story.xml : 
           
      <RelativeLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:tools="http://schemas.android.com/tools"
      android:layout_width="match_parent"
      android:layout_height="match_parent">

    
    <com.creativeLabs.news.util.MySwipeRefreshLayout
        android:id="@+id/swipe_refresh_story"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity$PlaceholderFragment">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/list_view_story_list"

            android:overScrollMode="never"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

    </com.creativeLabs.news.util.MySwipeRefreshLayout>



</RelativeLayout>

**Comment by mikepenz** [comment]
@Fshamri latest version is relative as there is a preview of the upcoming v4.0.0 available :D But i assume you use v3.1.2

Do you use support v22.2.1?

**Comment by Fshamri** [comment]
Hi,
I use materialdrawer:3.1.2. and      'com.android.support:appcompat-v7:22.2.0

**Comment by mikepenz** [comment]
@Fshamri have you tried to update to v22.2.1 of the appcompat?

**Comment by Fshamri** [comment]
no. i will install it and try

**Comment by mikepenz** [comment]
@Fshamri ok please. thanks. i never had this issue with v3.1.2 and no one else had it. so it's strange
