### ISSUE TITLE
MaterialDrawer may cause crash on pre L Devices

### ISSUE THREAD

**Issue by marinica94** [mikepenz/MaterialDrawer#544]
I have updated my appcomat, android studio, gradle and all other stuffs to last version and on pre L devices I get the following error:

08-09 11:31:36.037  24120-24120/com.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example, PID: 24120
    java.lang.NoClassDefFoundError: android.support.v7.appcompat.R$layout
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:324)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.example.marian.digimusicstream.musicPlayer.onCreate(musicPlayer.java:95)
            at android.app.Activity.performCreate(Activity.java:5458)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5593)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

I think this is caused of this library, I have more libraries but when I change for example in style for pre L devices

this:
    <style name="AppBaseTheme" parent="MaterialDrawerTheme.Light">

to something like AppCompat.Theme.Light the error is changint into something like this:

    Process: com.example.marian.digimusicstream, PID: 14542
    java.lang.NoClassDefFoundError: android.support.v7.appcompat.R$attr

so from layout it goes to attr

line 95 in my app is the setContentView:

        setContentView(R.layout.activity_music_player);

I don't know if this is happening only on pre L or only on SAmsung devices because I found something over the internet that related this problem on Samsung, I tested my APP on Nexus 7 and LG G3 and it's working good, I don't say the problem is on library but I think there is something on library that may not work how it should with last android updates.
Thank you.

**Comment by mikepenz** [comment]
What was the issue?

**Comment by marinica94** [comment]
Recyclerview(22.2.1) and playservice (7.5.0) caused this. After updating them I was getting an error with java finished with non zero exit value 2 so I added in defaultConfig multiDexEnabled true witch solved the problem but caused the crash on pre l devices.

**Comment by mikepenz** [comment]
@marinica94 ah ok. so it was a problem with the methods count and incompatible support libs

**Comment by marinica94** [comment]
Yeah sorry for though it was from materialdrawer

**Comment by mikepenz** [comment]
No problem
