### ISSUE TITLE
Problem with buildView()

### ISSUE THREAD

**Issue by artemkutukov** [mikepenz/MaterialDrawer#545]
Hi Mike! I have a problem with create MaterialDrawer in landscape. But in version 3.0.8 all is well !

```java
DrawerBuilder builder = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .withFireOnInitialOnClick(false)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems()
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View view) {
                        KeyboardUtil.hideKeyboard(NavigationDrawer.this);
                    }

                    @Override
                    public void onDrawerClosed(View view) {
                        if (menuId != lastMenuId)
                            switchContent(getFragmentPosition(menuId));
                    }

                    @Override
                    public void onDrawerSlide(View view, float v) {

                    }
                })
                .withSavedInstance(savedInstanceState)
                .withSliderBackgroundColor(Color.parseColor("#42475C"));

        // Embed only if orientation is Landscape (regular drawer in Portrait)
        if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE && isTablet) {
            result = builder.buildView();
            frameLayout.addView(result.getSlider());
        } else {
            result = builder.build();
        }
```

```
Caused by: java.lang.NullPointerException
            at com.mikepenz.materialdrawer.DrawerBuilder.buildView(DrawerBuilder.java:1285)
            at com.test.NavigationDrawer.onCreate(NavigationDrawer.java:293)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bachhuberdesign** [comment]
Having the same (or similar) issue, specifically with this line on a 4.1 Nexus 7 test device.

if(VERSION.SDK_INT < 21) {
            this.mDrawerLayout.setDrawerShadow(drawable.drawer_shadow, this.mDrawerGravity.intValue());
        }

For whatever reason the drawable is giving a null pointer error in MaterialDrawer 3.1.2. I switched to 3.0.8 and it works fine.

**Comment by mikepenz** [comment]
@bachhuberdesign this issue is fixed (as far as i remember) on v4.0.0 which will be available soon. Thanks for the error report

**Comment by artemkutukov** [comment]
Ty, Mike ! You created awesome library!

**Comment by mikepenz** [comment]
@artemkutukov thank you so much ;)
