### ISSUE TITLE
1.0.2 version compile incompatibility with google-material-typeface

### ISSUE THREAD

**Issue by gpulido** [mikepenz/MaterialDrawer#56]
After update the materialDrawer to the 1.0.2 version, I get the following message:

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	...\Android\sdk\build-tools\21.1.1\dx.bat --dex --no-optimize --output D:\tmp\androidapplication\app\build\intermediates\dex\debug --input-list=D:\tmp\androidapplication\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/google_material_typeface_library/GoogleMaterial$Icon;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
		at com.android.dx.command.dexer.Main.run(Main.java:245)
		at com.android.dx.command.dexer.Main.main(Main.java:214)
		at com.android.dx.command.Main.main(Main.java:106)

I have narrowed it and the problem seems to be with the 
compile 'com.mikepenz.iconics:google-material-typeface:1.1.0@aar'

dependenci that I already have on the build.gradle

With the version 1.0.0 of the material drawer, the conflict didn't exist.

**Comment by mikepenz** [comment]
@gpulido you don't have to add the dependency anymore. it's now included in the main Android-Iconics project ;). It's default now because many use those icons by default. 

No need for the extra addon dependency. Just remove it and you're fine ;)
