### ISSUE TITLE
NullPointerException when adding sticky footer item programmatically

### ISSUE THREAD

**Issue by livotov** [mikepenz/MaterialDrawer#591]
Hi and thanks for the great library !

We're getting strange exception when adding sticky footer items into  the just created drawer - the following code 

```java
accountsSelector = new AccountHeaderBuilder().withActivity(this).withHeaderBackground(R.drawable.bg_profiles).build();
        appDrawer = new DrawerBuilder().withActivity(this).withTranslucentStatusBar(false).withActionBarDrawerToggle(false).withAccountHeader(accountsSelector).build();

        accountsSelector.addProfile(new ProfileDrawerItem().withIcon(getDrawableCompat(R.drawable.pref_icon_account_setup)).withName("Test Acc 1").withEmail("test@test.com"), 0);

        appDrawer.addItem(new SwitchDrawerItem().withCheckable(true).withChecked(true).withSwitchEnabled(true).withName("Some quick option").withIcon(R.drawable.ic_cast_light).withSelectable(false));
        appDrawer.addItem(new SwitchDrawerItem().withCheckable(true).withChecked(false).withSwitchEnabled(true).withName("Other quick option").withIcon(R.drawable.ic_play_light).withSelectable(false));
        appDrawer.addItem(new DividerDrawerItem());
        appDrawer.addItem(new PrimaryDrawerItem().withName("Some immediate action").withIcon(R.drawable.ic_pause_light).withSelectable(false));

        appDrawer.addStickyFooterItem(new SecondaryDrawerItem().withName(R.string.settings).withIcon(R.drawable.ic_setting_light).withIdentifier(R.id.settings).withSelectable(false));
        appDrawer.addStickyFooterItem(new SecondaryDrawerItem().withName(R.string.about_2do).withIcon(R.drawable.bs_ic_more_light).withIdentifier(R.id.about_copyrights).withSelectable(false));
```

results to the following exception on the first appDrawer.addStickyFooterItem call:
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
            at com.mikepenz.materialdrawer.DrawerUtils.fillStickyDrawerItemFooter(DrawerUtils.java:369)
            at com.mikepenz.materialdrawer.DrawerUtils.rebuildStickyFooterView(DrawerUtils.java:252)
            at com.mikepenz.materialdrawer.Drawer.addStickyFooterItem(Drawer.java:670)
            at com.app.activities.main.MainAppActivity.setupDrawer(MainAppActivity.java:188)
            at com.app.activities.main.MainAppActivity.onCreate(MainAppActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

however, if we  move adding sticky items into the drawer builder, everything works just fine. Are we doing something wrong with sticky footer items or this is a bug ?

Trying with the latest (4.0.1) version, building with api level 23.

Thanks,
Dmitri

**Comment by mikepenz** [comment]
@livotov seems to be an exception. will take a look at it later today. I assume that i try to use the `Context` which is available during the build process, but not after it was builded.
