### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#633]
I got the following exception:
```
java.lang.NullPointerException
       at com.mikepenz.materialdrawer.adapter.BaseDrawerAdapter$1.onClick(BaseDrawerAdapter.java:189)
       at android.view.View.performClick(View.java:3511)
       at android.view.View$PerformClick.run(View.java:14110)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

It happens like 1/1000 so it's not really important, but you may want to look into that.

**Comment by mikepenz** [comment]
@RubenGees which version do you use?

**Comment by RubenGees** [comment]
It is a bug which was reported in my bug-collector tool. It was in the last version I published, which used  the last available release 3.x of the Drawer before 4.x was released I think. So it's propably fixed, didn't thought of that...

**Comment by mikepenz** [comment]
@RubenGees ok can't support versions prior to the most up 2 date version. :)

**Comment by RubenGees** [comment]
Yes, sure, as I said it happens almost never so we can safely ignore this I think.
