### ISSUE TITLE
Possible crash issue

### ISSUE THREAD

**Issue by afollestad** [mikepenz/MaterialDrawer#672]
I just received this crash after selecting a nav drawer item:

```Gradle
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime: FATAL EXCEPTION: main
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime: Process: com.afollestad.sumptus, PID: 29276
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.computeVerticalScrollRange(RecyclerView.java:1581)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.onDrawScrollBars(View.java:13924)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.onDrawForeground(View.java:17657)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:16189)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3171)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15174)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:16181)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at com.mikepenz.materialize.view.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:88)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15174)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:15948)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.draw(View.java:16181)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:15174)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
09-20 18:52:44.946 29276-29276/com.afollestad.sumptus E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
```

**Comment by afollestad** [comment]
The reason I think it's related to this library is because of the `at com.mikepenz.materialize.view.ScrimInsetsFrameLayout.draw(ScrimInsetsFrameLayout.java:88)` line.

**Comment by afollestad** [comment]
Sorry, I think it's unrelated.

**Comment by mikepenz** [comment]
Yeah the `draw` method just passes the `Exception` to the next `draw` method
