### ISSUE TITLE
Is there a way to display the drawer below the toolbar without darkening it inside a CollapsingToolbar?

### ISSUE THREAD

**Issue by TheAndroidMaster** [mikepenz/MaterialDrawer#693]
This is a very specific question... The person I am making an app for wants the animated hamburger icon *and* a collapsing toolbar, but only the things below the toolbar to dim. I tried to use a custom container to sort that out, but since the content view's size changes as you scroll, I can partially understand why I got this exception

```
09-25 16:03:37.041  30906-30906/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.platypus.platypop, PID: 30906
    java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:831)
            at android.view.View.measure(View.java:17536)
            at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1335)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:434)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:582)
            at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:649)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5478)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at   com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2632)
            at android.view.View.measure(View.java:17536)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2102)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1218)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1435)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1106)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6018)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
            at android.view.Choreographer.doCallbacks(Choreographer.java:596)
            at android.view.Choreographer.doFrame(Choreographer.java:557)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

Is there another way around this or should I tell him it's impossible (and probably goes against every material design guideline known to man)? I could always just make it overlap everything on the activities with collapsing toolbars...

Drawer code:

```java
        headerResult = new AccountHeaderBuilder()
                .withActivity(MainActivity.this)
                .withCompactStyle(false)
                .withHeaderBackground(R.drawable.header)
                .withSavedInstance(savedInstanceState)
                .build();

        result = new DrawerBuilder()
                .withActivity(MainActivity.this)
                .withDisplayBelowToolbar(true)
                .withActionBarDrawerToggleAnimated(true)
                .withRootView(R.id.content_view)
                .withStatusBarColorRes(R.color.primary_dark)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .withSelectedItem(0)
                .addDrawerItems(
                        //pass your items here
                        new SecondaryDrawerItem().withName("Home").withIdentifier(1).withIcon(FontAwesome.Icon.faw_home),
                        new SecondaryDrawerItem().withName("Icons").withIdentifier(2).withIcon(FontAwesome.Icon.faw_android),
                        new SecondaryDrawerItem().withName("Wallpapers").withIdentifier(3).withIcon(FontAwesome.Icon.faw_picture_o),
                        new SecondaryDrawerItem().withName("Apply").withIdentifier(4).withIcon(FontAwesome.Icon.faw_archive),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName("About").withIdentifier(5).withIcon(FontAwesome.Icon.faw_info_circle)

                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        Intent i = null;
                        if (drawerItem.getIdentifier() == 1) {
                            i = new Intent(MainActivity.this, MainActivity.class);
                        } else if (drawerItem.getIdentifier() == 2) {
                            i = new Intent(MainActivity.this, Icons.class);
                        } else if (drawerItem.getIdentifier() == 3) {
                            i = new Intent(MainActivity.this, Wallpapers.class);
                        } else if (drawerItem.getIdentifier() == 4) {
                            i = new Intent(MainActivity.this, Apply.class);
                        } else if (drawerItem.getIdentifier() == 5) {
                            i = new Intent(MainActivity.this, About.class);
                        }
                        if (i != null) {
                            startActivity(i);
                        }
                        return false;
                    }
                })
                .build();
```

Layout:

```xml
    <android.support.design.widget.CoordinatorLayout
    android:id="@+id/product_detail_main_content"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="#EEEEEE"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:card_view="http://schemas.android.com/tools">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:foregroundGravity="bottom|right"
            android:foregroundTintMode="add"
            android:clipToPadding="true"
            app:contentScrim="@color/primary"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <ImageView
                android:id="@+id/header"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:src="@drawable/header"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax"
                app:layout_collapseParallaxMultiplier="0.7"/>


            <android.support.v7.widget.Toolbar
                xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="?actionBarSize"
                android:elevation="4dp"
                android:minHeight="?actionBarSize"
                android:transitionName="actionBar"
                android:fitsSystemWindows="true"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                android:id="@+id/toolbar"
                tools:ignore="UnusedAttribute" />

        </android.support.design.widget.CollapsingToolbarLayout>

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/content_view"
        android:fitsSystemWindows="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:fitsSystemWindows="true"
            android:orientation="vertical"
            android:paddingBottom="60dp" >

            <android.support.v7.widget.CardView
                android:layout_height="wrap_content"
                android:layout_width="fill_parent"
                app:cardUseCompatPadding="true"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"
                card_view:preventCornerOverlap="false"
                android:id="@+id/donatecard"
                android:visibility="gone" >
                <LinearLayout
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:layout_alignParentLeft="true"
                    android:layout_alignParentStart="true"
                    android:layout_alignParentTop="true"
                    android:orientation="vertical">
                    <ImageView
                        android:id="@+id/imageView"
                        android:layout_width="fill_parent"
                        android:layout_height="wrap_content"
                        android:scaleType="centerCrop"
                        android:src="@mipmap/googlecard" />
                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textAppearance="?android:attr/textAppearanceLarge"
                        android:text="Thanks for donating!"
                        android:layout_marginTop="16dp"
                        android:layout_marginBottom="12dp"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp" />
                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textAppearance="?android:attr/textAppearanceSmall"
                        android:text="Designing icons takes a lot of time and effort, and donations help a lot to motivate and support the addition of new icons."
                        android:layout_marginBottom="16dp"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp" />
                </LinearLayout>
            </android.support.v7.widget.CardView>

            <android.support.v7.widget.CardView
                android:layout_height="wrap_content"
                android:layout_width="fill_parent"
                app:cardUseCompatPadding="true"
                android:layout_margin="8dp">
                <LinearLayout
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <LinearLayout
                        android:orientation="horizontal"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginTop="8dp">

                        <com.platypus.platypop.SquareImageView
                            android:layout_width="50dp"
                            android:layout_height="50dp"
                            android:id="@+id/imageView7"
                            android:src="@mipmap/icons"
                            android:layout_gravity="center_vertical"
                            android:layout_marginLeft="16dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textAppearance="?android:attr/textAppearanceLarge"
                            android:text="Welcome to Platy Pop"
                            android:id="@+id/textView6"
                            android:layout_marginTop="16dp"
                            android:layout_marginBottom="12dp"
                            android:layout_marginLeft="16dp"
                            android:layout_marginRight="16dp" />
                    </LinearLayout>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textAppearance="?android:attr/textAppearanceSmall"
                        android:text="Platy Pop is a collection of material design icons designed to make your phone stand out."
                        android:id="@+id/textView7"
                        android:layout_marginBottom="8dp"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp" />

                    <Button
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:id="@+id/apply"
                        android:background="?attr/selectableItemBackgroundBorderless"
                        android:text="Apply"
                        android:layout_marginLeft="8dp"
                        android:layout_marginRight="8dp"
                        android:paddingLeft="8dp"
                        android:paddingRight="8dp"
                        android:textColor="@color/primary"
                        android:layout_marginBottom="8dp"
                        android:layout_gravity="right" />

                </LinearLayout>
            </android.support.v7.widget.CardView>
            <android.support.v7.widget.CardView
                android:layout_height="wrap_content"
                android:layout_width="fill_parent"
                app:cardUseCompatPadding="true"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginBottom="8dp">

                <LinearLayout
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <LinearLayout
                        android:orientation="horizontal"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginTop="8dp">

                        <com.platypus.platypop.SquareImageView
                            android:layout_width="50dp"
                            android:layout_height="50dp"
                            android:id="@+id/imageView8243546"
                            android:src="@mipmap/people"
                            android:layout_gravity="center_vertical"
                            android:layout_marginLeft="16dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textAppearance="?android:attr/textAppearanceLarge"
                            android:text="The Community"
                            android:id="@+id/textView63523"
                            android:layout_marginTop="16dp"
                            android:layout_marginBottom="12dp"
                            android:layout_marginLeft="16dp"
                            android:layout_marginRight="16dp" />
                    </LinearLayout>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textAppearance="?android:attr/textAppearanceSmall"
                        android:text="Check out the google plus community for more information about new icons and upcoming updates."
                        android:id="@+id/textView9"
                        android:layout_marginBottom="8dp"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp" />

                    <Button
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:id="@+id/community"
                        android:text="Google Plus"
                        android:layout_marginLeft="8dp"
                        android:layout_marginRight="8dp"
                        android:paddingLeft="8dp"
                        android:paddingRight="8dp"
                        android:layout_gravity="right"
                        android:background="?attr/selectableItemBackgroundBorderless"
                        android:textColor="@color/primary"
                        android:layout_marginBottom="8dp" />

                </LinearLayout>
            </android.support.v7.widget.CardView>
            <android.support.v7.widget.CardView
                android:layout_height="wrap_content"
                android:layout_width="fill_parent"
                app:cardUseCompatPadding="true"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginBottom="8dp">

                <LinearLayout
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <LinearLayout
                        android:orientation="horizontal"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginTop="8dp">

                        <com.platypus.platypop.SquareImageView
                            android:layout_width="50dp"
                            android:layout_height="50dp"
                            android:id="@+id/imageView723456"
                            android:src="@mipmap/about"
                            android:layout_gravity="center_vertical"
                            android:layout_marginLeft="16dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textAppearance="?android:attr/textAppearanceLarge"
                            android:text="The About Section"
                            android:id="@+id/textView632456"
                            android:layout_marginTop="16dp"
                            android:layout_marginBottom="12dp"
                            android:layout_marginLeft="16dp"
                            android:layout_marginRight="16dp" />
                    </LinearLayout>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textAppearance="?android:attr/textAppearanceSmall"
                        android:text="Information about this app&apos;s creator and designers."
                        android:id="@+id/textView11"
                        android:layout_marginBottom="8dp"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp" />
                    <Button
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:id="@+id/about"
                        android:text="About"
                        android:layout_marginLeft="8dp"
                        android:layout_marginRight="8dp"
                        android:paddingLeft="8dp"
                        android:paddingRight="8dp"
                        android:layout_gravity="right"
                        android:background="?attr/selectableItemBackgroundBorderless"
                        android:textColor="@color/primary"
                        android:layout_marginBottom="8dp" />

                </LinearLayout>
            </android.support.v7.widget.CardView>
        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>

    </android.support.design.widget.CoordinatorLayout>
```

**Comment by mikepenz** [comment]
it would be great if you could provide a small sample project showcasing your issue.

**Comment by TheAndroidMaster** [comment]
I'm working on it, it may take a few minutes. Or days, if I don't get time today  :stuck_out_tongue_closed_eyes:

**Comment by TheAndroidMaster** [comment]
Just uploaded it here:
https://drive.google.com/folder/d/0B5Z3jCEdoXV2ZkM5OWVxZWJ4YXM/edit
The third layout file may be slightly inaccurate but should have the same result.

**Comment by TheAndroidMaster** [comment]
Made an apk as well to save you time if you need it.
https://drive.google.com/file/d/0B5Z3jCEdoXV2RXlVejNUNzRGdlE/view?usp=sharing
Sorry, I should probably have made a test project as soon as I realized the problem...

**Comment by mikepenz** [comment]
@TheAndroidMaster thanks. will take a look later today

**Comment by mikepenz** [comment]
@TheAndroidMaster ok i just checked your source and the sample. and i'm afraid it is not possible to get this working. the problem is that the DrawerLayout will automatically add the shadowed area on top and on the right side if you open the drawer. you can make this area transparent but it will still catch the touches and close the drawer first. 

What i have to note. the activity you have created "what i don't want" is the only correct one in therms of the MaterialDesignGuidelines. And i think it's also the only possible. Why don't you want it like this?


I tried a completely different approach to have the drawer on top of the content but this will then consume the touch events and don't pass it forward to the scroll view.

**Comment by TheAndroidMaster** [comment]
Sorry for the confusion, I should probably have put "what someone that doesn't read the material design guidelines doesn't want", I am completely fine with it being full screen, all of my (other) apps use the drawer that way. I might be able to fix the dimming problem by making an action bar (replacing the toolbar) transparent (haven't tested this yet, might not work), but that would disable some of the other features of the app.  Thanks for looking into this, anyway.

**Comment by mikepenz** [comment]
@TheAndroidMaster no no it's fine. It's just a question why you want to go against the guidelines. Because in this exact case going with the non default implementation does not seem to be possible. (As far as my tests have shown. I tried a few things..)

If you go with an `ActionBar` i assume the `CollapsingToolbarLayout ` would not work anymore. 

I would really suggest that you have the drawer fullscreen. As mentioned above the view hirachy and how the layouts are placed an arranged prevents the drawer to be set below the `toolbar` but not flexible to the `CollapsingToolbarLayout`. Having the `DrawerLayout` in a complete other layer is also not possible, as the `DrawerLayout` does not pass touch events trough to the below views. (I even was not able to achieve this by changing the `DrawerLayout` class
