### ISSUE TITLE
Any change to pass to v.10.2 to 2.0.1

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#78]
Are there any modification to pas from version 1.0.2 to 2.0.1 ? for now I have an error
int his line com.mikepenz.materialdrawer.Drawer.build(Drawer.java:743)

 at com.mikepenz.materialdrawer.Drawer.build(Drawer.java:743)
       at ad.andorratelecom.eh2dashboard.DashBoard.onCreate(DashBoard.java:174)
       at android.app.Activity.performCreate(Activity.java:5283)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
       at android.app.ActivityThread.access$700(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:175)
       at android.app.ActivityThread.main(ActivityThread.java:5279)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01005a a=-1}
       at android.content.res.Resources.loadDrawable(Resources.java:2816)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)

**Comment by mikepenz** [comment]
Yeah there were some changes from the old version. 

The drawer now includes a theme which defines the colors for the drawer. if you don't use a provided theme you have to add those values to your styles. 

This is because i tried to make it as easy as possible for you to use the drawer without manually setting a dark style for it.

More details are here:
https://github.com/mikepenz/MaterialDrawer#important

Which referes to this:
https://github.com/mikepenz/MaterialDrawer#use-of-a-none-materialdrawer-style

**Comment by Spiderbezno** [comment]
Ok thx, I didn't had understand this part , now work perfectly
