### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by viettanbkdn** [mikepenz/MaterialDrawer#861]
I got this exception and app crashed when I opened my app, open another app, doing something and resuming to my app. This is the log from hockeyapp (my app run on android 5.0):

```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1014)
	at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1282)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2059)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2376)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1727)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2783)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2337)
	at android.view.View.dispatchPointerEvent(View.java:8585)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4074)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3940)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3614)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3671)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5759)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5733)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5704)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5878)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5828)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5901)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5274)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by mikepenz** [comment]
@viettanbkdn this log does not even contain the the package name of the `MaterialDrawer` :D Seems like a `DrawerLayout` issue.

**Comment by viettanbkdn** [comment]
Because my app use only your lib and your lib included DrawerLayout, so i think you can help me about this bug. I have searched on stackoverflow but did not get any solutions

**Comment by mikepenz** [comment]
@viettanbkdn yes that's true the lib adds the `DrawerLayout` but i can't change things of the support lib. The `DrawerLayout` is provided by `Google`. Does this issue happen each time? Or was it a one time crash?

**Comment by viettanbkdn** [comment]
@mikepenz got it 3 hours ago and did not test again

**Comment by mikepenz** [comment]
@viettanbkdn you just use the `DrawerLayout` from the **MaterialDrawer** as shown in the sample app. your layout does not contain a `DrawerLayout` nor do you use any custom behavior?

**Comment by viettanbkdn** [comment]
I use only DrawerLayout from your lib as default, my app does not have any DrawerLayout

**Comment by mikepenz** [comment]
@viettanbkdn ok please try it again and if it still happens post some more information .
