### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by feenixspz** [mikepenz/MaterialDrawer#862]
Hello, i am use v4.3.5, I get a lot of logs with similar content. Please, help me.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at com.mypackage.utils.DrawerUtils$2.onItemClick(DrawerUtils.java:257)
	at com.mikepenz.materialdrawer.DrawerUtils.setRecyclerViewSelection(DrawerUtils.java:108)
	at com.mikepenz.materialdrawer.Drawer.setSelectionAtPosition(Drawer.java:500)
	at com.mikepenz.materialdrawer.Drawer.setSelection(Drawer.java:434)
```

**Comment by mikepenz** [comment]
@feenixspz seems like you try to do something after the activity was closed. make sure that you don't call any functions after the activity was closed
