### ISSUE TITLE
NullPointer Exception since 4.6.0

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#887]
Hi,
I updated to the new version and get a NullPointer when I click on a DrawerItem. Logcat says the following:

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.mikepenz.materialdrawer.adapter.DrawerAdapter.getDrawerItems()' on a null object reference
  at com.mikepenz.materialdrawer.MiniDrawer.setSelection(MiniDrawer.java:334)
  at com.mikepenz.materialdrawer.MiniDrawer.onItemClick(MiniDrawer.java:320)
  at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1727)
  at com.mikepenz.materialdrawer.adapter.BaseDrawerAdapter$1.onClick(BaseDrawerAdapter.java:232)
  at android.view.View.performClick(View.java:4786)
  at android.view.View$PerformClick.run(View.java:19902)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5290)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

Thank you for your help!

**Comment by rubengees** [comment]
This happens with the primary items and the account header items, but not with the sticky items.

**Comment by mikepenz** [comment]
@rubengees which version did you update from?

**Comment by rubengees** [comment]
I'm not 100% sure, but I think the previous one 4.5.9

**Comment by rubengees** [comment]
No, I don't. Just the regular one, which is weird because the MiniDrawer pops up in the log.

**Comment by parseINT32** [comment]
Same here... i copied and pasted the builder from a project with the v3.0.9 build and with the new version it doesn't work.

![image](https://cloud.githubusercontent.com/assets/5663423/11929012/14ca4c54-a7d8-11e5-904e-d8e7923fefaf.png)

**Comment by mikepenz** [comment]
@rubengees oh i think what could cause this ... 

the problem is here. i missed to check the boolean ^^ stupid me 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1490

**Comment by rubengees** [comment]
Okay, great!

**Comment by mikepenz** [comment]
I will publish v4.6.1 with the fix later today.
