### ISSUE TITLE
Samsung galaxy s6 edge bug

### ISSUE THREAD

**Issue by xesun** [mikepenz/MaterialDrawer#889]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.mikepenz.materialdrawer.adapter.DrawerAdapter.getDrawerItems()' on a null object reference
    at com.mikepenz.materialdrawer.MiniDrawer.setSelection(MiniDrawer.java:334)
    at com.mikepenz.materialdrawer.MiniDrawer.onItemClick(MiniDrawer.java:320)
    at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1727)
    at com.mikepenz.materialdrawer.adapter.BaseDrawerAdapter$1.onClick(BaseDrawerAdapter.java:232)
```

**Comment by mikepenz** [comment]
Which version do you use?

**Comment by mikepenz** [comment]
Close as i assume that you are on v4.6.0
