### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Berlon** [mikepenz/MaterialDrawer#891]
Hello Mike,
I am following this tutorial [Google Analytics V4 API](http://www.codedevplus.com/google-analytics-v4-api-android/)

I have been struggling with implementing Google Analytics into the material drawer. I get the following error when the application is ran. Can you point me in the right direction how to fix this?

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rdvejuicecalculator.and.debug/com.rdvejuicecalculator.and.CustomContainerActivity}: java.lang.ClassCastException: com.rdvejuicecalculator.and.CustomApplication cannot be cast to com.rdvejuicecalculator.and.GoogleAnalyticsApp
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:162)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5431)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                                                    Caused by: java.lang.ClassCastException: com.rdvejuicecalculator.and.CustomApplication cannot be cast to com.rdvejuicecalculator.and.GoogleAnalyticsApp
                                                       at com.rdvejuicecalculator.and.CustomContainerActivity.onCreate(CustomContainerActivity.java:127)

**Comment by mikepenz** [comment]
@Berlon the issue is nothing specific to the `MaterialDrawer` sorry. But the exception already states. that it tries to cast the CustomApplication to a GoogleAnalyticsApp.
