### ISSUE TITLE
Null pointer if icon url is null for Profile Drawer

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#942]
Hi, withIcon says:

```java
public ProfileDrawerItem withIcon(@Nullable java.lang.String url)
```

but it crashes on null.

```
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:471)
       at android.net.Uri$StringUri.<init>(Uri.java:461)
       at android.net.Uri.parse(Uri.java:433)
       at com.mikepenz.materialize.holder.ImageHolder.<init>(ImageHolder.java:28)
       at com.mikepenz.materialdrawer.holder.ImageHolder.<init>(ImageHolder.java:28)
       at com.mikepenz.materialdrawer.model.ProfileDrawerItem.withIcon(ProfileDrawerItem.java:72)```
```
Im trying like this:

```java
AccountHeader headerResult = new AccountHeaderBuilder().withActivity(this)
        .withSelectionListEnabled(false)
        .withHeaderBackground(R.drawable.menu_header)
        .withOnAccountHeaderListener(this)
        .addProfiles(new ProfileDrawerItem().withIdentifier(R.id.drawer_item_profile)
            .withName(user.getName())
            .withEmail(user.getEmail())
            .withIcon(user.getPhotoUrl()))
        .build();
```

**Comment by mikepenz** [comment]
@danielgomezrico what do you try? 
As of the source code `withIcon` is not defined as `@Nullable` where do you read this?

**Comment by danielgomezrico** [comment]
F1 over `withIcon`. check image

![screen shot 2016-01-19 at 4 12 31 pm](https://cloud.githubusercontent.com/assets/76348/12432138/84947f40-bec7-11e5-9450-5d801bb2d8fa.png)

**Comment by mikepenz** [comment]
@danielgomezrico interesting enough. It seems that is added automatically
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L71

To fix this FC i would recommend to simply don't set the icon if the url is `null`

**Comment by danielgomezrico** [comment]
:+1:

**Comment by AKASH941** [comment]
good
