### ISSUE TITLE
Adding Drawer Items at specific positions leads to errors (v5.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by justjanne** [mikepenz/MaterialDrawer#990]
What did I do?

Added items at specific positions, where I was sure the position was valid.

```java
            assertFalse(position == -1);
            drawer.addItemAtPosition(item, position);
```

What happened: Sometimes this:

```
02-07 18:13:56.618 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: de.kuschku.quasseldroid_ng, PID: 9933
                                     java.lang.IndexOutOfBoundsException: Invalid index -1, size is 5
                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                         at java.util.ArrayList.addAll(ArrayList.java:226)
                                         at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:255)
                                         at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:241)
                                         at com.mikepenz.materialdrawer.Drawer.addItemAtPosition(Drawer.java:653)
                                         at de.kuschku.quasseldroid_ng.ui.chat.drawer.NewBufferViewConfigItem.rebuildNetworkList(NewBufferViewConfigItem.java:93)
                                         at de.kuschku.quasseldroid_ng.ui.chat.drawer.NewBufferViewConfigItem.<init>(NewBufferViewConfigItem.java:61)
                                         at de.kuschku.quasseldroid_ng.ui.chat.ChatActivity.selectBufferViewConfig(ChatActivity.java:566)
                                         at de.kuschku.quasseldroid_ng.ui.chat.ChatActivity.lambda$setupHeader$6(ChatActivity.java:510)
                                         at de.kuschku.quasseldroid_ng.ui.chat.ChatActivity.access$lambda$6(ChatActivity.java:0)
                                         at de.kuschku.quasseldroid_ng.ui.chat.ChatActivity$$Lambda$7.onProfileChanged(Unknown Source)
                                         at com.mikepenz.materialdrawer.AccountHeaderBuilder$7.onItemClick(AccountHeaderBuilder.java:1409)
                                         at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1671)
                                         at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1651)
                                         at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:311)
                                         at android.view.View.performClick(View.java:4761)
                                         at android.view.View$PerformClick.run(View.java:19767)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:135)
                                         at android.app.ActivityThread.main(ActivityThread.java:5310)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

What I expected:

No crash.

**Comment by justjanne** [comment]
@mikepenz The bug doesn’t occur when I only add items at the last position, btw. It always occurs when adding items in the first (0th) position.

**Comment by mikepenz** [comment]
it happens on the 0th position if you have added a header, which is not a bug as the header takes the 0th position. 

will it happen if you added it on any position between 1 - last item?

**Comment by justjanne** [comment]
I haven’t tested that yet.

The same bug occurs with the itemAdapter’s .add(position, item...) method, though, I had hoped that that would prevent the issue...

**Comment by mikepenz** [comment]
it also happens with the `FastAdapter`s add method? with position 0 :O ok that shouldn't be the case then

**Comment by justjanne** [comment]
Okay, I tested now:

drawer.addItemAtPosition
at com.mikepenz.fastadapter.adapters.ItemAdapter.add  

Position 0, empty adapter with header: works.
Position 1, empty adapter with header: crash (array index out of bounds: index 1, size is 0)
Position 0, full adapter with header: crash (array index out of bounds: index -1, size is 0)

**Comment by mikepenz** [comment]
@justjanne ok sorry for the confusion. I took a second look and have a properly description for you now. 

To make it more transparent for devs, the `FastAdapter` only works with the global position. In an earlier version i worked with the relative position (depending on the adapter used) but this was to confusing. So i switched to global positions only. So that means if ther eis a header, the first position of your items is `1` if no header is there the first position is `0`.
So you may ask now why does it fail with position `0` if there is a header. To get the global position i substract the number of items which are in the prior adapter. So `HeaderAdapter` with `1` item, `ItemAdapter` with `X` items. To get the global position here, i substract `position` provided by `1` (where `1` is the cound of items inside the `HeaderAdapter`)

**Comment by mikepenz** [comment]
If you want to work with the `Relative` position (which is the position specific to one adapter) you can do the following:

```java
mItemAdapter.getGlobalPosition(int relativePosition);
```

**Comment by justjanne** [comment]
@mikepenz Why does it crash then when I have a header and try to add elements at position 1?

**Comment by mikepenz** [comment]
@justjanne ok i can't reproduce this one. Just tried it, and it adds the item at the position. 

```java
result.addItemAtPosition(new DividerDrawerItem(), 1);
```

no crash
